// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A mox account, owning one or more email addresses.
type Account struct {
	pulumi.CustomResourceState

	// Account name (mox's account identifier).
	Account pulumi.StringOutput `pulumi:"account"`
	// Initial email address for the account, e.g. "user@example.com".
	Address pulumi.StringOutput `pulumi:"address"`
	// The password the account was created with — the supplied password, or a provider-generated one when none was supplied. Secret output; empty when an existing account was adopted. mox stores passwords hashed, so a password set out-of-band cannot be recovered here.
	EffectivePassword pulumi.StringOutput `pulumi:"effectivePassword"`
	// When true (mox's default), apply the delay to messages from first-time senders. Set false to disable it.
	FirstTimeSenderDelay pulumi.BoolPtrOutput `pulumi:"firstTimeSenderDelay"`
	// When a non-empty string, disable login and use the string as the rejection message. Empty (or unset) leaves login enabled.
	LoginDisabled pulumi.StringPtrOutput `pulumi:"loginDisabled"`
	// Maximum new (first-time) recipients per day. Unset (or 0) uses mox's default.
	MaxFirstTimeRecipientsPerDay pulumi.IntPtrOutput `pulumi:"maxFirstTimeRecipientsPerDay"`
	// Per-message size quota in bytes. Unset (or 0) uses the global default.
	MaxMessageSize pulumi.IntPtrOutput `pulumi:"maxMessageSize"`
	// Maximum messages the account may submit per day. Unset (or 0) uses mox's default.
	MaxOutgoingMessagesPerDay pulumi.IntPtrOutput `pulumi:"maxOutgoingMessagesPerDay"`
	// When true, forbid the account from setting its own password via the account web UI.
	NoCustomPassword pulumi.BoolPtrOutput `pulumi:"noCustomPassword"`
	// Optional account password. When set, it is applied via SetPassword. When omitted on a newly created account, the provider generates one and exposes it as the effectivePassword secret output.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Per-account outgoing routing rules, evaluated before the global routes.
	Routes AccountRouteArrayOutput `pulumi:"routes"`
}

// NewAccount registers a new resource with the given unique name, arguments, and options.
func NewAccount(ctx *pulumi.Context,
	name string, args *AccountArgs, opts ...pulumi.ResourceOption) (*Account, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Account == nil {
		return nil, errors.New("invalid value for required argument 'Account'")
	}
	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"effectivePassword",
		"password",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"account",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Account
	err := ctx.RegisterResource("mox:index:Account", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccount gets an existing Account resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountState, opts ...pulumi.ResourceOption) (*Account, error) {
	var resource Account
	err := ctx.ReadResource("mox:index:Account", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Account resources.
type accountState struct {
}

type AccountState struct {
}

func (AccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountState)(nil)).Elem()
}

type accountArgs struct {
	// Account name (mox's account identifier).
	Account string `pulumi:"account"`
	// Initial email address for the account, e.g. "user@example.com".
	Address string `pulumi:"address"`
	// When true (mox's default), apply the delay to messages from first-time senders. Set false to disable it.
	FirstTimeSenderDelay *bool `pulumi:"firstTimeSenderDelay"`
	// When a non-empty string, disable login and use the string as the rejection message. Empty (or unset) leaves login enabled.
	LoginDisabled *string `pulumi:"loginDisabled"`
	// Maximum new (first-time) recipients per day. Unset (or 0) uses mox's default.
	MaxFirstTimeRecipientsPerDay *int `pulumi:"maxFirstTimeRecipientsPerDay"`
	// Per-message size quota in bytes. Unset (or 0) uses the global default.
	MaxMessageSize *int `pulumi:"maxMessageSize"`
	// Maximum messages the account may submit per day. Unset (or 0) uses mox's default.
	MaxOutgoingMessagesPerDay *int `pulumi:"maxOutgoingMessagesPerDay"`
	// When true, forbid the account from setting its own password via the account web UI.
	NoCustomPassword *bool `pulumi:"noCustomPassword"`
	// Optional account password. When set, it is applied via SetPassword. When omitted on a newly created account, the provider generates one and exposes it as the effectivePassword secret output.
	Password *string `pulumi:"password"`
	// Per-account outgoing routing rules, evaluated before the global routes.
	Routes []AccountRoute `pulumi:"routes"`
}

// The set of arguments for constructing a Account resource.
type AccountArgs struct {
	// Account name (mox's account identifier).
	Account pulumi.StringInput
	// Initial email address for the account, e.g. "user@example.com".
	Address pulumi.StringInput
	// When true (mox's default), apply the delay to messages from first-time senders. Set false to disable it.
	FirstTimeSenderDelay pulumi.BoolPtrInput
	// When a non-empty string, disable login and use the string as the rejection message. Empty (or unset) leaves login enabled.
	LoginDisabled pulumi.StringPtrInput
	// Maximum new (first-time) recipients per day. Unset (or 0) uses mox's default.
	MaxFirstTimeRecipientsPerDay pulumi.IntPtrInput
	// Per-message size quota in bytes. Unset (or 0) uses the global default.
	MaxMessageSize pulumi.IntPtrInput
	// Maximum messages the account may submit per day. Unset (or 0) uses mox's default.
	MaxOutgoingMessagesPerDay pulumi.IntPtrInput
	// When true, forbid the account from setting its own password via the account web UI.
	NoCustomPassword pulumi.BoolPtrInput
	// Optional account password. When set, it is applied via SetPassword. When omitted on a newly created account, the provider generates one and exposes it as the effectivePassword secret output.
	Password pulumi.StringPtrInput
	// Per-account outgoing routing rules, evaluated before the global routes.
	Routes AccountRouteArrayInput
}

func (AccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountArgs)(nil)).Elem()
}

type AccountInput interface {
	pulumi.Input

	ToAccountOutput() AccountOutput
	ToAccountOutputWithContext(ctx context.Context) AccountOutput
}

func (*Account) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (i *Account) ToAccountOutput() AccountOutput {
	return i.ToAccountOutputWithContext(context.Background())
}

func (i *Account) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOutput)
}

// AccountArrayInput is an input type that accepts AccountArray and AccountArrayOutput values.
// You can construct a concrete instance of `AccountArrayInput` via:
//
//	AccountArray{ AccountArgs{...} }
type AccountArrayInput interface {
	pulumi.Input

	ToAccountArrayOutput() AccountArrayOutput
	ToAccountArrayOutputWithContext(context.Context) AccountArrayOutput
}

type AccountArray []AccountInput

func (AccountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (i AccountArray) ToAccountArrayOutput() AccountArrayOutput {
	return i.ToAccountArrayOutputWithContext(context.Background())
}

func (i AccountArray) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountArrayOutput)
}

// AccountMapInput is an input type that accepts AccountMap and AccountMapOutput values.
// You can construct a concrete instance of `AccountMapInput` via:
//
//	AccountMap{ "key": AccountArgs{...} }
type AccountMapInput interface {
	pulumi.Input

	ToAccountMapOutput() AccountMapOutput
	ToAccountMapOutputWithContext(context.Context) AccountMapOutput
}

type AccountMap map[string]AccountInput

func (AccountMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (i AccountMap) ToAccountMapOutput() AccountMapOutput {
	return i.ToAccountMapOutputWithContext(context.Background())
}

func (i AccountMap) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountMapOutput)
}

type AccountOutput struct{ *pulumi.OutputState }

func (AccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (o AccountOutput) ToAccountOutput() AccountOutput {
	return o
}

func (o AccountOutput) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return o
}

// Account name (mox's account identifier).
func (o AccountOutput) Account() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.Account }).(pulumi.StringOutput)
}

// Initial email address for the account, e.g. "user@example.com".
func (o AccountOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// The password the account was created with — the supplied password, or a provider-generated one when none was supplied. Secret output; empty when an existing account was adopted. mox stores passwords hashed, so a password set out-of-band cannot be recovered here.
func (o AccountOutput) EffectivePassword() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.EffectivePassword }).(pulumi.StringOutput)
}

// When true (mox's default), apply the delay to messages from first-time senders. Set false to disable it.
func (o AccountOutput) FirstTimeSenderDelay() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.BoolPtrOutput { return v.FirstTimeSenderDelay }).(pulumi.BoolPtrOutput)
}

// When a non-empty string, disable login and use the string as the rejection message. Empty (or unset) leaves login enabled.
func (o AccountOutput) LoginDisabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.StringPtrOutput { return v.LoginDisabled }).(pulumi.StringPtrOutput)
}

// Maximum new (first-time) recipients per day. Unset (or 0) uses mox's default.
func (o AccountOutput) MaxFirstTimeRecipientsPerDay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.IntPtrOutput { return v.MaxFirstTimeRecipientsPerDay }).(pulumi.IntPtrOutput)
}

// Per-message size quota in bytes. Unset (or 0) uses the global default.
func (o AccountOutput) MaxMessageSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.IntPtrOutput { return v.MaxMessageSize }).(pulumi.IntPtrOutput)
}

// Maximum messages the account may submit per day. Unset (or 0) uses mox's default.
func (o AccountOutput) MaxOutgoingMessagesPerDay() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.IntPtrOutput { return v.MaxOutgoingMessagesPerDay }).(pulumi.IntPtrOutput)
}

// When true, forbid the account from setting its own password via the account web UI.
func (o AccountOutput) NoCustomPassword() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.BoolPtrOutput { return v.NoCustomPassword }).(pulumi.BoolPtrOutput)
}

// Optional account password. When set, it is applied via SetPassword. When omitted on a newly created account, the provider generates one and exposes it as the effectivePassword secret output.
func (o AccountOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// Per-account outgoing routing rules, evaluated before the global routes.
func (o AccountOutput) Routes() AccountRouteArrayOutput {
	return o.ApplyT(func(v *Account) AccountRouteArrayOutput { return v.Routes }).(AccountRouteArrayOutput)
}

type AccountArrayOutput struct{ *pulumi.OutputState }

func (AccountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (o AccountArrayOutput) ToAccountArrayOutput() AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) Index(i pulumi.IntInput) AccountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Account {
		return vs[0].([]*Account)[vs[1].(int)]
	}).(AccountOutput)
}

type AccountMapOutput struct{ *pulumi.OutputState }

func (AccountMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (o AccountMapOutput) ToAccountMapOutput() AccountMapOutput {
	return o
}

func (o AccountMapOutput) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return o
}

func (o AccountMapOutput) MapIndex(k pulumi.StringInput) AccountOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Account {
		return vs[0].(map[string]*Account)[vs[1].(string)]
	}).(AccountOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountInput)(nil)).Elem(), &Account{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountArrayInput)(nil)).Elem(), AccountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountMapInput)(nil)).Elem(), AccountMap{})
	pulumi.RegisterOutputType(AccountOutput{})
	pulumi.RegisterOutputType(AccountArrayOutput{})
	pulumi.RegisterOutputType(AccountMapOutput{})
}
