// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A mox alias (mailing list): an address whose mail is delivered to a set of member account addresses.
type Alias struct {
	pulumi.CustomResourceState

	// Full alias address, e.g. "list@example.com".
	Address pulumi.StringOutput `pulumi:"address"`
	// Allow members to use the alias address in the From header. Defaults to false.
	AllowMsgFrom pulumi.BoolPtrOutput `pulumi:"allowMsgFrom"`
	// Allow members to see the membership list. Defaults to false.
	ListMembers pulumi.BoolPtrOutput `pulumi:"listMembers"`
	// Member account addresses that receive mail sent to the alias.
	Members pulumi.StringArrayOutput `pulumi:"members"`
	// Allow anyone (not just members) to send to the alias. Defaults to false.
	PostPublic pulumi.BoolPtrOutput `pulumi:"postPublic"`
}

// NewAlias registers a new resource with the given unique name, arguments, and options.
func NewAlias(ctx *pulumi.Context,
	name string, args *AliasArgs, opts ...pulumi.ResourceOption) (*Alias, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.Members == nil {
		return nil, errors.New("invalid value for required argument 'Members'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"address",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Alias
	err := ctx.RegisterResource("mox:index:Alias", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAlias gets an existing Alias resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAlias(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AliasState, opts ...pulumi.ResourceOption) (*Alias, error) {
	var resource Alias
	err := ctx.ReadResource("mox:index:Alias", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Alias resources.
type aliasState struct {
}

type AliasState struct {
}

func (AliasState) ElementType() reflect.Type {
	return reflect.TypeOf((*aliasState)(nil)).Elem()
}

type aliasArgs struct {
	// Full alias address, e.g. "list@example.com".
	Address string `pulumi:"address"`
	// Allow members to use the alias address in the From header. Defaults to false.
	AllowMsgFrom *bool `pulumi:"allowMsgFrom"`
	// Allow members to see the membership list. Defaults to false.
	ListMembers *bool `pulumi:"listMembers"`
	// Member account addresses that receive mail sent to the alias.
	Members []string `pulumi:"members"`
	// Allow anyone (not just members) to send to the alias. Defaults to false.
	PostPublic *bool `pulumi:"postPublic"`
}

// The set of arguments for constructing a Alias resource.
type AliasArgs struct {
	// Full alias address, e.g. "list@example.com".
	Address pulumi.StringInput
	// Allow members to use the alias address in the From header. Defaults to false.
	AllowMsgFrom pulumi.BoolPtrInput
	// Allow members to see the membership list. Defaults to false.
	ListMembers pulumi.BoolPtrInput
	// Member account addresses that receive mail sent to the alias.
	Members pulumi.StringArrayInput
	// Allow anyone (not just members) to send to the alias. Defaults to false.
	PostPublic pulumi.BoolPtrInput
}

func (AliasArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aliasArgs)(nil)).Elem()
}

type AliasInput interface {
	pulumi.Input

	ToAliasOutput() AliasOutput
	ToAliasOutputWithContext(ctx context.Context) AliasOutput
}

func (*Alias) ElementType() reflect.Type {
	return reflect.TypeOf((**Alias)(nil)).Elem()
}

func (i *Alias) ToAliasOutput() AliasOutput {
	return i.ToAliasOutputWithContext(context.Background())
}

func (i *Alias) ToAliasOutputWithContext(ctx context.Context) AliasOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AliasOutput)
}

// AliasArrayInput is an input type that accepts AliasArray and AliasArrayOutput values.
// You can construct a concrete instance of `AliasArrayInput` via:
//
//	AliasArray{ AliasArgs{...} }
type AliasArrayInput interface {
	pulumi.Input

	ToAliasArrayOutput() AliasArrayOutput
	ToAliasArrayOutputWithContext(context.Context) AliasArrayOutput
}

type AliasArray []AliasInput

func (AliasArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alias)(nil)).Elem()
}

func (i AliasArray) ToAliasArrayOutput() AliasArrayOutput {
	return i.ToAliasArrayOutputWithContext(context.Background())
}

func (i AliasArray) ToAliasArrayOutputWithContext(ctx context.Context) AliasArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AliasArrayOutput)
}

// AliasMapInput is an input type that accepts AliasMap and AliasMapOutput values.
// You can construct a concrete instance of `AliasMapInput` via:
//
//	AliasMap{ "key": AliasArgs{...} }
type AliasMapInput interface {
	pulumi.Input

	ToAliasMapOutput() AliasMapOutput
	ToAliasMapOutputWithContext(context.Context) AliasMapOutput
}

type AliasMap map[string]AliasInput

func (AliasMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alias)(nil)).Elem()
}

func (i AliasMap) ToAliasMapOutput() AliasMapOutput {
	return i.ToAliasMapOutputWithContext(context.Background())
}

func (i AliasMap) ToAliasMapOutputWithContext(ctx context.Context) AliasMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AliasMapOutput)
}

type AliasOutput struct{ *pulumi.OutputState }

func (AliasOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Alias)(nil)).Elem()
}

func (o AliasOutput) ToAliasOutput() AliasOutput {
	return o
}

func (o AliasOutput) ToAliasOutputWithContext(ctx context.Context) AliasOutput {
	return o
}

// Full alias address, e.g. "list@example.com".
func (o AliasOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *Alias) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// Allow members to use the alias address in the From header. Defaults to false.
func (o AliasOutput) AllowMsgFrom() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Alias) pulumi.BoolPtrOutput { return v.AllowMsgFrom }).(pulumi.BoolPtrOutput)
}

// Allow members to see the membership list. Defaults to false.
func (o AliasOutput) ListMembers() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Alias) pulumi.BoolPtrOutput { return v.ListMembers }).(pulumi.BoolPtrOutput)
}

// Member account addresses that receive mail sent to the alias.
func (o AliasOutput) Members() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Alias) pulumi.StringArrayOutput { return v.Members }).(pulumi.StringArrayOutput)
}

// Allow anyone (not just members) to send to the alias. Defaults to false.
func (o AliasOutput) PostPublic() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Alias) pulumi.BoolPtrOutput { return v.PostPublic }).(pulumi.BoolPtrOutput)
}

type AliasArrayOutput struct{ *pulumi.OutputState }

func (AliasArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Alias)(nil)).Elem()
}

func (o AliasArrayOutput) ToAliasArrayOutput() AliasArrayOutput {
	return o
}

func (o AliasArrayOutput) ToAliasArrayOutputWithContext(ctx context.Context) AliasArrayOutput {
	return o
}

func (o AliasArrayOutput) Index(i pulumi.IntInput) AliasOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Alias {
		return vs[0].([]*Alias)[vs[1].(int)]
	}).(AliasOutput)
}

type AliasMapOutput struct{ *pulumi.OutputState }

func (AliasMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Alias)(nil)).Elem()
}

func (o AliasMapOutput) ToAliasMapOutput() AliasMapOutput {
	return o
}

func (o AliasMapOutput) ToAliasMapOutputWithContext(ctx context.Context) AliasMapOutput {
	return o
}

func (o AliasMapOutput) MapIndex(k pulumi.StringInput) AliasOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Alias {
		return vs[0].(map[string]*Alias)[vs[1].(string)]
	}).(AliasOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AliasInput)(nil)).Elem(), &Alias{})
	pulumi.RegisterInputType(reflect.TypeOf((*AliasArrayInput)(nil)).Elem(), AliasArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AliasMapInput)(nil)).Elem(), AliasMap{})
	pulumi.RegisterOutputType(AliasOutput{})
	pulumi.RegisterOutputType(AliasArrayOutput{})
	pulumi.RegisterOutputType(AliasMapOutput{})
}
