// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// DNS blocklists to monitor for outgoing IP listings without using them for incoming-message rejection.
type DNSBLMonitoring struct {
	pulumi.CustomResourceState

	// DNSBL zones to monitor, e.g. sbl.spamhaus.org.
	Zones pulumi.StringArrayOutput `pulumi:"zones"`
}

// NewDNSBLMonitoring registers a new resource with the given unique name, arguments, and options.
func NewDNSBLMonitoring(ctx *pulumi.Context,
	name string, args *DNSBLMonitoringArgs, opts ...pulumi.ResourceOption) (*DNSBLMonitoring, error) {
	if args == nil {
		args = &DNSBLMonitoringArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DNSBLMonitoring
	err := ctx.RegisterResource("mox:index:DNSBLMonitoring", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDNSBLMonitoring gets an existing DNSBLMonitoring resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDNSBLMonitoring(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DNSBLMonitoringState, opts ...pulumi.ResourceOption) (*DNSBLMonitoring, error) {
	var resource DNSBLMonitoring
	err := ctx.ReadResource("mox:index:DNSBLMonitoring", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DNSBLMonitoring resources.
type dnsblmonitoringState struct {
}

type DNSBLMonitoringState struct {
}

func (DNSBLMonitoringState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsblmonitoringState)(nil)).Elem()
}

type dnsblmonitoringArgs struct {
	// DNSBL zones to monitor, e.g. sbl.spamhaus.org.
	Zones []string `pulumi:"zones"`
}

// The set of arguments for constructing a DNSBLMonitoring resource.
type DNSBLMonitoringArgs struct {
	// DNSBL zones to monitor, e.g. sbl.spamhaus.org.
	Zones pulumi.StringArrayInput
}

func (DNSBLMonitoringArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsblmonitoringArgs)(nil)).Elem()
}

type DNSBLMonitoringInput interface {
	pulumi.Input

	ToDNSBLMonitoringOutput() DNSBLMonitoringOutput
	ToDNSBLMonitoringOutputWithContext(ctx context.Context) DNSBLMonitoringOutput
}

func (*DNSBLMonitoring) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSBLMonitoring)(nil)).Elem()
}

func (i *DNSBLMonitoring) ToDNSBLMonitoringOutput() DNSBLMonitoringOutput {
	return i.ToDNSBLMonitoringOutputWithContext(context.Background())
}

func (i *DNSBLMonitoring) ToDNSBLMonitoringOutputWithContext(ctx context.Context) DNSBLMonitoringOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSBLMonitoringOutput)
}

// DNSBLMonitoringArrayInput is an input type that accepts DNSBLMonitoringArray and DNSBLMonitoringArrayOutput values.
// You can construct a concrete instance of `DNSBLMonitoringArrayInput` via:
//
//	DNSBLMonitoringArray{ DNSBLMonitoringArgs{...} }
type DNSBLMonitoringArrayInput interface {
	pulumi.Input

	ToDNSBLMonitoringArrayOutput() DNSBLMonitoringArrayOutput
	ToDNSBLMonitoringArrayOutputWithContext(context.Context) DNSBLMonitoringArrayOutput
}

type DNSBLMonitoringArray []DNSBLMonitoringInput

func (DNSBLMonitoringArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSBLMonitoring)(nil)).Elem()
}

func (i DNSBLMonitoringArray) ToDNSBLMonitoringArrayOutput() DNSBLMonitoringArrayOutput {
	return i.ToDNSBLMonitoringArrayOutputWithContext(context.Background())
}

func (i DNSBLMonitoringArray) ToDNSBLMonitoringArrayOutputWithContext(ctx context.Context) DNSBLMonitoringArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSBLMonitoringArrayOutput)
}

// DNSBLMonitoringMapInput is an input type that accepts DNSBLMonitoringMap and DNSBLMonitoringMapOutput values.
// You can construct a concrete instance of `DNSBLMonitoringMapInput` via:
//
//	DNSBLMonitoringMap{ "key": DNSBLMonitoringArgs{...} }
type DNSBLMonitoringMapInput interface {
	pulumi.Input

	ToDNSBLMonitoringMapOutput() DNSBLMonitoringMapOutput
	ToDNSBLMonitoringMapOutputWithContext(context.Context) DNSBLMonitoringMapOutput
}

type DNSBLMonitoringMap map[string]DNSBLMonitoringInput

func (DNSBLMonitoringMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSBLMonitoring)(nil)).Elem()
}

func (i DNSBLMonitoringMap) ToDNSBLMonitoringMapOutput() DNSBLMonitoringMapOutput {
	return i.ToDNSBLMonitoringMapOutputWithContext(context.Background())
}

func (i DNSBLMonitoringMap) ToDNSBLMonitoringMapOutputWithContext(ctx context.Context) DNSBLMonitoringMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DNSBLMonitoringMapOutput)
}

type DNSBLMonitoringOutput struct{ *pulumi.OutputState }

func (DNSBLMonitoringOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSBLMonitoring)(nil)).Elem()
}

func (o DNSBLMonitoringOutput) ToDNSBLMonitoringOutput() DNSBLMonitoringOutput {
	return o
}

func (o DNSBLMonitoringOutput) ToDNSBLMonitoringOutputWithContext(ctx context.Context) DNSBLMonitoringOutput {
	return o
}

// DNSBL zones to monitor, e.g. sbl.spamhaus.org.
func (o DNSBLMonitoringOutput) Zones() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DNSBLMonitoring) pulumi.StringArrayOutput { return v.Zones }).(pulumi.StringArrayOutput)
}

type DNSBLMonitoringArrayOutput struct{ *pulumi.OutputState }

func (DNSBLMonitoringArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DNSBLMonitoring)(nil)).Elem()
}

func (o DNSBLMonitoringArrayOutput) ToDNSBLMonitoringArrayOutput() DNSBLMonitoringArrayOutput {
	return o
}

func (o DNSBLMonitoringArrayOutput) ToDNSBLMonitoringArrayOutputWithContext(ctx context.Context) DNSBLMonitoringArrayOutput {
	return o
}

func (o DNSBLMonitoringArrayOutput) Index(i pulumi.IntInput) DNSBLMonitoringOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DNSBLMonitoring {
		return vs[0].([]*DNSBLMonitoring)[vs[1].(int)]
	}).(DNSBLMonitoringOutput)
}

type DNSBLMonitoringMapOutput struct{ *pulumi.OutputState }

func (DNSBLMonitoringMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DNSBLMonitoring)(nil)).Elem()
}

func (o DNSBLMonitoringMapOutput) ToDNSBLMonitoringMapOutput() DNSBLMonitoringMapOutput {
	return o
}

func (o DNSBLMonitoringMapOutput) ToDNSBLMonitoringMapOutputWithContext(ctx context.Context) DNSBLMonitoringMapOutput {
	return o
}

func (o DNSBLMonitoringMapOutput) MapIndex(k pulumi.StringInput) DNSBLMonitoringOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DNSBLMonitoring {
		return vs[0].(map[string]*DNSBLMonitoring)[vs[1].(string)]
	}).(DNSBLMonitoringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DNSBLMonitoringInput)(nil)).Elem(), &DNSBLMonitoring{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSBLMonitoringArrayInput)(nil)).Elem(), DNSBLMonitoringArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DNSBLMonitoringMapInput)(nil)).Elem(), DNSBLMonitoringMap{})
	pulumi.RegisterOutputType(DNSBLMonitoringOutput{})
	pulumi.RegisterOutputType(DNSBLMonitoringArrayOutput{})
	pulumi.RegisterOutputType(DNSBLMonitoringMapOutput{})
}
