// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A DKIM selector on a mox domain, optionally enabled for signing.
type DomainDKIMSelector struct {
	pulumi.CustomResourceState

	// Key algorithm used when creating the selector, e.g. ed25519 or rsa-2048. Changing it replaces the selector.
	Algorithm pulumi.StringPtrOutput `pulumi:"algorithm"`
	// Enable relaxed body canonicalization.
	BodyRelaxed pulumi.BoolPtrOutput `pulumi:"bodyRelaxed"`
	// Mox domain that owns the selector.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Hash mox uses after applying defaults.
	EffectiveHash pulumi.StringOutput `pulumi:"effectiveHash"`
	// DKIM hash algorithm, normally sha256.
	Hash pulumi.StringPtrOutput `pulumi:"hash"`
	// Enable relaxed header canonicalization.
	HeaderRelaxed pulumi.BoolPtrOutput `pulumi:"headerRelaxed"`
	// Headers to sign. Empty uses mox's default set.
	Headers pulumi.StringArrayOutput `pulumi:"headers"`
	// DKIM signature lifetime for a newly generated selector.
	LifetimeSeconds pulumi.IntPtrOutput `pulumi:"lifetimeSeconds"`
	// Server-side key file generated/stored by mox.
	PrivateKeyFile pulumi.StringOutput `pulumi:"privateKeyFile"`
	// Prevent duplicate headers from being added. Defaults to true.
	SealHeaders pulumi.BoolPtrOutput `pulumi:"sealHeaders"`
	// DKIM selector label.
	Selector pulumi.StringOutput `pulumi:"selector"`
	// Enable this selector for signing outgoing mail.
	Sign pulumi.BoolPtrOutput `pulumi:"sign"`
}

// NewDomainDKIMSelector registers a new resource with the given unique name, arguments, and options.
func NewDomainDKIMSelector(ctx *pulumi.Context,
	name string, args *DomainDKIMSelectorArgs, opts ...pulumi.ResourceOption) (*DomainDKIMSelector, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Selector == nil {
		return nil, errors.New("invalid value for required argument 'Selector'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"algorithm",
		"domain",
		"selector",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainDKIMSelector
	err := ctx.RegisterResource("mox:index:DomainDKIMSelector", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainDKIMSelector gets an existing DomainDKIMSelector resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainDKIMSelector(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainDKIMSelectorState, opts ...pulumi.ResourceOption) (*DomainDKIMSelector, error) {
	var resource DomainDKIMSelector
	err := ctx.ReadResource("mox:index:DomainDKIMSelector", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainDKIMSelector resources.
type domainDKIMSelectorState struct {
}

type DomainDKIMSelectorState struct {
}

func (DomainDKIMSelectorState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainDKIMSelectorState)(nil)).Elem()
}

type domainDKIMSelectorArgs struct {
	// Key algorithm used when creating the selector, e.g. ed25519 or rsa-2048. Changing it replaces the selector.
	Algorithm *string `pulumi:"algorithm"`
	// Enable relaxed body canonicalization.
	BodyRelaxed *bool `pulumi:"bodyRelaxed"`
	// Mox domain that owns the selector.
	Domain string `pulumi:"domain"`
	// DKIM hash algorithm, normally sha256.
	Hash *string `pulumi:"hash"`
	// Enable relaxed header canonicalization.
	HeaderRelaxed *bool `pulumi:"headerRelaxed"`
	// Headers to sign. Empty uses mox's default set.
	Headers []string `pulumi:"headers"`
	// DKIM signature lifetime for a newly generated selector.
	LifetimeSeconds *int `pulumi:"lifetimeSeconds"`
	// Prevent duplicate headers from being added. Defaults to true.
	SealHeaders *bool `pulumi:"sealHeaders"`
	// DKIM selector label.
	Selector string `pulumi:"selector"`
	// Enable this selector for signing outgoing mail.
	Sign *bool `pulumi:"sign"`
}

// The set of arguments for constructing a DomainDKIMSelector resource.
type DomainDKIMSelectorArgs struct {
	// Key algorithm used when creating the selector, e.g. ed25519 or rsa-2048. Changing it replaces the selector.
	Algorithm pulumi.StringPtrInput
	// Enable relaxed body canonicalization.
	BodyRelaxed pulumi.BoolPtrInput
	// Mox domain that owns the selector.
	Domain pulumi.StringInput
	// DKIM hash algorithm, normally sha256.
	Hash pulumi.StringPtrInput
	// Enable relaxed header canonicalization.
	HeaderRelaxed pulumi.BoolPtrInput
	// Headers to sign. Empty uses mox's default set.
	Headers pulumi.StringArrayInput
	// DKIM signature lifetime for a newly generated selector.
	LifetimeSeconds pulumi.IntPtrInput
	// Prevent duplicate headers from being added. Defaults to true.
	SealHeaders pulumi.BoolPtrInput
	// DKIM selector label.
	Selector pulumi.StringInput
	// Enable this selector for signing outgoing mail.
	Sign pulumi.BoolPtrInput
}

func (DomainDKIMSelectorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainDKIMSelectorArgs)(nil)).Elem()
}

type DomainDKIMSelectorInput interface {
	pulumi.Input

	ToDomainDKIMSelectorOutput() DomainDKIMSelectorOutput
	ToDomainDKIMSelectorOutputWithContext(ctx context.Context) DomainDKIMSelectorOutput
}

func (*DomainDKIMSelector) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainDKIMSelector)(nil)).Elem()
}

func (i *DomainDKIMSelector) ToDomainDKIMSelectorOutput() DomainDKIMSelectorOutput {
	return i.ToDomainDKIMSelectorOutputWithContext(context.Background())
}

func (i *DomainDKIMSelector) ToDomainDKIMSelectorOutputWithContext(ctx context.Context) DomainDKIMSelectorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainDKIMSelectorOutput)
}

// DomainDKIMSelectorArrayInput is an input type that accepts DomainDKIMSelectorArray and DomainDKIMSelectorArrayOutput values.
// You can construct a concrete instance of `DomainDKIMSelectorArrayInput` via:
//
//	DomainDKIMSelectorArray{ DomainDKIMSelectorArgs{...} }
type DomainDKIMSelectorArrayInput interface {
	pulumi.Input

	ToDomainDKIMSelectorArrayOutput() DomainDKIMSelectorArrayOutput
	ToDomainDKIMSelectorArrayOutputWithContext(context.Context) DomainDKIMSelectorArrayOutput
}

type DomainDKIMSelectorArray []DomainDKIMSelectorInput

func (DomainDKIMSelectorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainDKIMSelector)(nil)).Elem()
}

func (i DomainDKIMSelectorArray) ToDomainDKIMSelectorArrayOutput() DomainDKIMSelectorArrayOutput {
	return i.ToDomainDKIMSelectorArrayOutputWithContext(context.Background())
}

func (i DomainDKIMSelectorArray) ToDomainDKIMSelectorArrayOutputWithContext(ctx context.Context) DomainDKIMSelectorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainDKIMSelectorArrayOutput)
}

// DomainDKIMSelectorMapInput is an input type that accepts DomainDKIMSelectorMap and DomainDKIMSelectorMapOutput values.
// You can construct a concrete instance of `DomainDKIMSelectorMapInput` via:
//
//	DomainDKIMSelectorMap{ "key": DomainDKIMSelectorArgs{...} }
type DomainDKIMSelectorMapInput interface {
	pulumi.Input

	ToDomainDKIMSelectorMapOutput() DomainDKIMSelectorMapOutput
	ToDomainDKIMSelectorMapOutputWithContext(context.Context) DomainDKIMSelectorMapOutput
}

type DomainDKIMSelectorMap map[string]DomainDKIMSelectorInput

func (DomainDKIMSelectorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainDKIMSelector)(nil)).Elem()
}

func (i DomainDKIMSelectorMap) ToDomainDKIMSelectorMapOutput() DomainDKIMSelectorMapOutput {
	return i.ToDomainDKIMSelectorMapOutputWithContext(context.Background())
}

func (i DomainDKIMSelectorMap) ToDomainDKIMSelectorMapOutputWithContext(ctx context.Context) DomainDKIMSelectorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainDKIMSelectorMapOutput)
}

type DomainDKIMSelectorOutput struct{ *pulumi.OutputState }

func (DomainDKIMSelectorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainDKIMSelector)(nil)).Elem()
}

func (o DomainDKIMSelectorOutput) ToDomainDKIMSelectorOutput() DomainDKIMSelectorOutput {
	return o
}

func (o DomainDKIMSelectorOutput) ToDomainDKIMSelectorOutputWithContext(ctx context.Context) DomainDKIMSelectorOutput {
	return o
}

// Key algorithm used when creating the selector, e.g. ed25519 or rsa-2048. Changing it replaces the selector.
func (o DomainDKIMSelectorOutput) Algorithm() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringPtrOutput { return v.Algorithm }).(pulumi.StringPtrOutput)
}

// Enable relaxed body canonicalization.
func (o DomainDKIMSelectorOutput) BodyRelaxed() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.BoolPtrOutput { return v.BodyRelaxed }).(pulumi.BoolPtrOutput)
}

// Mox domain that owns the selector.
func (o DomainDKIMSelectorOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Hash mox uses after applying defaults.
func (o DomainDKIMSelectorOutput) EffectiveHash() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringOutput { return v.EffectiveHash }).(pulumi.StringOutput)
}

// DKIM hash algorithm, normally sha256.
func (o DomainDKIMSelectorOutput) Hash() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringPtrOutput { return v.Hash }).(pulumi.StringPtrOutput)
}

// Enable relaxed header canonicalization.
func (o DomainDKIMSelectorOutput) HeaderRelaxed() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.BoolPtrOutput { return v.HeaderRelaxed }).(pulumi.BoolPtrOutput)
}

// Headers to sign. Empty uses mox's default set.
func (o DomainDKIMSelectorOutput) Headers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringArrayOutput { return v.Headers }).(pulumi.StringArrayOutput)
}

// DKIM signature lifetime for a newly generated selector.
func (o DomainDKIMSelectorOutput) LifetimeSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.IntPtrOutput { return v.LifetimeSeconds }).(pulumi.IntPtrOutput)
}

// Server-side key file generated/stored by mox.
func (o DomainDKIMSelectorOutput) PrivateKeyFile() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringOutput { return v.PrivateKeyFile }).(pulumi.StringOutput)
}

// Prevent duplicate headers from being added. Defaults to true.
func (o DomainDKIMSelectorOutput) SealHeaders() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.BoolPtrOutput { return v.SealHeaders }).(pulumi.BoolPtrOutput)
}

// DKIM selector label.
func (o DomainDKIMSelectorOutput) Selector() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.StringOutput { return v.Selector }).(pulumi.StringOutput)
}

// Enable this selector for signing outgoing mail.
func (o DomainDKIMSelectorOutput) Sign() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainDKIMSelector) pulumi.BoolPtrOutput { return v.Sign }).(pulumi.BoolPtrOutput)
}

type DomainDKIMSelectorArrayOutput struct{ *pulumi.OutputState }

func (DomainDKIMSelectorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainDKIMSelector)(nil)).Elem()
}

func (o DomainDKIMSelectorArrayOutput) ToDomainDKIMSelectorArrayOutput() DomainDKIMSelectorArrayOutput {
	return o
}

func (o DomainDKIMSelectorArrayOutput) ToDomainDKIMSelectorArrayOutputWithContext(ctx context.Context) DomainDKIMSelectorArrayOutput {
	return o
}

func (o DomainDKIMSelectorArrayOutput) Index(i pulumi.IntInput) DomainDKIMSelectorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DomainDKIMSelector {
		return vs[0].([]*DomainDKIMSelector)[vs[1].(int)]
	}).(DomainDKIMSelectorOutput)
}

type DomainDKIMSelectorMapOutput struct{ *pulumi.OutputState }

func (DomainDKIMSelectorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainDKIMSelector)(nil)).Elem()
}

func (o DomainDKIMSelectorMapOutput) ToDomainDKIMSelectorMapOutput() DomainDKIMSelectorMapOutput {
	return o
}

func (o DomainDKIMSelectorMapOutput) ToDomainDKIMSelectorMapOutputWithContext(ctx context.Context) DomainDKIMSelectorMapOutput {
	return o
}

func (o DomainDKIMSelectorMapOutput) MapIndex(k pulumi.StringInput) DomainDKIMSelectorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DomainDKIMSelector {
		return vs[0].(map[string]*DomainDKIMSelector)[vs[1].(string)]
	}).(DomainDKIMSelectorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainDKIMSelectorInput)(nil)).Elem(), &DomainDKIMSelector{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainDKIMSelectorArrayInput)(nil)).Elem(), DomainDKIMSelectorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainDKIMSelectorMapInput)(nil)).Elem(), DomainDKIMSelectorMap{})
	pulumi.RegisterOutputType(DomainDKIMSelectorOutput{})
	pulumi.RegisterOutputType(DomainDKIMSelectorArrayOutput{})
	pulumi.RegisterOutputType(DomainDKIMSelectorMapOutput{})
}
