// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A mail domain managed by mox. Exposes the mox-generated DNS records as an output.
type Domain struct {
	pulumi.CustomResourceState

	// Initial account name to create/associate. Defaults to the domain name.
	Account pulumi.StringPtrOutput `pulumi:"account"`
	// Hostname clients should use for IMAP/SMTP autoconfiguration.
	ClientSettingsDomain pulumi.StringPtrOutput `pulumi:"clientSettingsDomain"`
	// Free-form description of the domain.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Whether the domain is administratively disabled in mox.
	Disabled pulumi.BoolPtrOutput `pulumi:"disabled"`
	// DKIM public-key TXT records (one per selector), parsed from DnsRecords for programmatic DNS provisioning. Record name is "<selector>._domainkey.<domain>".
	DkimRecords DkimDNSRecordArrayOutput `pulumi:"dkimRecords"`
	// DMARC aggregate-report destination. Removing a previously-set block clears it.
	Dmarc DomainReportAddressPtrOutput `pulumi:"dmarc"`
	// Zone-file lines mox expects to exist for this domain (MX, SPF, DKIM, DMARC, ...).
	DnsRecords pulumi.StringArrayOutput `pulumi:"dnsRecords"`
	// Domain name to add, e.g. "example.com".
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Local part of the initial address (before "@"). Defaults to "postmaster".
	Localpart pulumi.StringPtrOutput `pulumi:"localpart"`
	// Localpart catch-all separators and case-sensitivity.
	LocalpartConfig DomainLocalpartConfigPtrOutput `pulumi:"localpartConfig"`
	// MTA-STS policy configuration. Removing a previously-set block clears the policy.
	MtaSts DomainMtaStsPtrOutput `pulumi:"mtaSts"`
	// Domain-level outgoing routing rules.
	Routes AccountRouteArrayOutput `pulumi:"routes"`
	// TLSRPT report destination. Removing a previously-set block clears it.
	TlsRpt DomainReportAddressPtrOutput `pulumi:"tlsRpt"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"account",
		"domain",
		"localpart",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Domain
	err := ctx.RegisterResource("mox:index:Domain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	err := ctx.ReadResource("mox:index:Domain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
}

type DomainState struct {
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	// Initial account name to create/associate. Defaults to the domain name.
	Account *string `pulumi:"account"`
	// Hostname clients should use for IMAP/SMTP autoconfiguration.
	ClientSettingsDomain *string `pulumi:"clientSettingsDomain"`
	// Free-form description of the domain.
	Description *string `pulumi:"description"`
	// Whether the domain is administratively disabled in mox.
	Disabled *bool `pulumi:"disabled"`
	// DMARC aggregate-report destination. Removing a previously-set block clears it.
	Dmarc *DomainReportAddress `pulumi:"dmarc"`
	// Domain name to add, e.g. "example.com".
	Domain string `pulumi:"domain"`
	// Local part of the initial address (before "@"). Defaults to "postmaster".
	Localpart *string `pulumi:"localpart"`
	// Localpart catch-all separators and case-sensitivity.
	LocalpartConfig *DomainLocalpartConfig `pulumi:"localpartConfig"`
	// MTA-STS policy configuration. Removing a previously-set block clears the policy.
	MtaSts *DomainMtaSts `pulumi:"mtaSts"`
	// Domain-level outgoing routing rules.
	Routes []AccountRoute `pulumi:"routes"`
	// TLSRPT report destination. Removing a previously-set block clears it.
	TlsRpt *DomainReportAddress `pulumi:"tlsRpt"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	// Initial account name to create/associate. Defaults to the domain name.
	Account pulumi.StringPtrInput
	// Hostname clients should use for IMAP/SMTP autoconfiguration.
	ClientSettingsDomain pulumi.StringPtrInput
	// Free-form description of the domain.
	Description pulumi.StringPtrInput
	// Whether the domain is administratively disabled in mox.
	Disabled pulumi.BoolPtrInput
	// DMARC aggregate-report destination. Removing a previously-set block clears it.
	Dmarc DomainReportAddressPtrInput
	// Domain name to add, e.g. "example.com".
	Domain pulumi.StringInput
	// Local part of the initial address (before "@"). Defaults to "postmaster".
	Localpart pulumi.StringPtrInput
	// Localpart catch-all separators and case-sensitivity.
	LocalpartConfig DomainLocalpartConfigPtrInput
	// MTA-STS policy configuration. Removing a previously-set block clears the policy.
	MtaSts DomainMtaStsPtrInput
	// Domain-level outgoing routing rules.
	Routes AccountRouteArrayInput
	// TLSRPT report destination. Removing a previously-set block clears it.
	TlsRpt DomainReportAddressPtrInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

// DomainArrayInput is an input type that accepts DomainArray and DomainArrayOutput values.
// You can construct a concrete instance of `DomainArrayInput` via:
//
//	DomainArray{ DomainArgs{...} }
type DomainArrayInput interface {
	pulumi.Input

	ToDomainArrayOutput() DomainArrayOutput
	ToDomainArrayOutputWithContext(context.Context) DomainArrayOutput
}

type DomainArray []DomainInput

func (DomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (i DomainArray) ToDomainArrayOutput() DomainArrayOutput {
	return i.ToDomainArrayOutputWithContext(context.Background())
}

func (i DomainArray) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainArrayOutput)
}

// DomainMapInput is an input type that accepts DomainMap and DomainMapOutput values.
// You can construct a concrete instance of `DomainMapInput` via:
//
//	DomainMap{ "key": DomainArgs{...} }
type DomainMapInput interface {
	pulumi.Input

	ToDomainMapOutput() DomainMapOutput
	ToDomainMapOutputWithContext(context.Context) DomainMapOutput
}

type DomainMap map[string]DomainInput

func (DomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (i DomainMap) ToDomainMapOutput() DomainMapOutput {
	return i.ToDomainMapOutputWithContext(context.Background())
}

func (i DomainMap) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMapOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

// Initial account name to create/associate. Defaults to the domain name.
func (o DomainOutput) Account() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Account }).(pulumi.StringPtrOutput)
}

// Hostname clients should use for IMAP/SMTP autoconfiguration.
func (o DomainOutput) ClientSettingsDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.ClientSettingsDomain }).(pulumi.StringPtrOutput)
}

// Free-form description of the domain.
func (o DomainOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Whether the domain is administratively disabled in mox.
func (o DomainOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

// DKIM public-key TXT records (one per selector), parsed from DnsRecords for programmatic DNS provisioning. Record name is "<selector>._domainkey.<domain>".
func (o DomainOutput) DkimRecords() DkimDNSRecordArrayOutput {
	return o.ApplyT(func(v *Domain) DkimDNSRecordArrayOutput { return v.DkimRecords }).(DkimDNSRecordArrayOutput)
}

// DMARC aggregate-report destination. Removing a previously-set block clears it.
func (o DomainOutput) Dmarc() DomainReportAddressPtrOutput {
	return o.ApplyT(func(v *Domain) DomainReportAddressPtrOutput { return v.Dmarc }).(DomainReportAddressPtrOutput)
}

// Zone-file lines mox expects to exist for this domain (MX, SPF, DKIM, DMARC, ...).
func (o DomainOutput) DnsRecords() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringArrayOutput { return v.DnsRecords }).(pulumi.StringArrayOutput)
}

// Domain name to add, e.g. "example.com".
func (o DomainOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Local part of the initial address (before "@"). Defaults to "postmaster".
func (o DomainOutput) Localpart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Localpart }).(pulumi.StringPtrOutput)
}

// Localpart catch-all separators and case-sensitivity.
func (o DomainOutput) LocalpartConfig() DomainLocalpartConfigPtrOutput {
	return o.ApplyT(func(v *Domain) DomainLocalpartConfigPtrOutput { return v.LocalpartConfig }).(DomainLocalpartConfigPtrOutput)
}

// MTA-STS policy configuration. Removing a previously-set block clears the policy.
func (o DomainOutput) MtaSts() DomainMtaStsPtrOutput {
	return o.ApplyT(func(v *Domain) DomainMtaStsPtrOutput { return v.MtaSts }).(DomainMtaStsPtrOutput)
}

// Domain-level outgoing routing rules.
func (o DomainOutput) Routes() AccountRouteArrayOutput {
	return o.ApplyT(func(v *Domain) AccountRouteArrayOutput { return v.Routes }).(AccountRouteArrayOutput)
}

// TLSRPT report destination. Removing a previously-set block clears it.
func (o DomainOutput) TlsRpt() DomainReportAddressPtrOutput {
	return o.ApplyT(func(v *Domain) DomainReportAddressPtrOutput { return v.TlsRpt }).(DomainReportAddressPtrOutput)
}

type DomainArrayOutput struct{ *pulumi.OutputState }

func (DomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (o DomainArrayOutput) ToDomainArrayOutput() DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) Index(i pulumi.IntInput) DomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].([]*Domain)[vs[1].(int)]
	}).(DomainOutput)
}

type DomainMapOutput struct{ *pulumi.OutputState }

func (DomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (o DomainMapOutput) ToDomainMapOutput() DomainMapOutput {
	return o
}

func (o DomainMapOutput) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return o
}

func (o DomainMapOutput) MapIndex(k pulumi.StringInput) DomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].(map[string]*Domain)[vs[1].(string)]
	}).(DomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainArrayInput)(nil)).Elem(), DomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMapInput)(nil)).Elem(), DomainMap{})
	pulumi.RegisterOutputType(DomainOutput{})
	pulumi.RegisterOutputType(DomainArrayOutput{})
	pulumi.RegisterOutputType(DomainMapOutput{})
}
