// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the effective dynamic mox configuration. The result is marked secret because it can contain private key material.
func GetConfig(ctx *pulumi.Context, args *GetConfigArgs, opts ...pulumi.InvokeOption) (*GetConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConfigResult
	err := ctx.Invoke("mox:index:getConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetConfigArgs struct {
}

type GetConfigResult struct {
	Result moxapi.Dynamic `pulumi:"result"`
}

func GetConfigOutput(ctx *pulumi.Context, args GetConfigOutputArgs, opts ...pulumi.InvokeOption) GetConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConfigResultOutput, error) {
			args := v.(GetConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getConfig", args, GetConfigResultOutput{}, options).(GetConfigResultOutput), nil
		}).(GetConfigResultOutput)
}

type GetConfigOutputArgs struct {
}

func (GetConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigArgs)(nil)).Elem()
}

type GetConfigResultOutput struct{ *pulumi.OutputState }

func (GetConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigResult)(nil)).Elem()
}

func (o GetConfigResultOutput) ToGetConfigResultOutput() GetConfigResultOutput {
	return o
}

func (o GetConfigResultOutput) ToGetConfigResultOutputWithContext(ctx context.Context) GetConfigResultOutput {
	return o
}

func (o GetConfigResultOutput) Result() moxapi.DynamicOutput {
	return o.ApplyT(func(v GetConfigResult) moxapi.Dynamic { return v.Result }).(moxapi.DynamicOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConfigResultOutput{})
}
