// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reports whether mox's static update-check setting is enabled. The admin API exposes this as read-only.
func GetCheckUpdatesEnabled(ctx *pulumi.Context, args *GetCheckUpdatesEnabledArgs, opts ...pulumi.InvokeOption) (*GetCheckUpdatesEnabledResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCheckUpdatesEnabledResult
	err := ctx.Invoke("mox:index:getCheckUpdatesEnabled", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCheckUpdatesEnabledArgs struct {
}

type GetCheckUpdatesEnabledResult struct {
	// Whether mox checks for upstream updates.
	Enabled bool `pulumi:"enabled"`
}

func GetCheckUpdatesEnabledOutput(ctx *pulumi.Context, args GetCheckUpdatesEnabledOutputArgs, opts ...pulumi.InvokeOption) GetCheckUpdatesEnabledResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCheckUpdatesEnabledResultOutput, error) {
			args := v.(GetCheckUpdatesEnabledArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getCheckUpdatesEnabled", args, GetCheckUpdatesEnabledResultOutput{}, options).(GetCheckUpdatesEnabledResultOutput), nil
		}).(GetCheckUpdatesEnabledResultOutput)
}

type GetCheckUpdatesEnabledOutputArgs struct {
}

func (GetCheckUpdatesEnabledOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckUpdatesEnabledArgs)(nil)).Elem()
}

type GetCheckUpdatesEnabledResultOutput struct{ *pulumi.OutputState }

func (GetCheckUpdatesEnabledResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckUpdatesEnabledResult)(nil)).Elem()
}

func (o GetCheckUpdatesEnabledResultOutput) ToGetCheckUpdatesEnabledResultOutput() GetCheckUpdatesEnabledResultOutput {
	return o
}

func (o GetCheckUpdatesEnabledResultOutput) ToGetCheckUpdatesEnabledResultOutputWithContext(ctx context.Context) GetCheckUpdatesEnabledResultOutput {
	return o
}

// Whether mox checks for upstream updates.
func (o GetCheckUpdatesEnabledResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetCheckUpdatesEnabledResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCheckUpdatesEnabledResultOutput{})
}
