// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the paths and raw contents of mox's static and dynamic config files. The contents are marked secret.
func GetConfigFiles(ctx *pulumi.Context, args *GetConfigFilesArgs, opts ...pulumi.InvokeOption) (*GetConfigFilesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetConfigFilesResult
	err := ctx.Invoke("mox:index:getConfigFiles", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetConfigFilesArgs struct {
}

type GetConfigFilesResult struct {
	// Raw contents of the dynamic config file.
	Dynamic string `pulumi:"dynamic"`
	// Filesystem path of the dynamic config file (domains.conf).
	DynamicPath string `pulumi:"dynamicPath"`
	// Raw contents of the static config file.
	Static string `pulumi:"static"`
	// Filesystem path of the static config file (mox.conf).
	StaticPath string `pulumi:"staticPath"`
}

func GetConfigFilesOutput(ctx *pulumi.Context, args GetConfigFilesOutputArgs, opts ...pulumi.InvokeOption) GetConfigFilesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetConfigFilesResultOutput, error) {
			args := v.(GetConfigFilesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getConfigFiles", args, GetConfigFilesResultOutput{}, options).(GetConfigFilesResultOutput), nil
		}).(GetConfigFilesResultOutput)
}

type GetConfigFilesOutputArgs struct {
}

func (GetConfigFilesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigFilesArgs)(nil)).Elem()
}

type GetConfigFilesResultOutput struct{ *pulumi.OutputState }

func (GetConfigFilesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetConfigFilesResult)(nil)).Elem()
}

func (o GetConfigFilesResultOutput) ToGetConfigFilesResultOutput() GetConfigFilesResultOutput {
	return o
}

func (o GetConfigFilesResultOutput) ToGetConfigFilesResultOutputWithContext(ctx context.Context) GetConfigFilesResultOutput {
	return o
}

// Raw contents of the dynamic config file.
func (o GetConfigFilesResultOutput) Dynamic() pulumi.StringOutput {
	return o.ApplyT(func(v GetConfigFilesResult) string { return v.Dynamic }).(pulumi.StringOutput)
}

// Filesystem path of the dynamic config file (domains.conf).
func (o GetConfigFilesResultOutput) DynamicPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetConfigFilesResult) string { return v.DynamicPath }).(pulumi.StringOutput)
}

// Raw contents of the static config file.
func (o GetConfigFilesResultOutput) Static() pulumi.StringOutput {
	return o.ApplyT(func(v GetConfigFilesResult) string { return v.Static }).(pulumi.StringOutput)
}

// Filesystem path of the static config file (mox.conf).
func (o GetConfigFilesResultOutput) StaticPath() pulumi.StringOutput {
	return o.ApplyT(func(v GetConfigFilesResult) string { return v.StaticPath }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetConfigFilesResultOutput{})
}
