// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the IMAP/SMTP client autoconfiguration settings (hostnames, ports, TLS) for a domain.
func GetClientConfigsDomain(ctx *pulumi.Context, args *GetClientConfigsDomainArgs, opts ...pulumi.InvokeOption) (*GetClientConfigsDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetClientConfigsDomainResult
	err := ctx.Invoke("mox:index:getClientConfigsDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetClientConfigsDomainArgs struct {
	// Domain name whose client configuration to return, e.g. "example.com".
	Domain string `pulumi:"domain"`
}

type GetClientConfigsDomainResult struct {
	Result moxapi.ClientConfigs `pulumi:"result"`
}

func GetClientConfigsDomainOutput(ctx *pulumi.Context, args GetClientConfigsDomainOutputArgs, opts ...pulumi.InvokeOption) GetClientConfigsDomainResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetClientConfigsDomainResultOutput, error) {
			args := v.(GetClientConfigsDomainArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getClientConfigsDomain", args, GetClientConfigsDomainResultOutput{}, options).(GetClientConfigsDomainResultOutput), nil
		}).(GetClientConfigsDomainResultOutput)
}

type GetClientConfigsDomainOutputArgs struct {
	// Domain name whose client configuration to return, e.g. "example.com".
	Domain pulumi.StringInput `pulumi:"domain"`
}

func (GetClientConfigsDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientConfigsDomainArgs)(nil)).Elem()
}

type GetClientConfigsDomainResultOutput struct{ *pulumi.OutputState }

func (GetClientConfigsDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientConfigsDomainResult)(nil)).Elem()
}

func (o GetClientConfigsDomainResultOutput) ToGetClientConfigsDomainResultOutput() GetClientConfigsDomainResultOutput {
	return o
}

func (o GetClientConfigsDomainResultOutput) ToGetClientConfigsDomainResultOutputWithContext(ctx context.Context) GetClientConfigsDomainResultOutput {
	return o
}

func (o GetClientConfigsDomainResultOutput) Result() moxapi.ClientConfigsOutput {
	return o.ApplyT(func(v GetClientConfigsDomainResult) moxapi.ClientConfigs { return v.Result }).(moxapi.ClientConfigsOutput)
}

func init() {
	pulumi.RegisterOutputType(GetClientConfigsDomainResultOutput{})
}
