// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Runs mox's DNS and configuration health checks for a domain (MX, SPF, DKIM, DMARC, TLSRPT, MTA-STS, DANE, ...).
func GetCheckDomain(ctx *pulumi.Context, args *GetCheckDomainArgs, opts ...pulumi.InvokeOption) (*GetCheckDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetCheckDomainResult
	err := ctx.Invoke("mox:index:getCheckDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetCheckDomainArgs struct {
	// Domain name to check, e.g. "example.com".
	Domain string `pulumi:"domain"`
}

type GetCheckDomainResult struct {
	Result moxapi.CheckResult `pulumi:"result"`
}

func GetCheckDomainOutput(ctx *pulumi.Context, args GetCheckDomainOutputArgs, opts ...pulumi.InvokeOption) GetCheckDomainResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCheckDomainResultOutput, error) {
			args := v.(GetCheckDomainArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getCheckDomain", args, GetCheckDomainResultOutput{}, options).(GetCheckDomainResultOutput), nil
		}).(GetCheckDomainResultOutput)
}

type GetCheckDomainOutputArgs struct {
	// Domain name to check, e.g. "example.com".
	Domain pulumi.StringInput `pulumi:"domain"`
}

func (GetCheckDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckDomainArgs)(nil)).Elem()
}

type GetCheckDomainResultOutput struct{ *pulumi.OutputState }

func (GetCheckDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCheckDomainResult)(nil)).Elem()
}

func (o GetCheckDomainResultOutput) ToGetCheckDomainResultOutput() GetCheckDomainResultOutput {
	return o
}

func (o GetCheckDomainResultOutput) ToGetCheckDomainResultOutputWithContext(ctx context.Context) GetCheckDomainResultOutput {
	return o
}

func (o GetCheckDomainResultOutput) Result() moxapi.CheckResultOutput {
	return o.ApplyT(func(v GetCheckDomainResult) moxapi.CheckResult { return v.Result }).(moxapi.CheckResultOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCheckDomainResultOutput{})
}
