// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the full effective mox configuration for a domain, including localpart, DKIM, DMARC, TLSRPT, MTA-STS and routing settings.
func GetDomainConfig(ctx *pulumi.Context, args *GetDomainConfigArgs, opts ...pulumi.InvokeOption) (*GetDomainConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDomainConfigResult
	err := ctx.Invoke("mox:index:getDomainConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDomainConfigArgs struct {
	// Domain name whose configuration to return, e.g. "example.com".
	Domain string `pulumi:"domain"`
}

type GetDomainConfigResult struct {
	Result moxapi.ConfigDomain `pulumi:"result"`
}

func GetDomainConfigOutput(ctx *pulumi.Context, args GetDomainConfigOutputArgs, opts ...pulumi.InvokeOption) GetDomainConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDomainConfigResultOutput, error) {
			args := v.(GetDomainConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getDomainConfig", args, GetDomainConfigResultOutput{}, options).(GetDomainConfigResultOutput), nil
		}).(GetDomainConfigResultOutput)
}

type GetDomainConfigOutputArgs struct {
	// Domain name whose configuration to return, e.g. "example.com".
	Domain pulumi.StringInput `pulumi:"domain"`
}

func (GetDomainConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainConfigArgs)(nil)).Elem()
}

type GetDomainConfigResultOutput struct{ *pulumi.OutputState }

func (GetDomainConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainConfigResult)(nil)).Elem()
}

func (o GetDomainConfigResultOutput) ToGetDomainConfigResultOutput() GetDomainConfigResultOutput {
	return o
}

func (o GetDomainConfigResultOutput) ToGetDomainConfigResultOutputWithContext(ctx context.Context) GetDomainConfigResultOutput {
	return o
}

func (o GetDomainConfigResultOutput) Result() moxapi.ConfigDomainOutput {
	return o.ApplyT(func(v GetDomainConfigResult) moxapi.ConfigDomain { return v.Result }).(moxapi.ConfigDomainOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainConfigResultOutput{})
}
