// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the localpart-to-account and localpart-to-alias mappings for a domain.
func GetDomainLocalparts(ctx *pulumi.Context, args *GetDomainLocalpartsArgs, opts ...pulumi.InvokeOption) (*GetDomainLocalpartsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDomainLocalpartsResult
	err := ctx.Invoke("mox:index:getDomainLocalparts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDomainLocalpartsArgs struct {
	// Domain name whose localparts to list, e.g. "example.com".
	Domain string `pulumi:"domain"`
}

type GetDomainLocalpartsResult struct {
	// Map of localpart to the account that owns it.
	LocalpartAccounts map[string]string `pulumi:"localpartAccounts"`
	// Map of localpart to its alias definition.
	LocalpartAliases map[string]moxapi.Alias `pulumi:"localpartAliases"`
}

func GetDomainLocalpartsOutput(ctx *pulumi.Context, args GetDomainLocalpartsOutputArgs, opts ...pulumi.InvokeOption) GetDomainLocalpartsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDomainLocalpartsResultOutput, error) {
			args := v.(GetDomainLocalpartsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getDomainLocalparts", args, GetDomainLocalpartsResultOutput{}, options).(GetDomainLocalpartsResultOutput), nil
		}).(GetDomainLocalpartsResultOutput)
}

type GetDomainLocalpartsOutputArgs struct {
	// Domain name whose localparts to list, e.g. "example.com".
	Domain pulumi.StringInput `pulumi:"domain"`
}

func (GetDomainLocalpartsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainLocalpartsArgs)(nil)).Elem()
}

type GetDomainLocalpartsResultOutput struct{ *pulumi.OutputState }

func (GetDomainLocalpartsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainLocalpartsResult)(nil)).Elem()
}

func (o GetDomainLocalpartsResultOutput) ToGetDomainLocalpartsResultOutput() GetDomainLocalpartsResultOutput {
	return o
}

func (o GetDomainLocalpartsResultOutput) ToGetDomainLocalpartsResultOutputWithContext(ctx context.Context) GetDomainLocalpartsResultOutput {
	return o
}

// Map of localpart to the account that owns it.
func (o GetDomainLocalpartsResultOutput) LocalpartAccounts() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDomainLocalpartsResult) map[string]string { return v.LocalpartAccounts }).(pulumi.StringMapOutput)
}

// Map of localpart to its alias definition.
func (o GetDomainLocalpartsResultOutput) LocalpartAliases() moxapi.AliasMapOutput {
	return o.ApplyT(func(v GetDomainLocalpartsResult) map[string]moxapi.Alias { return v.LocalpartAliases }).(moxapi.AliasMapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainLocalpartsResultOutput{})
}
