// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns recent login attempts for an account, most recent first.
func GetLoginAttempts(ctx *pulumi.Context, args *GetLoginAttemptsArgs, opts ...pulumi.InvokeOption) (*GetLoginAttemptsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLoginAttemptsResult
	err := ctx.Invoke("mox:index:getLoginAttempts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetLoginAttemptsArgs struct {
	// Account name whose login attempts to return.
	Account string `pulumi:"account"`
	// Maximum number of attempts to return, most recent first. Set to 0 (the default) to return all attempts.
	Limit *int `pulumi:"limit"`
}

type GetLoginAttemptsResult struct {
	Result []moxapi.LoginAttempt `pulumi:"result"`
}

func GetLoginAttemptsOutput(ctx *pulumi.Context, args GetLoginAttemptsOutputArgs, opts ...pulumi.InvokeOption) GetLoginAttemptsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLoginAttemptsResultOutput, error) {
			args := v.(GetLoginAttemptsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getLoginAttempts", args, GetLoginAttemptsResultOutput{}, options).(GetLoginAttemptsResultOutput), nil
		}).(GetLoginAttemptsResultOutput)
}

type GetLoginAttemptsOutputArgs struct {
	// Account name whose login attempts to return.
	Account pulumi.StringInput `pulumi:"account"`
	// Maximum number of attempts to return, most recent first. Set to 0 (the default) to return all attempts.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
}

func (GetLoginAttemptsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoginAttemptsArgs)(nil)).Elem()
}

type GetLoginAttemptsResultOutput struct{ *pulumi.OutputState }

func (GetLoginAttemptsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoginAttemptsResult)(nil)).Elem()
}

func (o GetLoginAttemptsResultOutput) ToGetLoginAttemptsResultOutput() GetLoginAttemptsResultOutput {
	return o
}

func (o GetLoginAttemptsResultOutput) ToGetLoginAttemptsResultOutputWithContext(ctx context.Context) GetLoginAttemptsResultOutput {
	return o
}

func (o GetLoginAttemptsResultOutput) Result() moxapi.LoginAttemptArrayOutput {
	return o.ApplyT(func(v GetLoginAttemptsResult) []moxapi.LoginAttempt { return v.Result }).(moxapi.LoginAttemptArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLoginAttemptsResultOutput{})
}
