// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/hilli/pulumi-mox/sdk/go/mox/moxapi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Lists TLS client-authentication public keys, optionally restricted to a single account.
func GetTLSPublicKeys(ctx *pulumi.Context, args *GetTLSPublicKeysArgs, opts ...pulumi.InvokeOption) (*GetTLSPublicKeysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTLSPublicKeysResult
	err := ctx.Invoke("mox:index:getTLSPublicKeys", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetTLSPublicKeysArgs struct {
	// Restrict the result to this account. Omit to list keys for all accounts.
	Account *string `pulumi:"account"`
}

type GetTLSPublicKeysResult struct {
	Result []moxapi.TLSPublicKey `pulumi:"result"`
}

func GetTLSPublicKeysOutput(ctx *pulumi.Context, args GetTLSPublicKeysOutputArgs, opts ...pulumi.InvokeOption) GetTLSPublicKeysResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTLSPublicKeysResultOutput, error) {
			args := v.(GetTLSPublicKeysArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getTLSPublicKeys", args, GetTLSPublicKeysResultOutput{}, options).(GetTLSPublicKeysResultOutput), nil
		}).(GetTLSPublicKeysResultOutput)
}

type GetTLSPublicKeysOutputArgs struct {
	// Restrict the result to this account. Omit to list keys for all accounts.
	Account pulumi.StringPtrInput `pulumi:"account"`
}

func (GetTLSPublicKeysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTLSPublicKeysArgs)(nil)).Elem()
}

type GetTLSPublicKeysResultOutput struct{ *pulumi.OutputState }

func (GetTLSPublicKeysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTLSPublicKeysResult)(nil)).Elem()
}

func (o GetTLSPublicKeysResultOutput) ToGetTLSPublicKeysResultOutput() GetTLSPublicKeysResultOutput {
	return o
}

func (o GetTLSPublicKeysResultOutput) ToGetTLSPublicKeysResultOutputWithContext(ctx context.Context) GetTLSPublicKeysResultOutput {
	return o
}

func (o GetTLSPublicKeysResultOutput) Result() moxapi.TLSPublicKeyArrayOutput {
	return o.ApplyT(func(v GetTLSPublicKeysResult) []moxapi.TLSPublicKey { return v.Result }).(moxapi.TLSPublicKeyArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTLSPublicKeysResultOutput{})
}
