// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the mox server version and the OS/architecture it was built for.
func GetVersion(ctx *pulumi.Context, args *GetVersionArgs, opts ...pulumi.InvokeOption) (*GetVersionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVersionResult
	err := ctx.Invoke("mox:index:getVersion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetVersionArgs struct {
}

type GetVersionResult struct {
	// Architecture the server was built for (GOARCH).
	Goarch string `pulumi:"goarch"`
	// Operating system the server was built for (GOOS).
	Goos string `pulumi:"goos"`
	// Mox server version string.
	Version string `pulumi:"version"`
}

func GetVersionOutput(ctx *pulumi.Context, args GetVersionOutputArgs, opts ...pulumi.InvokeOption) GetVersionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVersionResultOutput, error) {
			args := v.(GetVersionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mox:index:getVersion", args, GetVersionResultOutput{}, options).(GetVersionResultOutput), nil
		}).(GetVersionResultOutput)
}

type GetVersionOutputArgs struct {
}

func (GetVersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVersionArgs)(nil)).Elem()
}

type GetVersionResultOutput struct{ *pulumi.OutputState }

func (GetVersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVersionResult)(nil)).Elem()
}

func (o GetVersionResultOutput) ToGetVersionResultOutput() GetVersionResultOutput {
	return o
}

func (o GetVersionResultOutput) ToGetVersionResultOutputWithContext(ctx context.Context) GetVersionResultOutput {
	return o
}

// Architecture the server was built for (GOARCH).
func (o GetVersionResultOutput) Goarch() pulumi.StringOutput {
	return o.ApplyT(func(v GetVersionResult) string { return v.Goarch }).(pulumi.StringOutput)
}

// Operating system the server was built for (GOOS).
func (o GetVersionResultOutput) Goos() pulumi.StringOutput {
	return o.ApplyT(func(v GetVersionResult) string { return v.Goos }).(pulumi.StringOutput)
}

// Mox server version string.
func (o GetVersionResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetVersionResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVersionResultOutput{})
}
