// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Server-level outgoing routing rules, evaluated after account and domain routes.
type GlobalRoutes struct {
	pulumi.CustomResourceState

	// Global outgoing routing rules.
	Routes AccountRouteArrayOutput `pulumi:"routes"`
}

// NewGlobalRoutes registers a new resource with the given unique name, arguments, and options.
func NewGlobalRoutes(ctx *pulumi.Context,
	name string, args *GlobalRoutesArgs, opts ...pulumi.ResourceOption) (*GlobalRoutes, error) {
	if args == nil {
		args = &GlobalRoutesArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GlobalRoutes
	err := ctx.RegisterResource("mox:index:GlobalRoutes", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGlobalRoutes gets an existing GlobalRoutes resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGlobalRoutes(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GlobalRoutesState, opts ...pulumi.ResourceOption) (*GlobalRoutes, error) {
	var resource GlobalRoutes
	err := ctx.ReadResource("mox:index:GlobalRoutes", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GlobalRoutes resources.
type globalRoutesState struct {
}

type GlobalRoutesState struct {
}

func (GlobalRoutesState) ElementType() reflect.Type {
	return reflect.TypeOf((*globalRoutesState)(nil)).Elem()
}

type globalRoutesArgs struct {
	// Global outgoing routing rules.
	Routes []AccountRoute `pulumi:"routes"`
}

// The set of arguments for constructing a GlobalRoutes resource.
type GlobalRoutesArgs struct {
	// Global outgoing routing rules.
	Routes AccountRouteArrayInput
}

func (GlobalRoutesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*globalRoutesArgs)(nil)).Elem()
}

type GlobalRoutesInput interface {
	pulumi.Input

	ToGlobalRoutesOutput() GlobalRoutesOutput
	ToGlobalRoutesOutputWithContext(ctx context.Context) GlobalRoutesOutput
}

func (*GlobalRoutes) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalRoutes)(nil)).Elem()
}

func (i *GlobalRoutes) ToGlobalRoutesOutput() GlobalRoutesOutput {
	return i.ToGlobalRoutesOutputWithContext(context.Background())
}

func (i *GlobalRoutes) ToGlobalRoutesOutputWithContext(ctx context.Context) GlobalRoutesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalRoutesOutput)
}

// GlobalRoutesArrayInput is an input type that accepts GlobalRoutesArray and GlobalRoutesArrayOutput values.
// You can construct a concrete instance of `GlobalRoutesArrayInput` via:
//
//	GlobalRoutesArray{ GlobalRoutesArgs{...} }
type GlobalRoutesArrayInput interface {
	pulumi.Input

	ToGlobalRoutesArrayOutput() GlobalRoutesArrayOutput
	ToGlobalRoutesArrayOutputWithContext(context.Context) GlobalRoutesArrayOutput
}

type GlobalRoutesArray []GlobalRoutesInput

func (GlobalRoutesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalRoutes)(nil)).Elem()
}

func (i GlobalRoutesArray) ToGlobalRoutesArrayOutput() GlobalRoutesArrayOutput {
	return i.ToGlobalRoutesArrayOutputWithContext(context.Background())
}

func (i GlobalRoutesArray) ToGlobalRoutesArrayOutputWithContext(ctx context.Context) GlobalRoutesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalRoutesArrayOutput)
}

// GlobalRoutesMapInput is an input type that accepts GlobalRoutesMap and GlobalRoutesMapOutput values.
// You can construct a concrete instance of `GlobalRoutesMapInput` via:
//
//	GlobalRoutesMap{ "key": GlobalRoutesArgs{...} }
type GlobalRoutesMapInput interface {
	pulumi.Input

	ToGlobalRoutesMapOutput() GlobalRoutesMapOutput
	ToGlobalRoutesMapOutputWithContext(context.Context) GlobalRoutesMapOutput
}

type GlobalRoutesMap map[string]GlobalRoutesInput

func (GlobalRoutesMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalRoutes)(nil)).Elem()
}

func (i GlobalRoutesMap) ToGlobalRoutesMapOutput() GlobalRoutesMapOutput {
	return i.ToGlobalRoutesMapOutputWithContext(context.Background())
}

func (i GlobalRoutesMap) ToGlobalRoutesMapOutputWithContext(ctx context.Context) GlobalRoutesMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalRoutesMapOutput)
}

type GlobalRoutesOutput struct{ *pulumi.OutputState }

func (GlobalRoutesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalRoutes)(nil)).Elem()
}

func (o GlobalRoutesOutput) ToGlobalRoutesOutput() GlobalRoutesOutput {
	return o
}

func (o GlobalRoutesOutput) ToGlobalRoutesOutputWithContext(ctx context.Context) GlobalRoutesOutput {
	return o
}

// Global outgoing routing rules.
func (o GlobalRoutesOutput) Routes() AccountRouteArrayOutput {
	return o.ApplyT(func(v *GlobalRoutes) AccountRouteArrayOutput { return v.Routes }).(AccountRouteArrayOutput)
}

type GlobalRoutesArrayOutput struct{ *pulumi.OutputState }

func (GlobalRoutesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalRoutes)(nil)).Elem()
}

func (o GlobalRoutesArrayOutput) ToGlobalRoutesArrayOutput() GlobalRoutesArrayOutput {
	return o
}

func (o GlobalRoutesArrayOutput) ToGlobalRoutesArrayOutputWithContext(ctx context.Context) GlobalRoutesArrayOutput {
	return o
}

func (o GlobalRoutesArrayOutput) Index(i pulumi.IntInput) GlobalRoutesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GlobalRoutes {
		return vs[0].([]*GlobalRoutes)[vs[1].(int)]
	}).(GlobalRoutesOutput)
}

type GlobalRoutesMapOutput struct{ *pulumi.OutputState }

func (GlobalRoutesMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalRoutes)(nil)).Elem()
}

func (o GlobalRoutesMapOutput) ToGlobalRoutesMapOutput() GlobalRoutesMapOutput {
	return o
}

func (o GlobalRoutesMapOutput) ToGlobalRoutesMapOutputWithContext(ctx context.Context) GlobalRoutesMapOutput {
	return o
}

func (o GlobalRoutesMapOutput) MapIndex(k pulumi.StringInput) GlobalRoutesOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GlobalRoutes {
		return vs[0].(map[string]*GlobalRoutes)[vs[1].(string)]
	}).(GlobalRoutesOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalRoutesInput)(nil)).Elem(), &GlobalRoutes{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalRoutesArrayInput)(nil)).Elem(), GlobalRoutesArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalRoutesMapInput)(nil)).Elem(), GlobalRoutesMap{})
	pulumi.RegisterOutputType(GlobalRoutesOutput{})
	pulumi.RegisterOutputType(GlobalRoutesArrayOutput{})
	pulumi.RegisterOutputType(GlobalRoutesMapOutput{})
}
