// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A package-specific mox log level override.
type LogLevel struct {
	pulumi.CustomResourceState

	// Log level string accepted by mox, such as debug, info, warn or error.
	Level pulumi.StringOutput `pulumi:"level"`
	// Mox package/logger name to configure.
	Package pulumi.StringOutput `pulumi:"package"`
}

// NewLogLevel registers a new resource with the given unique name, arguments, and options.
func NewLogLevel(ctx *pulumi.Context,
	name string, args *LogLevelArgs, opts ...pulumi.ResourceOption) (*LogLevel, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Level == nil {
		return nil, errors.New("invalid value for required argument 'Level'")
	}
	if args.Package == nil {
		return nil, errors.New("invalid value for required argument 'Package'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"package",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LogLevel
	err := ctx.RegisterResource("mox:index:LogLevel", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLogLevel gets an existing LogLevel resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLogLevel(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LogLevelState, opts ...pulumi.ResourceOption) (*LogLevel, error) {
	var resource LogLevel
	err := ctx.ReadResource("mox:index:LogLevel", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LogLevel resources.
type logLevelState struct {
}

type LogLevelState struct {
}

func (LogLevelState) ElementType() reflect.Type {
	return reflect.TypeOf((*logLevelState)(nil)).Elem()
}

type logLevelArgs struct {
	// Log level string accepted by mox, such as debug, info, warn or error.
	Level string `pulumi:"level"`
	// Mox package/logger name to configure.
	Package string `pulumi:"package"`
}

// The set of arguments for constructing a LogLevel resource.
type LogLevelArgs struct {
	// Log level string accepted by mox, such as debug, info, warn or error.
	Level pulumi.StringInput
	// Mox package/logger name to configure.
	Package pulumi.StringInput
}

func (LogLevelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*logLevelArgs)(nil)).Elem()
}

type LogLevelInput interface {
	pulumi.Input

	ToLogLevelOutput() LogLevelOutput
	ToLogLevelOutputWithContext(ctx context.Context) LogLevelOutput
}

func (*LogLevel) ElementType() reflect.Type {
	return reflect.TypeOf((**LogLevel)(nil)).Elem()
}

func (i *LogLevel) ToLogLevelOutput() LogLevelOutput {
	return i.ToLogLevelOutputWithContext(context.Background())
}

func (i *LogLevel) ToLogLevelOutputWithContext(ctx context.Context) LogLevelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogLevelOutput)
}

// LogLevelArrayInput is an input type that accepts LogLevelArray and LogLevelArrayOutput values.
// You can construct a concrete instance of `LogLevelArrayInput` via:
//
//	LogLevelArray{ LogLevelArgs{...} }
type LogLevelArrayInput interface {
	pulumi.Input

	ToLogLevelArrayOutput() LogLevelArrayOutput
	ToLogLevelArrayOutputWithContext(context.Context) LogLevelArrayOutput
}

type LogLevelArray []LogLevelInput

func (LogLevelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogLevel)(nil)).Elem()
}

func (i LogLevelArray) ToLogLevelArrayOutput() LogLevelArrayOutput {
	return i.ToLogLevelArrayOutputWithContext(context.Background())
}

func (i LogLevelArray) ToLogLevelArrayOutputWithContext(ctx context.Context) LogLevelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogLevelArrayOutput)
}

// LogLevelMapInput is an input type that accepts LogLevelMap and LogLevelMapOutput values.
// You can construct a concrete instance of `LogLevelMapInput` via:
//
//	LogLevelMap{ "key": LogLevelArgs{...} }
type LogLevelMapInput interface {
	pulumi.Input

	ToLogLevelMapOutput() LogLevelMapOutput
	ToLogLevelMapOutputWithContext(context.Context) LogLevelMapOutput
}

type LogLevelMap map[string]LogLevelInput

func (LogLevelMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogLevel)(nil)).Elem()
}

func (i LogLevelMap) ToLogLevelMapOutput() LogLevelMapOutput {
	return i.ToLogLevelMapOutputWithContext(context.Background())
}

func (i LogLevelMap) ToLogLevelMapOutputWithContext(ctx context.Context) LogLevelMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LogLevelMapOutput)
}

type LogLevelOutput struct{ *pulumi.OutputState }

func (LogLevelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LogLevel)(nil)).Elem()
}

func (o LogLevelOutput) ToLogLevelOutput() LogLevelOutput {
	return o
}

func (o LogLevelOutput) ToLogLevelOutputWithContext(ctx context.Context) LogLevelOutput {
	return o
}

// Log level string accepted by mox, such as debug, info, warn or error.
func (o LogLevelOutput) Level() pulumi.StringOutput {
	return o.ApplyT(func(v *LogLevel) pulumi.StringOutput { return v.Level }).(pulumi.StringOutput)
}

// Mox package/logger name to configure.
func (o LogLevelOutput) Package() pulumi.StringOutput {
	return o.ApplyT(func(v *LogLevel) pulumi.StringOutput { return v.Package }).(pulumi.StringOutput)
}

type LogLevelArrayOutput struct{ *pulumi.OutputState }

func (LogLevelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LogLevel)(nil)).Elem()
}

func (o LogLevelArrayOutput) ToLogLevelArrayOutput() LogLevelArrayOutput {
	return o
}

func (o LogLevelArrayOutput) ToLogLevelArrayOutputWithContext(ctx context.Context) LogLevelArrayOutput {
	return o
}

func (o LogLevelArrayOutput) Index(i pulumi.IntInput) LogLevelOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LogLevel {
		return vs[0].([]*LogLevel)[vs[1].(int)]
	}).(LogLevelOutput)
}

type LogLevelMapOutput struct{ *pulumi.OutputState }

func (LogLevelMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LogLevel)(nil)).Elem()
}

func (o LogLevelMapOutput) ToLogLevelMapOutput() LogLevelMapOutput {
	return o
}

func (o LogLevelMapOutput) ToLogLevelMapOutputWithContext(ctx context.Context) LogLevelMapOutput {
	return o
}

func (o LogLevelMapOutput) MapIndex(k pulumi.StringInput) LogLevelOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LogLevel {
		return vs[0].(map[string]*LogLevel)[vs[1].(string)]
	}).(LogLevelOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LogLevelInput)(nil)).Elem(), &LogLevel{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogLevelArrayInput)(nil)).Elem(), LogLevelArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LogLevelMapInput)(nil)).Elem(), LogLevelMap{})
	pulumi.RegisterOutputType(LogLevelOutput{})
	pulumi.RegisterOutputType(LogLevelArrayOutput{})
	pulumi.RegisterOutputType(LogLevelMapOutput{})
}
