// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Password for the mox admin LoginPrep/Login flow.
	AdminPassword pulumi.StringPtrOutput `pulumi:"adminPassword"`
	// Base URL of the mox admin interface, e.g. https://mox-admin.example.com.
	AdminUrl pulumi.StringPtrOutput `pulumi:"adminUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.AdminPassword == nil {
		if d := internal.GetEnvOrDefault("", nil, "MOX_ADMIN_PASSWORD"); d != nil {
			args.AdminPassword = pulumi.StringPtr(d.(string))
		}
	}
	if args.AdminUrl == nil {
		if d := internal.GetEnvOrDefault("", nil, "MOX_ADMIN_URL"); d != nil {
			args.AdminUrl = pulumi.StringPtr(d.(string))
		}
	}
	if args.AdminPassword != nil {
		args.AdminPassword = pulumi.ToSecret(args.AdminPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"adminPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:mox", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Password for the mox admin LoginPrep/Login flow.
	AdminPassword *string `pulumi:"adminPassword"`
	// Base URL of the mox admin interface, e.g. https://mox-admin.example.com.
	AdminUrl *string `pulumi:"adminUrl"`
	// Disable TLS certificate verification (dev/self-signed only).
	InsecureSkipVerify *bool `pulumi:"insecureSkipVerify"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Password for the mox admin LoginPrep/Login flow.
	AdminPassword pulumi.StringPtrInput
	// Base URL of the mox admin interface, e.g. https://mox-admin.example.com.
	AdminUrl pulumi.StringPtrInput
	// Disable TLS certificate verification (dev/self-signed only).
	InsecureSkipVerify pulumi.BoolPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Password for the mox admin LoginPrep/Login flow.
func (o ProviderOutput) AdminPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AdminPassword }).(pulumi.StringPtrOutput)
}

// Base URL of the mox admin interface, e.g. https://mox-admin.example.com.
func (o ProviderOutput) AdminUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AdminUrl }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
