// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AccountRoute struct {
	FromDomains     []string `pulumi:"fromDomains"`
	MinimumAttempts *int     `pulumi:"minimumAttempts"`
	ToDomains       []string `pulumi:"toDomains"`
	Transport       string   `pulumi:"transport"`
}

// AccountRouteInput is an input type that accepts AccountRouteArgs and AccountRouteOutput values.
// You can construct a concrete instance of `AccountRouteInput` via:
//
//	AccountRouteArgs{...}
type AccountRouteInput interface {
	pulumi.Input

	ToAccountRouteOutput() AccountRouteOutput
	ToAccountRouteOutputWithContext(context.Context) AccountRouteOutput
}

type AccountRouteArgs struct {
	FromDomains     pulumi.StringArrayInput `pulumi:"fromDomains"`
	MinimumAttempts pulumi.IntPtrInput      `pulumi:"minimumAttempts"`
	ToDomains       pulumi.StringArrayInput `pulumi:"toDomains"`
	Transport       pulumi.StringInput      `pulumi:"transport"`
}

func (AccountRouteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AccountRoute)(nil)).Elem()
}

func (i AccountRouteArgs) ToAccountRouteOutput() AccountRouteOutput {
	return i.ToAccountRouteOutputWithContext(context.Background())
}

func (i AccountRouteArgs) ToAccountRouteOutputWithContext(ctx context.Context) AccountRouteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountRouteOutput)
}

// AccountRouteArrayInput is an input type that accepts AccountRouteArray and AccountRouteArrayOutput values.
// You can construct a concrete instance of `AccountRouteArrayInput` via:
//
//	AccountRouteArray{ AccountRouteArgs{...} }
type AccountRouteArrayInput interface {
	pulumi.Input

	ToAccountRouteArrayOutput() AccountRouteArrayOutput
	ToAccountRouteArrayOutputWithContext(context.Context) AccountRouteArrayOutput
}

type AccountRouteArray []AccountRouteInput

func (AccountRouteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccountRoute)(nil)).Elem()
}

func (i AccountRouteArray) ToAccountRouteArrayOutput() AccountRouteArrayOutput {
	return i.ToAccountRouteArrayOutputWithContext(context.Background())
}

func (i AccountRouteArray) ToAccountRouteArrayOutputWithContext(ctx context.Context) AccountRouteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountRouteArrayOutput)
}

type AccountRouteOutput struct{ *pulumi.OutputState }

func (AccountRouteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AccountRoute)(nil)).Elem()
}

func (o AccountRouteOutput) ToAccountRouteOutput() AccountRouteOutput {
	return o
}

func (o AccountRouteOutput) ToAccountRouteOutputWithContext(ctx context.Context) AccountRouteOutput {
	return o
}

func (o AccountRouteOutput) FromDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AccountRoute) []string { return v.FromDomains }).(pulumi.StringArrayOutput)
}

func (o AccountRouteOutput) MinimumAttempts() pulumi.IntPtrOutput {
	return o.ApplyT(func(v AccountRoute) *int { return v.MinimumAttempts }).(pulumi.IntPtrOutput)
}

func (o AccountRouteOutput) ToDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AccountRoute) []string { return v.ToDomains }).(pulumi.StringArrayOutput)
}

func (o AccountRouteOutput) Transport() pulumi.StringOutput {
	return o.ApplyT(func(v AccountRoute) string { return v.Transport }).(pulumi.StringOutput)
}

type AccountRouteArrayOutput struct{ *pulumi.OutputState }

func (AccountRouteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccountRoute)(nil)).Elem()
}

func (o AccountRouteArrayOutput) ToAccountRouteArrayOutput() AccountRouteArrayOutput {
	return o
}

func (o AccountRouteArrayOutput) ToAccountRouteArrayOutputWithContext(ctx context.Context) AccountRouteArrayOutput {
	return o
}

func (o AccountRouteArrayOutput) Index(i pulumi.IntInput) AccountRouteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AccountRoute {
		return vs[0].([]AccountRoute)[vs[1].(int)]
	}).(AccountRouteOutput)
}

type DkimDNSRecord struct {
	// DKIM selector (the label before "._domainkey").
	Selector string `pulumi:"selector"`
	// Full DKIM TXT record value, e.g. "v=DKIM1;h=sha256;p=...".
	Txt string `pulumi:"txt"`
}

type DkimDNSRecordOutput struct{ *pulumi.OutputState }

func (DkimDNSRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DkimDNSRecord)(nil)).Elem()
}

func (o DkimDNSRecordOutput) ToDkimDNSRecordOutput() DkimDNSRecordOutput {
	return o
}

func (o DkimDNSRecordOutput) ToDkimDNSRecordOutputWithContext(ctx context.Context) DkimDNSRecordOutput {
	return o
}

// DKIM selector (the label before "._domainkey").
func (o DkimDNSRecordOutput) Selector() pulumi.StringOutput {
	return o.ApplyT(func(v DkimDNSRecord) string { return v.Selector }).(pulumi.StringOutput)
}

// Full DKIM TXT record value, e.g. "v=DKIM1;h=sha256;p=...".
func (o DkimDNSRecordOutput) Txt() pulumi.StringOutput {
	return o.ApplyT(func(v DkimDNSRecord) string { return v.Txt }).(pulumi.StringOutput)
}

type DkimDNSRecordArrayOutput struct{ *pulumi.OutputState }

func (DkimDNSRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DkimDNSRecord)(nil)).Elem()
}

func (o DkimDNSRecordArrayOutput) ToDkimDNSRecordArrayOutput() DkimDNSRecordArrayOutput {
	return o
}

func (o DkimDNSRecordArrayOutput) ToDkimDNSRecordArrayOutputWithContext(ctx context.Context) DkimDNSRecordArrayOutput {
	return o
}

func (o DkimDNSRecordArrayOutput) Index(i pulumi.IntInput) DkimDNSRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DkimDNSRecord {
		return vs[0].([]DkimDNSRecord)[vs[1].(int)]
	}).(DkimDNSRecordOutput)
}

type DomainLocalpartConfig struct {
	// Whether localparts are case-sensitive.
	CaseSensitive *bool `pulumi:"caseSensitive"`
	// Separators used for sub-addressing, e.g. "+".
	CatchallSeparators []string `pulumi:"catchallSeparators"`
}

// DomainLocalpartConfigInput is an input type that accepts DomainLocalpartConfigArgs and DomainLocalpartConfigOutput values.
// You can construct a concrete instance of `DomainLocalpartConfigInput` via:
//
//	DomainLocalpartConfigArgs{...}
type DomainLocalpartConfigInput interface {
	pulumi.Input

	ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput
	ToDomainLocalpartConfigOutputWithContext(context.Context) DomainLocalpartConfigOutput
}

type DomainLocalpartConfigArgs struct {
	// Whether localparts are case-sensitive.
	CaseSensitive pulumi.BoolPtrInput `pulumi:"caseSensitive"`
	// Separators used for sub-addressing, e.g. "+".
	CatchallSeparators pulumi.StringArrayInput `pulumi:"catchallSeparators"`
}

func (DomainLocalpartConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainLocalpartConfig)(nil)).Elem()
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput {
	return i.ToDomainLocalpartConfigOutputWithContext(context.Background())
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigOutputWithContext(ctx context.Context) DomainLocalpartConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigOutput)
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return i.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigOutput).ToDomainLocalpartConfigPtrOutputWithContext(ctx)
}

// DomainLocalpartConfigPtrInput is an input type that accepts DomainLocalpartConfigArgs, DomainLocalpartConfigPtr and DomainLocalpartConfigPtrOutput values.
// You can construct a concrete instance of `DomainLocalpartConfigPtrInput` via:
//
//	        DomainLocalpartConfigArgs{...}
//
//	or:
//
//	        nil
type DomainLocalpartConfigPtrInput interface {
	pulumi.Input

	ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput
	ToDomainLocalpartConfigPtrOutputWithContext(context.Context) DomainLocalpartConfigPtrOutput
}

type domainLocalpartConfigPtrType DomainLocalpartConfigArgs

func DomainLocalpartConfigPtr(v *DomainLocalpartConfigArgs) DomainLocalpartConfigPtrInput {
	return (*domainLocalpartConfigPtrType)(v)
}

func (*domainLocalpartConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainLocalpartConfig)(nil)).Elem()
}

func (i *domainLocalpartConfigPtrType) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return i.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (i *domainLocalpartConfigPtrType) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigPtrOutput)
}

type DomainLocalpartConfigOutput struct{ *pulumi.OutputState }

func (DomainLocalpartConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainLocalpartConfig)(nil)).Elem()
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput {
	return o
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigOutputWithContext(ctx context.Context) DomainLocalpartConfigOutput {
	return o
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return o.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainLocalpartConfig) *DomainLocalpartConfig {
		return &v
	}).(DomainLocalpartConfigPtrOutput)
}

// Whether localparts are case-sensitive.
func (o DomainLocalpartConfigOutput) CaseSensitive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainLocalpartConfig) *bool { return v.CaseSensitive }).(pulumi.BoolPtrOutput)
}

// Separators used for sub-addressing, e.g. "+".
func (o DomainLocalpartConfigOutput) CatchallSeparators() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainLocalpartConfig) []string { return v.CatchallSeparators }).(pulumi.StringArrayOutput)
}

type DomainLocalpartConfigPtrOutput struct{ *pulumi.OutputState }

func (DomainLocalpartConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainLocalpartConfig)(nil)).Elem()
}

func (o DomainLocalpartConfigPtrOutput) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return o
}

func (o DomainLocalpartConfigPtrOutput) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return o
}

func (o DomainLocalpartConfigPtrOutput) Elem() DomainLocalpartConfigOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) DomainLocalpartConfig {
		if v != nil {
			return *v
		}
		var ret DomainLocalpartConfig
		return ret
	}).(DomainLocalpartConfigOutput)
}

// Whether localparts are case-sensitive.
func (o DomainLocalpartConfigPtrOutput) CaseSensitive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) *bool {
		if v == nil {
			return nil
		}
		return v.CaseSensitive
	}).(pulumi.BoolPtrOutput)
}

// Separators used for sub-addressing, e.g. "+".
func (o DomainLocalpartConfigPtrOutput) CatchallSeparators() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) []string {
		if v == nil {
			return nil
		}
		return v.CatchallSeparators
	}).(pulumi.StringArrayOutput)
}

type DomainMtaSts struct {
	// Policy lifetime in seconds.
	MaxAgeSeconds int `pulumi:"maxAgeSeconds"`
	// MTA-STS mode: "enforce", "testing" or "none".
	Mode string `pulumi:"mode"`
	// Permitted MX host patterns.
	Mx []string `pulumi:"mx"`
	// Policy version identifier; change it to signal an updated policy to senders.
	PolicyId string `pulumi:"policyId"`
}

// DomainMtaStsInput is an input type that accepts DomainMtaStsArgs and DomainMtaStsOutput values.
// You can construct a concrete instance of `DomainMtaStsInput` via:
//
//	DomainMtaStsArgs{...}
type DomainMtaStsInput interface {
	pulumi.Input

	ToDomainMtaStsOutput() DomainMtaStsOutput
	ToDomainMtaStsOutputWithContext(context.Context) DomainMtaStsOutput
}

type DomainMtaStsArgs struct {
	// Policy lifetime in seconds.
	MaxAgeSeconds pulumi.IntInput `pulumi:"maxAgeSeconds"`
	// MTA-STS mode: "enforce", "testing" or "none".
	Mode pulumi.StringInput `pulumi:"mode"`
	// Permitted MX host patterns.
	Mx pulumi.StringArrayInput `pulumi:"mx"`
	// Policy version identifier; change it to signal an updated policy to senders.
	PolicyId pulumi.StringInput `pulumi:"policyId"`
}

func (DomainMtaStsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainMtaSts)(nil)).Elem()
}

func (i DomainMtaStsArgs) ToDomainMtaStsOutput() DomainMtaStsOutput {
	return i.ToDomainMtaStsOutputWithContext(context.Background())
}

func (i DomainMtaStsArgs) ToDomainMtaStsOutputWithContext(ctx context.Context) DomainMtaStsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsOutput)
}

func (i DomainMtaStsArgs) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return i.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (i DomainMtaStsArgs) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsOutput).ToDomainMtaStsPtrOutputWithContext(ctx)
}

// DomainMtaStsPtrInput is an input type that accepts DomainMtaStsArgs, DomainMtaStsPtr and DomainMtaStsPtrOutput values.
// You can construct a concrete instance of `DomainMtaStsPtrInput` via:
//
//	        DomainMtaStsArgs{...}
//
//	or:
//
//	        nil
type DomainMtaStsPtrInput interface {
	pulumi.Input

	ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput
	ToDomainMtaStsPtrOutputWithContext(context.Context) DomainMtaStsPtrOutput
}

type domainMtaStsPtrType DomainMtaStsArgs

func DomainMtaStsPtr(v *DomainMtaStsArgs) DomainMtaStsPtrInput {
	return (*domainMtaStsPtrType)(v)
}

func (*domainMtaStsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainMtaSts)(nil)).Elem()
}

func (i *domainMtaStsPtrType) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return i.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (i *domainMtaStsPtrType) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsPtrOutput)
}

type DomainMtaStsOutput struct{ *pulumi.OutputState }

func (DomainMtaStsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainMtaSts)(nil)).Elem()
}

func (o DomainMtaStsOutput) ToDomainMtaStsOutput() DomainMtaStsOutput {
	return o
}

func (o DomainMtaStsOutput) ToDomainMtaStsOutputWithContext(ctx context.Context) DomainMtaStsOutput {
	return o
}

func (o DomainMtaStsOutput) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return o.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (o DomainMtaStsOutput) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainMtaSts) *DomainMtaSts {
		return &v
	}).(DomainMtaStsPtrOutput)
}

// Policy lifetime in seconds.
func (o DomainMtaStsOutput) MaxAgeSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v DomainMtaSts) int { return v.MaxAgeSeconds }).(pulumi.IntOutput)
}

// MTA-STS mode: "enforce", "testing" or "none".
func (o DomainMtaStsOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v DomainMtaSts) string { return v.Mode }).(pulumi.StringOutput)
}

// Permitted MX host patterns.
func (o DomainMtaStsOutput) Mx() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainMtaSts) []string { return v.Mx }).(pulumi.StringArrayOutput)
}

// Policy version identifier; change it to signal an updated policy to senders.
func (o DomainMtaStsOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v DomainMtaSts) string { return v.PolicyId }).(pulumi.StringOutput)
}

type DomainMtaStsPtrOutput struct{ *pulumi.OutputState }

func (DomainMtaStsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainMtaSts)(nil)).Elem()
}

func (o DomainMtaStsPtrOutput) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return o
}

func (o DomainMtaStsPtrOutput) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return o
}

func (o DomainMtaStsPtrOutput) Elem() DomainMtaStsOutput {
	return o.ApplyT(func(v *DomainMtaSts) DomainMtaSts {
		if v != nil {
			return *v
		}
		var ret DomainMtaSts
		return ret
	}).(DomainMtaStsOutput)
}

// Policy lifetime in seconds.
func (o DomainMtaStsPtrOutput) MaxAgeSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *int {
		if v == nil {
			return nil
		}
		return &v.MaxAgeSeconds
	}).(pulumi.IntPtrOutput)
}

// MTA-STS mode: "enforce", "testing" or "none".
func (o DomainMtaStsPtrOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *string {
		if v == nil {
			return nil
		}
		return &v.Mode
	}).(pulumi.StringPtrOutput)
}

// Permitted MX host patterns.
func (o DomainMtaStsPtrOutput) Mx() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DomainMtaSts) []string {
		if v == nil {
			return nil
		}
		return v.Mx
	}).(pulumi.StringArrayOutput)
}

// Policy version identifier; change it to signal an updated policy to senders.
func (o DomainMtaStsPtrOutput) PolicyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *string {
		if v == nil {
			return nil
		}
		return &v.PolicyId
	}).(pulumi.StringPtrOutput)
}

type DomainReportAddress struct {
	// Mox account that receives the reports.
	Account string `pulumi:"account"`
	// Report destination domain. Empty means the domain itself.
	Domain *string `pulumi:"domain"`
	// Local part of the report destination address.
	Localpart string `pulumi:"localpart"`
	// Destination mailbox within the account.
	Mailbox *string `pulumi:"mailbox"`
}

// DomainReportAddressInput is an input type that accepts DomainReportAddressArgs and DomainReportAddressOutput values.
// You can construct a concrete instance of `DomainReportAddressInput` via:
//
//	DomainReportAddressArgs{...}
type DomainReportAddressInput interface {
	pulumi.Input

	ToDomainReportAddressOutput() DomainReportAddressOutput
	ToDomainReportAddressOutputWithContext(context.Context) DomainReportAddressOutput
}

type DomainReportAddressArgs struct {
	// Mox account that receives the reports.
	Account pulumi.StringInput `pulumi:"account"`
	// Report destination domain. Empty means the domain itself.
	Domain pulumi.StringPtrInput `pulumi:"domain"`
	// Local part of the report destination address.
	Localpart pulumi.StringInput `pulumi:"localpart"`
	// Destination mailbox within the account.
	Mailbox pulumi.StringPtrInput `pulumi:"mailbox"`
}

func (DomainReportAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainReportAddress)(nil)).Elem()
}

func (i DomainReportAddressArgs) ToDomainReportAddressOutput() DomainReportAddressOutput {
	return i.ToDomainReportAddressOutputWithContext(context.Background())
}

func (i DomainReportAddressArgs) ToDomainReportAddressOutputWithContext(ctx context.Context) DomainReportAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressOutput)
}

func (i DomainReportAddressArgs) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return i.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (i DomainReportAddressArgs) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressOutput).ToDomainReportAddressPtrOutputWithContext(ctx)
}

// DomainReportAddressPtrInput is an input type that accepts DomainReportAddressArgs, DomainReportAddressPtr and DomainReportAddressPtrOutput values.
// You can construct a concrete instance of `DomainReportAddressPtrInput` via:
//
//	        DomainReportAddressArgs{...}
//
//	or:
//
//	        nil
type DomainReportAddressPtrInput interface {
	pulumi.Input

	ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput
	ToDomainReportAddressPtrOutputWithContext(context.Context) DomainReportAddressPtrOutput
}

type domainReportAddressPtrType DomainReportAddressArgs

func DomainReportAddressPtr(v *DomainReportAddressArgs) DomainReportAddressPtrInput {
	return (*domainReportAddressPtrType)(v)
}

func (*domainReportAddressPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainReportAddress)(nil)).Elem()
}

func (i *domainReportAddressPtrType) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return i.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (i *domainReportAddressPtrType) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressPtrOutput)
}

type DomainReportAddressOutput struct{ *pulumi.OutputState }

func (DomainReportAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainReportAddress)(nil)).Elem()
}

func (o DomainReportAddressOutput) ToDomainReportAddressOutput() DomainReportAddressOutput {
	return o
}

func (o DomainReportAddressOutput) ToDomainReportAddressOutputWithContext(ctx context.Context) DomainReportAddressOutput {
	return o
}

func (o DomainReportAddressOutput) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return o.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (o DomainReportAddressOutput) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainReportAddress) *DomainReportAddress {
		return &v
	}).(DomainReportAddressPtrOutput)
}

// Mox account that receives the reports.
func (o DomainReportAddressOutput) Account() pulumi.StringOutput {
	return o.ApplyT(func(v DomainReportAddress) string { return v.Account }).(pulumi.StringOutput)
}

// Report destination domain. Empty means the domain itself.
func (o DomainReportAddressOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainReportAddress) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

// Local part of the report destination address.
func (o DomainReportAddressOutput) Localpart() pulumi.StringOutput {
	return o.ApplyT(func(v DomainReportAddress) string { return v.Localpart }).(pulumi.StringOutput)
}

// Destination mailbox within the account.
func (o DomainReportAddressOutput) Mailbox() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainReportAddress) *string { return v.Mailbox }).(pulumi.StringPtrOutput)
}

type DomainReportAddressPtrOutput struct{ *pulumi.OutputState }

func (DomainReportAddressPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainReportAddress)(nil)).Elem()
}

func (o DomainReportAddressPtrOutput) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return o
}

func (o DomainReportAddressPtrOutput) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return o
}

func (o DomainReportAddressPtrOutput) Elem() DomainReportAddressOutput {
	return o.ApplyT(func(v *DomainReportAddress) DomainReportAddress {
		if v != nil {
			return *v
		}
		var ret DomainReportAddress
		return ret
	}).(DomainReportAddressOutput)
}

// Mox account that receives the reports.
func (o DomainReportAddressPtrOutput) Account() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return &v.Account
	}).(pulumi.StringPtrOutput)
}

// Report destination domain. Empty means the domain itself.
func (o DomainReportAddressPtrOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return v.Domain
	}).(pulumi.StringPtrOutput)
}

// Local part of the report destination address.
func (o DomainReportAddressPtrOutput) Localpart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return &v.Localpart
	}).(pulumi.StringPtrOutput)
}

// Destination mailbox within the account.
func (o DomainReportAddressPtrOutput) Mailbox() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return v.Mailbox
	}).(pulumi.StringPtrOutput)
}

type DomainSieve struct {
	// Whether fileinto creates missing mailboxes.
	AutoCreateMailboxes *bool `pulumi:"autoCreateMailboxes"`
	// Enable or disable Sieve filtering at this domain scope.
	Enabled *bool `pulumi:"enabled"`
	// Whether the active Sieve script runs for incoming SMTP delivery.
	RunOnDelivery *bool `pulumi:"runOnDelivery"`
	// Whether RFC 6785 IMAPSIEVE scripts run on IMAP events.
	RunOnIMAPEvents *bool `pulumi:"runOnIMAPEvents"`
}

// DomainSieveInput is an input type that accepts DomainSieveArgs and DomainSieveOutput values.
// You can construct a concrete instance of `DomainSieveInput` via:
//
//	DomainSieveArgs{...}
type DomainSieveInput interface {
	pulumi.Input

	ToDomainSieveOutput() DomainSieveOutput
	ToDomainSieveOutputWithContext(context.Context) DomainSieveOutput
}

type DomainSieveArgs struct {
	// Whether fileinto creates missing mailboxes.
	AutoCreateMailboxes pulumi.BoolPtrInput `pulumi:"autoCreateMailboxes"`
	// Enable or disable Sieve filtering at this domain scope.
	Enabled pulumi.BoolPtrInput `pulumi:"enabled"`
	// Whether the active Sieve script runs for incoming SMTP delivery.
	RunOnDelivery pulumi.BoolPtrInput `pulumi:"runOnDelivery"`
	// Whether RFC 6785 IMAPSIEVE scripts run on IMAP events.
	RunOnIMAPEvents pulumi.BoolPtrInput `pulumi:"runOnIMAPEvents"`
}

func (DomainSieveArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainSieve)(nil)).Elem()
}

func (i DomainSieveArgs) ToDomainSieveOutput() DomainSieveOutput {
	return i.ToDomainSieveOutputWithContext(context.Background())
}

func (i DomainSieveArgs) ToDomainSieveOutputWithContext(ctx context.Context) DomainSieveOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainSieveOutput)
}

func (i DomainSieveArgs) ToDomainSievePtrOutput() DomainSievePtrOutput {
	return i.ToDomainSievePtrOutputWithContext(context.Background())
}

func (i DomainSieveArgs) ToDomainSievePtrOutputWithContext(ctx context.Context) DomainSievePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainSieveOutput).ToDomainSievePtrOutputWithContext(ctx)
}

// DomainSievePtrInput is an input type that accepts DomainSieveArgs, DomainSievePtr and DomainSievePtrOutput values.
// You can construct a concrete instance of `DomainSievePtrInput` via:
//
//	        DomainSieveArgs{...}
//
//	or:
//
//	        nil
type DomainSievePtrInput interface {
	pulumi.Input

	ToDomainSievePtrOutput() DomainSievePtrOutput
	ToDomainSievePtrOutputWithContext(context.Context) DomainSievePtrOutput
}

type domainSievePtrType DomainSieveArgs

func DomainSievePtr(v *DomainSieveArgs) DomainSievePtrInput {
	return (*domainSievePtrType)(v)
}

func (*domainSievePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainSieve)(nil)).Elem()
}

func (i *domainSievePtrType) ToDomainSievePtrOutput() DomainSievePtrOutput {
	return i.ToDomainSievePtrOutputWithContext(context.Background())
}

func (i *domainSievePtrType) ToDomainSievePtrOutputWithContext(ctx context.Context) DomainSievePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainSievePtrOutput)
}

type DomainSieveOutput struct{ *pulumi.OutputState }

func (DomainSieveOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainSieve)(nil)).Elem()
}

func (o DomainSieveOutput) ToDomainSieveOutput() DomainSieveOutput {
	return o
}

func (o DomainSieveOutput) ToDomainSieveOutputWithContext(ctx context.Context) DomainSieveOutput {
	return o
}

func (o DomainSieveOutput) ToDomainSievePtrOutput() DomainSievePtrOutput {
	return o.ToDomainSievePtrOutputWithContext(context.Background())
}

func (o DomainSieveOutput) ToDomainSievePtrOutputWithContext(ctx context.Context) DomainSievePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainSieve) *DomainSieve {
		return &v
	}).(DomainSievePtrOutput)
}

// Whether fileinto creates missing mailboxes.
func (o DomainSieveOutput) AutoCreateMailboxes() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainSieve) *bool { return v.AutoCreateMailboxes }).(pulumi.BoolPtrOutput)
}

// Enable or disable Sieve filtering at this domain scope.
func (o DomainSieveOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainSieve) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Whether the active Sieve script runs for incoming SMTP delivery.
func (o DomainSieveOutput) RunOnDelivery() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainSieve) *bool { return v.RunOnDelivery }).(pulumi.BoolPtrOutput)
}

// Whether RFC 6785 IMAPSIEVE scripts run on IMAP events.
func (o DomainSieveOutput) RunOnIMAPEvents() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainSieve) *bool { return v.RunOnIMAPEvents }).(pulumi.BoolPtrOutput)
}

type DomainSievePtrOutput struct{ *pulumi.OutputState }

func (DomainSievePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainSieve)(nil)).Elem()
}

func (o DomainSievePtrOutput) ToDomainSievePtrOutput() DomainSievePtrOutput {
	return o
}

func (o DomainSievePtrOutput) ToDomainSievePtrOutputWithContext(ctx context.Context) DomainSievePtrOutput {
	return o
}

func (o DomainSievePtrOutput) Elem() DomainSieveOutput {
	return o.ApplyT(func(v *DomainSieve) DomainSieve {
		if v != nil {
			return *v
		}
		var ret DomainSieve
		return ret
	}).(DomainSieveOutput)
}

// Whether fileinto creates missing mailboxes.
func (o DomainSievePtrOutput) AutoCreateMailboxes() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainSieve) *bool {
		if v == nil {
			return nil
		}
		return v.AutoCreateMailboxes
	}).(pulumi.BoolPtrOutput)
}

// Enable or disable Sieve filtering at this domain scope.
func (o DomainSievePtrOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainSieve) *bool {
		if v == nil {
			return nil
		}
		return v.Enabled
	}).(pulumi.BoolPtrOutput)
}

// Whether the active Sieve script runs for incoming SMTP delivery.
func (o DomainSievePtrOutput) RunOnDelivery() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainSieve) *bool {
		if v == nil {
			return nil
		}
		return v.RunOnDelivery
	}).(pulumi.BoolPtrOutput)
}

// Whether RFC 6785 IMAPSIEVE scripts run on IMAP events.
func (o DomainSievePtrOutput) RunOnIMAPEvents() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainSieve) *bool {
		if v == nil {
			return nil
		}
		return v.RunOnIMAPEvents
	}).(pulumi.BoolPtrOutput)
}

type WebDomainRedirect struct {
	// Source domain to redirect from.
	From string `pulumi:"from"`
	// Destination domain to redirect to.
	To string `pulumi:"to"`
}

// WebDomainRedirectInput is an input type that accepts WebDomainRedirectArgs and WebDomainRedirectOutput values.
// You can construct a concrete instance of `WebDomainRedirectInput` via:
//
//	WebDomainRedirectArgs{...}
type WebDomainRedirectInput interface {
	pulumi.Input

	ToWebDomainRedirectOutput() WebDomainRedirectOutput
	ToWebDomainRedirectOutputWithContext(context.Context) WebDomainRedirectOutput
}

type WebDomainRedirectArgs struct {
	// Source domain to redirect from.
	From pulumi.StringInput `pulumi:"from"`
	// Destination domain to redirect to.
	To pulumi.StringInput `pulumi:"to"`
}

func (WebDomainRedirectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebDomainRedirect)(nil)).Elem()
}

func (i WebDomainRedirectArgs) ToWebDomainRedirectOutput() WebDomainRedirectOutput {
	return i.ToWebDomainRedirectOutputWithContext(context.Background())
}

func (i WebDomainRedirectArgs) ToWebDomainRedirectOutputWithContext(ctx context.Context) WebDomainRedirectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebDomainRedirectOutput)
}

// WebDomainRedirectArrayInput is an input type that accepts WebDomainRedirectArray and WebDomainRedirectArrayOutput values.
// You can construct a concrete instance of `WebDomainRedirectArrayInput` via:
//
//	WebDomainRedirectArray{ WebDomainRedirectArgs{...} }
type WebDomainRedirectArrayInput interface {
	pulumi.Input

	ToWebDomainRedirectArrayOutput() WebDomainRedirectArrayOutput
	ToWebDomainRedirectArrayOutputWithContext(context.Context) WebDomainRedirectArrayOutput
}

type WebDomainRedirectArray []WebDomainRedirectInput

func (WebDomainRedirectArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebDomainRedirect)(nil)).Elem()
}

func (i WebDomainRedirectArray) ToWebDomainRedirectArrayOutput() WebDomainRedirectArrayOutput {
	return i.ToWebDomainRedirectArrayOutputWithContext(context.Background())
}

func (i WebDomainRedirectArray) ToWebDomainRedirectArrayOutputWithContext(ctx context.Context) WebDomainRedirectArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebDomainRedirectArrayOutput)
}

type WebDomainRedirectOutput struct{ *pulumi.OutputState }

func (WebDomainRedirectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebDomainRedirect)(nil)).Elem()
}

func (o WebDomainRedirectOutput) ToWebDomainRedirectOutput() WebDomainRedirectOutput {
	return o
}

func (o WebDomainRedirectOutput) ToWebDomainRedirectOutputWithContext(ctx context.Context) WebDomainRedirectOutput {
	return o
}

// Source domain to redirect from.
func (o WebDomainRedirectOutput) From() pulumi.StringOutput {
	return o.ApplyT(func(v WebDomainRedirect) string { return v.From }).(pulumi.StringOutput)
}

// Destination domain to redirect to.
func (o WebDomainRedirectOutput) To() pulumi.StringOutput {
	return o.ApplyT(func(v WebDomainRedirect) string { return v.To }).(pulumi.StringOutput)
}

type WebDomainRedirectArrayOutput struct{ *pulumi.OutputState }

func (WebDomainRedirectArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebDomainRedirect)(nil)).Elem()
}

func (o WebDomainRedirectArrayOutput) ToWebDomainRedirectArrayOutput() WebDomainRedirectArrayOutput {
	return o
}

func (o WebDomainRedirectArrayOutput) ToWebDomainRedirectArrayOutputWithContext(ctx context.Context) WebDomainRedirectArrayOutput {
	return o
}

func (o WebDomainRedirectArrayOutput) Index(i pulumi.IntInput) WebDomainRedirectOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) WebDomainRedirect {
		return vs[0].([]WebDomainRedirect)[vs[1].(int)]
	}).(WebDomainRedirectOutput)
}

type WebForward struct {
	ResponseHeaders map[string]string `pulumi:"responseHeaders"`
	StripPath       *bool             `pulumi:"stripPath"`
	Url             string            `pulumi:"url"`
}

// WebForwardInput is an input type that accepts WebForwardArgs and WebForwardOutput values.
// You can construct a concrete instance of `WebForwardInput` via:
//
//	WebForwardArgs{...}
type WebForwardInput interface {
	pulumi.Input

	ToWebForwardOutput() WebForwardOutput
	ToWebForwardOutputWithContext(context.Context) WebForwardOutput
}

type WebForwardArgs struct {
	ResponseHeaders pulumi.StringMapInput `pulumi:"responseHeaders"`
	StripPath       pulumi.BoolPtrInput   `pulumi:"stripPath"`
	Url             pulumi.StringInput    `pulumi:"url"`
}

func (WebForwardArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebForward)(nil)).Elem()
}

func (i WebForwardArgs) ToWebForwardOutput() WebForwardOutput {
	return i.ToWebForwardOutputWithContext(context.Background())
}

func (i WebForwardArgs) ToWebForwardOutputWithContext(ctx context.Context) WebForwardOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebForwardOutput)
}

func (i WebForwardArgs) ToWebForwardPtrOutput() WebForwardPtrOutput {
	return i.ToWebForwardPtrOutputWithContext(context.Background())
}

func (i WebForwardArgs) ToWebForwardPtrOutputWithContext(ctx context.Context) WebForwardPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebForwardOutput).ToWebForwardPtrOutputWithContext(ctx)
}

// WebForwardPtrInput is an input type that accepts WebForwardArgs, WebForwardPtr and WebForwardPtrOutput values.
// You can construct a concrete instance of `WebForwardPtrInput` via:
//
//	        WebForwardArgs{...}
//
//	or:
//
//	        nil
type WebForwardPtrInput interface {
	pulumi.Input

	ToWebForwardPtrOutput() WebForwardPtrOutput
	ToWebForwardPtrOutputWithContext(context.Context) WebForwardPtrOutput
}

type webForwardPtrType WebForwardArgs

func WebForwardPtr(v *WebForwardArgs) WebForwardPtrInput {
	return (*webForwardPtrType)(v)
}

func (*webForwardPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebForward)(nil)).Elem()
}

func (i *webForwardPtrType) ToWebForwardPtrOutput() WebForwardPtrOutput {
	return i.ToWebForwardPtrOutputWithContext(context.Background())
}

func (i *webForwardPtrType) ToWebForwardPtrOutputWithContext(ctx context.Context) WebForwardPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebForwardPtrOutput)
}

type WebForwardOutput struct{ *pulumi.OutputState }

func (WebForwardOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebForward)(nil)).Elem()
}

func (o WebForwardOutput) ToWebForwardOutput() WebForwardOutput {
	return o
}

func (o WebForwardOutput) ToWebForwardOutputWithContext(ctx context.Context) WebForwardOutput {
	return o
}

func (o WebForwardOutput) ToWebForwardPtrOutput() WebForwardPtrOutput {
	return o.ToWebForwardPtrOutputWithContext(context.Background())
}

func (o WebForwardOutput) ToWebForwardPtrOutputWithContext(ctx context.Context) WebForwardPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebForward) *WebForward {
		return &v
	}).(WebForwardPtrOutput)
}

func (o WebForwardOutput) ResponseHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v WebForward) map[string]string { return v.ResponseHeaders }).(pulumi.StringMapOutput)
}

func (o WebForwardOutput) StripPath() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v WebForward) *bool { return v.StripPath }).(pulumi.BoolPtrOutput)
}

func (o WebForwardOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v WebForward) string { return v.Url }).(pulumi.StringOutput)
}

type WebForwardPtrOutput struct{ *pulumi.OutputState }

func (WebForwardPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebForward)(nil)).Elem()
}

func (o WebForwardPtrOutput) ToWebForwardPtrOutput() WebForwardPtrOutput {
	return o
}

func (o WebForwardPtrOutput) ToWebForwardPtrOutputWithContext(ctx context.Context) WebForwardPtrOutput {
	return o
}

func (o WebForwardPtrOutput) Elem() WebForwardOutput {
	return o.ApplyT(func(v *WebForward) WebForward {
		if v != nil {
			return *v
		}
		var ret WebForward
		return ret
	}).(WebForwardOutput)
}

func (o WebForwardPtrOutput) ResponseHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WebForward) map[string]string {
		if v == nil {
			return nil
		}
		return v.ResponseHeaders
	}).(pulumi.StringMapOutput)
}

func (o WebForwardPtrOutput) StripPath() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WebForward) *bool {
		if v == nil {
			return nil
		}
		return v.StripPath
	}).(pulumi.BoolPtrOutput)
}

func (o WebForwardPtrOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebForward) *string {
		if v == nil {
			return nil
		}
		return &v.Url
	}).(pulumi.StringPtrOutput)
}

type WebHandler struct {
	Compress              *bool        `pulumi:"compress"`
	Domain                string       `pulumi:"domain"`
	DontRedirectPlainHTTP *bool        `pulumi:"dontRedirectPlainHTTP"`
	Forward               *WebForward  `pulumi:"forward"`
	Internal              *WebInternal `pulumi:"internal"`
	LogName               *string      `pulumi:"logName"`
	PathRegexp            string       `pulumi:"pathRegexp"`
	Redirect              *WebRedirect `pulumi:"redirect"`
	Static                *WebStatic   `pulumi:"static"`
}

// WebHandlerInput is an input type that accepts WebHandlerArgs and WebHandlerOutput values.
// You can construct a concrete instance of `WebHandlerInput` via:
//
//	WebHandlerArgs{...}
type WebHandlerInput interface {
	pulumi.Input

	ToWebHandlerOutput() WebHandlerOutput
	ToWebHandlerOutputWithContext(context.Context) WebHandlerOutput
}

type WebHandlerArgs struct {
	Compress              pulumi.BoolPtrInput   `pulumi:"compress"`
	Domain                pulumi.StringInput    `pulumi:"domain"`
	DontRedirectPlainHTTP pulumi.BoolPtrInput   `pulumi:"dontRedirectPlainHTTP"`
	Forward               WebForwardPtrInput    `pulumi:"forward"`
	Internal              WebInternalPtrInput   `pulumi:"internal"`
	LogName               pulumi.StringPtrInput `pulumi:"logName"`
	PathRegexp            pulumi.StringInput    `pulumi:"pathRegexp"`
	Redirect              WebRedirectPtrInput   `pulumi:"redirect"`
	Static                WebStaticPtrInput     `pulumi:"static"`
}

func (WebHandlerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebHandler)(nil)).Elem()
}

func (i WebHandlerArgs) ToWebHandlerOutput() WebHandlerOutput {
	return i.ToWebHandlerOutputWithContext(context.Background())
}

func (i WebHandlerArgs) ToWebHandlerOutputWithContext(ctx context.Context) WebHandlerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebHandlerOutput)
}

// WebHandlerArrayInput is an input type that accepts WebHandlerArray and WebHandlerArrayOutput values.
// You can construct a concrete instance of `WebHandlerArrayInput` via:
//
//	WebHandlerArray{ WebHandlerArgs{...} }
type WebHandlerArrayInput interface {
	pulumi.Input

	ToWebHandlerArrayOutput() WebHandlerArrayOutput
	ToWebHandlerArrayOutputWithContext(context.Context) WebHandlerArrayOutput
}

type WebHandlerArray []WebHandlerInput

func (WebHandlerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebHandler)(nil)).Elem()
}

func (i WebHandlerArray) ToWebHandlerArrayOutput() WebHandlerArrayOutput {
	return i.ToWebHandlerArrayOutputWithContext(context.Background())
}

func (i WebHandlerArray) ToWebHandlerArrayOutputWithContext(ctx context.Context) WebHandlerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebHandlerArrayOutput)
}

type WebHandlerOutput struct{ *pulumi.OutputState }

func (WebHandlerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebHandler)(nil)).Elem()
}

func (o WebHandlerOutput) ToWebHandlerOutput() WebHandlerOutput {
	return o
}

func (o WebHandlerOutput) ToWebHandlerOutputWithContext(ctx context.Context) WebHandlerOutput {
	return o
}

func (o WebHandlerOutput) Compress() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v WebHandler) *bool { return v.Compress }).(pulumi.BoolPtrOutput)
}

func (o WebHandlerOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v WebHandler) string { return v.Domain }).(pulumi.StringOutput)
}

func (o WebHandlerOutput) DontRedirectPlainHTTP() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v WebHandler) *bool { return v.DontRedirectPlainHTTP }).(pulumi.BoolPtrOutput)
}

func (o WebHandlerOutput) Forward() WebForwardPtrOutput {
	return o.ApplyT(func(v WebHandler) *WebForward { return v.Forward }).(WebForwardPtrOutput)
}

func (o WebHandlerOutput) Internal() WebInternalPtrOutput {
	return o.ApplyT(func(v WebHandler) *WebInternal { return v.Internal }).(WebInternalPtrOutput)
}

func (o WebHandlerOutput) LogName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebHandler) *string { return v.LogName }).(pulumi.StringPtrOutput)
}

func (o WebHandlerOutput) PathRegexp() pulumi.StringOutput {
	return o.ApplyT(func(v WebHandler) string { return v.PathRegexp }).(pulumi.StringOutput)
}

func (o WebHandlerOutput) Redirect() WebRedirectPtrOutput {
	return o.ApplyT(func(v WebHandler) *WebRedirect { return v.Redirect }).(WebRedirectPtrOutput)
}

func (o WebHandlerOutput) Static() WebStaticPtrOutput {
	return o.ApplyT(func(v WebHandler) *WebStatic { return v.Static }).(WebStaticPtrOutput)
}

type WebHandlerArrayOutput struct{ *pulumi.OutputState }

func (WebHandlerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WebHandler)(nil)).Elem()
}

func (o WebHandlerArrayOutput) ToWebHandlerArrayOutput() WebHandlerArrayOutput {
	return o
}

func (o WebHandlerArrayOutput) ToWebHandlerArrayOutputWithContext(ctx context.Context) WebHandlerArrayOutput {
	return o
}

func (o WebHandlerArrayOutput) Index(i pulumi.IntInput) WebHandlerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) WebHandler {
		return vs[0].([]WebHandler)[vs[1].(int)]
	}).(WebHandlerOutput)
}

type WebInternal struct {
	BasePath string `pulumi:"basePath"`
	Service  string `pulumi:"service"`
}

// WebInternalInput is an input type that accepts WebInternalArgs and WebInternalOutput values.
// You can construct a concrete instance of `WebInternalInput` via:
//
//	WebInternalArgs{...}
type WebInternalInput interface {
	pulumi.Input

	ToWebInternalOutput() WebInternalOutput
	ToWebInternalOutputWithContext(context.Context) WebInternalOutput
}

type WebInternalArgs struct {
	BasePath pulumi.StringInput `pulumi:"basePath"`
	Service  pulumi.StringInput `pulumi:"service"`
}

func (WebInternalArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebInternal)(nil)).Elem()
}

func (i WebInternalArgs) ToWebInternalOutput() WebInternalOutput {
	return i.ToWebInternalOutputWithContext(context.Background())
}

func (i WebInternalArgs) ToWebInternalOutputWithContext(ctx context.Context) WebInternalOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebInternalOutput)
}

func (i WebInternalArgs) ToWebInternalPtrOutput() WebInternalPtrOutput {
	return i.ToWebInternalPtrOutputWithContext(context.Background())
}

func (i WebInternalArgs) ToWebInternalPtrOutputWithContext(ctx context.Context) WebInternalPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebInternalOutput).ToWebInternalPtrOutputWithContext(ctx)
}

// WebInternalPtrInput is an input type that accepts WebInternalArgs, WebInternalPtr and WebInternalPtrOutput values.
// You can construct a concrete instance of `WebInternalPtrInput` via:
//
//	        WebInternalArgs{...}
//
//	or:
//
//	        nil
type WebInternalPtrInput interface {
	pulumi.Input

	ToWebInternalPtrOutput() WebInternalPtrOutput
	ToWebInternalPtrOutputWithContext(context.Context) WebInternalPtrOutput
}

type webInternalPtrType WebInternalArgs

func WebInternalPtr(v *WebInternalArgs) WebInternalPtrInput {
	return (*webInternalPtrType)(v)
}

func (*webInternalPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebInternal)(nil)).Elem()
}

func (i *webInternalPtrType) ToWebInternalPtrOutput() WebInternalPtrOutput {
	return i.ToWebInternalPtrOutputWithContext(context.Background())
}

func (i *webInternalPtrType) ToWebInternalPtrOutputWithContext(ctx context.Context) WebInternalPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebInternalPtrOutput)
}

type WebInternalOutput struct{ *pulumi.OutputState }

func (WebInternalOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebInternal)(nil)).Elem()
}

func (o WebInternalOutput) ToWebInternalOutput() WebInternalOutput {
	return o
}

func (o WebInternalOutput) ToWebInternalOutputWithContext(ctx context.Context) WebInternalOutput {
	return o
}

func (o WebInternalOutput) ToWebInternalPtrOutput() WebInternalPtrOutput {
	return o.ToWebInternalPtrOutputWithContext(context.Background())
}

func (o WebInternalOutput) ToWebInternalPtrOutputWithContext(ctx context.Context) WebInternalPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebInternal) *WebInternal {
		return &v
	}).(WebInternalPtrOutput)
}

func (o WebInternalOutput) BasePath() pulumi.StringOutput {
	return o.ApplyT(func(v WebInternal) string { return v.BasePath }).(pulumi.StringOutput)
}

func (o WebInternalOutput) Service() pulumi.StringOutput {
	return o.ApplyT(func(v WebInternal) string { return v.Service }).(pulumi.StringOutput)
}

type WebInternalPtrOutput struct{ *pulumi.OutputState }

func (WebInternalPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebInternal)(nil)).Elem()
}

func (o WebInternalPtrOutput) ToWebInternalPtrOutput() WebInternalPtrOutput {
	return o
}

func (o WebInternalPtrOutput) ToWebInternalPtrOutputWithContext(ctx context.Context) WebInternalPtrOutput {
	return o
}

func (o WebInternalPtrOutput) Elem() WebInternalOutput {
	return o.ApplyT(func(v *WebInternal) WebInternal {
		if v != nil {
			return *v
		}
		var ret WebInternal
		return ret
	}).(WebInternalOutput)
}

func (o WebInternalPtrOutput) BasePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebInternal) *string {
		if v == nil {
			return nil
		}
		return &v.BasePath
	}).(pulumi.StringPtrOutput)
}

func (o WebInternalPtrOutput) Service() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebInternal) *string {
		if v == nil {
			return nil
		}
		return &v.Service
	}).(pulumi.StringPtrOutput)
}

type WebRedirect struct {
	BaseUrl        *string `pulumi:"baseUrl"`
	OrigPathRegexp *string `pulumi:"origPathRegexp"`
	ReplacePath    *string `pulumi:"replacePath"`
	StatusCode     *int    `pulumi:"statusCode"`
}

// WebRedirectInput is an input type that accepts WebRedirectArgs and WebRedirectOutput values.
// You can construct a concrete instance of `WebRedirectInput` via:
//
//	WebRedirectArgs{...}
type WebRedirectInput interface {
	pulumi.Input

	ToWebRedirectOutput() WebRedirectOutput
	ToWebRedirectOutputWithContext(context.Context) WebRedirectOutput
}

type WebRedirectArgs struct {
	BaseUrl        pulumi.StringPtrInput `pulumi:"baseUrl"`
	OrigPathRegexp pulumi.StringPtrInput `pulumi:"origPathRegexp"`
	ReplacePath    pulumi.StringPtrInput `pulumi:"replacePath"`
	StatusCode     pulumi.IntPtrInput    `pulumi:"statusCode"`
}

func (WebRedirectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebRedirect)(nil)).Elem()
}

func (i WebRedirectArgs) ToWebRedirectOutput() WebRedirectOutput {
	return i.ToWebRedirectOutputWithContext(context.Background())
}

func (i WebRedirectArgs) ToWebRedirectOutputWithContext(ctx context.Context) WebRedirectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebRedirectOutput)
}

func (i WebRedirectArgs) ToWebRedirectPtrOutput() WebRedirectPtrOutput {
	return i.ToWebRedirectPtrOutputWithContext(context.Background())
}

func (i WebRedirectArgs) ToWebRedirectPtrOutputWithContext(ctx context.Context) WebRedirectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebRedirectOutput).ToWebRedirectPtrOutputWithContext(ctx)
}

// WebRedirectPtrInput is an input type that accepts WebRedirectArgs, WebRedirectPtr and WebRedirectPtrOutput values.
// You can construct a concrete instance of `WebRedirectPtrInput` via:
//
//	        WebRedirectArgs{...}
//
//	or:
//
//	        nil
type WebRedirectPtrInput interface {
	pulumi.Input

	ToWebRedirectPtrOutput() WebRedirectPtrOutput
	ToWebRedirectPtrOutputWithContext(context.Context) WebRedirectPtrOutput
}

type webRedirectPtrType WebRedirectArgs

func WebRedirectPtr(v *WebRedirectArgs) WebRedirectPtrInput {
	return (*webRedirectPtrType)(v)
}

func (*webRedirectPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebRedirect)(nil)).Elem()
}

func (i *webRedirectPtrType) ToWebRedirectPtrOutput() WebRedirectPtrOutput {
	return i.ToWebRedirectPtrOutputWithContext(context.Background())
}

func (i *webRedirectPtrType) ToWebRedirectPtrOutputWithContext(ctx context.Context) WebRedirectPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebRedirectPtrOutput)
}

type WebRedirectOutput struct{ *pulumi.OutputState }

func (WebRedirectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebRedirect)(nil)).Elem()
}

func (o WebRedirectOutput) ToWebRedirectOutput() WebRedirectOutput {
	return o
}

func (o WebRedirectOutput) ToWebRedirectOutputWithContext(ctx context.Context) WebRedirectOutput {
	return o
}

func (o WebRedirectOutput) ToWebRedirectPtrOutput() WebRedirectPtrOutput {
	return o.ToWebRedirectPtrOutputWithContext(context.Background())
}

func (o WebRedirectOutput) ToWebRedirectPtrOutputWithContext(ctx context.Context) WebRedirectPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebRedirect) *WebRedirect {
		return &v
	}).(WebRedirectPtrOutput)
}

func (o WebRedirectOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebRedirect) *string { return v.BaseUrl }).(pulumi.StringPtrOutput)
}

func (o WebRedirectOutput) OrigPathRegexp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebRedirect) *string { return v.OrigPathRegexp }).(pulumi.StringPtrOutput)
}

func (o WebRedirectOutput) ReplacePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebRedirect) *string { return v.ReplacePath }).(pulumi.StringPtrOutput)
}

func (o WebRedirectOutput) StatusCode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v WebRedirect) *int { return v.StatusCode }).(pulumi.IntPtrOutput)
}

type WebRedirectPtrOutput struct{ *pulumi.OutputState }

func (WebRedirectPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebRedirect)(nil)).Elem()
}

func (o WebRedirectPtrOutput) ToWebRedirectPtrOutput() WebRedirectPtrOutput {
	return o
}

func (o WebRedirectPtrOutput) ToWebRedirectPtrOutputWithContext(ctx context.Context) WebRedirectPtrOutput {
	return o
}

func (o WebRedirectPtrOutput) Elem() WebRedirectOutput {
	return o.ApplyT(func(v *WebRedirect) WebRedirect {
		if v != nil {
			return *v
		}
		var ret WebRedirect
		return ret
	}).(WebRedirectOutput)
}

func (o WebRedirectPtrOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebRedirect) *string {
		if v == nil {
			return nil
		}
		return v.BaseUrl
	}).(pulumi.StringPtrOutput)
}

func (o WebRedirectPtrOutput) OrigPathRegexp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebRedirect) *string {
		if v == nil {
			return nil
		}
		return v.OrigPathRegexp
	}).(pulumi.StringPtrOutput)
}

func (o WebRedirectPtrOutput) ReplacePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebRedirect) *string {
		if v == nil {
			return nil
		}
		return v.ReplacePath
	}).(pulumi.StringPtrOutput)
}

func (o WebRedirectPtrOutput) StatusCode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *WebRedirect) *int {
		if v == nil {
			return nil
		}
		return v.StatusCode
	}).(pulumi.IntPtrOutput)
}

type WebStatic struct {
	ContinueNotFound *bool             `pulumi:"continueNotFound"`
	ListFiles        *bool             `pulumi:"listFiles"`
	ResponseHeaders  map[string]string `pulumi:"responseHeaders"`
	Root             string            `pulumi:"root"`
	StripPrefix      *string           `pulumi:"stripPrefix"`
}

// WebStaticInput is an input type that accepts WebStaticArgs and WebStaticOutput values.
// You can construct a concrete instance of `WebStaticInput` via:
//
//	WebStaticArgs{...}
type WebStaticInput interface {
	pulumi.Input

	ToWebStaticOutput() WebStaticOutput
	ToWebStaticOutputWithContext(context.Context) WebStaticOutput
}

type WebStaticArgs struct {
	ContinueNotFound pulumi.BoolPtrInput   `pulumi:"continueNotFound"`
	ListFiles        pulumi.BoolPtrInput   `pulumi:"listFiles"`
	ResponseHeaders  pulumi.StringMapInput `pulumi:"responseHeaders"`
	Root             pulumi.StringInput    `pulumi:"root"`
	StripPrefix      pulumi.StringPtrInput `pulumi:"stripPrefix"`
}

func (WebStaticArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WebStatic)(nil)).Elem()
}

func (i WebStaticArgs) ToWebStaticOutput() WebStaticOutput {
	return i.ToWebStaticOutputWithContext(context.Background())
}

func (i WebStaticArgs) ToWebStaticOutputWithContext(ctx context.Context) WebStaticOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebStaticOutput)
}

func (i WebStaticArgs) ToWebStaticPtrOutput() WebStaticPtrOutput {
	return i.ToWebStaticPtrOutputWithContext(context.Background())
}

func (i WebStaticArgs) ToWebStaticPtrOutputWithContext(ctx context.Context) WebStaticPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebStaticOutput).ToWebStaticPtrOutputWithContext(ctx)
}

// WebStaticPtrInput is an input type that accepts WebStaticArgs, WebStaticPtr and WebStaticPtrOutput values.
// You can construct a concrete instance of `WebStaticPtrInput` via:
//
//	        WebStaticArgs{...}
//
//	or:
//
//	        nil
type WebStaticPtrInput interface {
	pulumi.Input

	ToWebStaticPtrOutput() WebStaticPtrOutput
	ToWebStaticPtrOutputWithContext(context.Context) WebStaticPtrOutput
}

type webStaticPtrType WebStaticArgs

func WebStaticPtr(v *WebStaticArgs) WebStaticPtrInput {
	return (*webStaticPtrType)(v)
}

func (*webStaticPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WebStatic)(nil)).Elem()
}

func (i *webStaticPtrType) ToWebStaticPtrOutput() WebStaticPtrOutput {
	return i.ToWebStaticPtrOutputWithContext(context.Background())
}

func (i *webStaticPtrType) ToWebStaticPtrOutputWithContext(ctx context.Context) WebStaticPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebStaticPtrOutput)
}

type WebStaticOutput struct{ *pulumi.OutputState }

func (WebStaticOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WebStatic)(nil)).Elem()
}

func (o WebStaticOutput) ToWebStaticOutput() WebStaticOutput {
	return o
}

func (o WebStaticOutput) ToWebStaticOutputWithContext(ctx context.Context) WebStaticOutput {
	return o
}

func (o WebStaticOutput) ToWebStaticPtrOutput() WebStaticPtrOutput {
	return o.ToWebStaticPtrOutputWithContext(context.Background())
}

func (o WebStaticOutput) ToWebStaticPtrOutputWithContext(ctx context.Context) WebStaticPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WebStatic) *WebStatic {
		return &v
	}).(WebStaticPtrOutput)
}

func (o WebStaticOutput) ContinueNotFound() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v WebStatic) *bool { return v.ContinueNotFound }).(pulumi.BoolPtrOutput)
}

func (o WebStaticOutput) ListFiles() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v WebStatic) *bool { return v.ListFiles }).(pulumi.BoolPtrOutput)
}

func (o WebStaticOutput) ResponseHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v WebStatic) map[string]string { return v.ResponseHeaders }).(pulumi.StringMapOutput)
}

func (o WebStaticOutput) Root() pulumi.StringOutput {
	return o.ApplyT(func(v WebStatic) string { return v.Root }).(pulumi.StringOutput)
}

func (o WebStaticOutput) StripPrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WebStatic) *string { return v.StripPrefix }).(pulumi.StringPtrOutput)
}

type WebStaticPtrOutput struct{ *pulumi.OutputState }

func (WebStaticPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebStatic)(nil)).Elem()
}

func (o WebStaticPtrOutput) ToWebStaticPtrOutput() WebStaticPtrOutput {
	return o
}

func (o WebStaticPtrOutput) ToWebStaticPtrOutputWithContext(ctx context.Context) WebStaticPtrOutput {
	return o
}

func (o WebStaticPtrOutput) Elem() WebStaticOutput {
	return o.ApplyT(func(v *WebStatic) WebStatic {
		if v != nil {
			return *v
		}
		var ret WebStatic
		return ret
	}).(WebStaticOutput)
}

func (o WebStaticPtrOutput) ContinueNotFound() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WebStatic) *bool {
		if v == nil {
			return nil
		}
		return v.ContinueNotFound
	}).(pulumi.BoolPtrOutput)
}

func (o WebStaticPtrOutput) ListFiles() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WebStatic) *bool {
		if v == nil {
			return nil
		}
		return v.ListFiles
	}).(pulumi.BoolPtrOutput)
}

func (o WebStaticPtrOutput) ResponseHeaders() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WebStatic) map[string]string {
		if v == nil {
			return nil
		}
		return v.ResponseHeaders
	}).(pulumi.StringMapOutput)
}

func (o WebStaticPtrOutput) Root() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebStatic) *string {
		if v == nil {
			return nil
		}
		return &v.Root
	}).(pulumi.StringPtrOutput)
}

func (o WebStaticPtrOutput) StripPrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebStatic) *string {
		if v == nil {
			return nil
		}
		return v.StripPrefix
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountRouteInput)(nil)).Elem(), AccountRouteArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountRouteArrayInput)(nil)).Elem(), AccountRouteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainLocalpartConfigInput)(nil)).Elem(), DomainLocalpartConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainLocalpartConfigPtrInput)(nil)).Elem(), DomainLocalpartConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMtaStsInput)(nil)).Elem(), DomainMtaStsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMtaStsPtrInput)(nil)).Elem(), DomainMtaStsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainReportAddressInput)(nil)).Elem(), DomainReportAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainReportAddressPtrInput)(nil)).Elem(), DomainReportAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainSieveInput)(nil)).Elem(), DomainSieveArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainSievePtrInput)(nil)).Elem(), DomainSieveArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebDomainRedirectInput)(nil)).Elem(), WebDomainRedirectArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebDomainRedirectArrayInput)(nil)).Elem(), WebDomainRedirectArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebForwardInput)(nil)).Elem(), WebForwardArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebForwardPtrInput)(nil)).Elem(), WebForwardArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebHandlerInput)(nil)).Elem(), WebHandlerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebHandlerArrayInput)(nil)).Elem(), WebHandlerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebInternalInput)(nil)).Elem(), WebInternalArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebInternalPtrInput)(nil)).Elem(), WebInternalArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebRedirectInput)(nil)).Elem(), WebRedirectArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebRedirectPtrInput)(nil)).Elem(), WebRedirectArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebStaticInput)(nil)).Elem(), WebStaticArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebStaticPtrInput)(nil)).Elem(), WebStaticArgs{})
	pulumi.RegisterOutputType(AccountRouteOutput{})
	pulumi.RegisterOutputType(AccountRouteArrayOutput{})
	pulumi.RegisterOutputType(DkimDNSRecordOutput{})
	pulumi.RegisterOutputType(DkimDNSRecordArrayOutput{})
	pulumi.RegisterOutputType(DomainLocalpartConfigOutput{})
	pulumi.RegisterOutputType(DomainLocalpartConfigPtrOutput{})
	pulumi.RegisterOutputType(DomainMtaStsOutput{})
	pulumi.RegisterOutputType(DomainMtaStsPtrOutput{})
	pulumi.RegisterOutputType(DomainReportAddressOutput{})
	pulumi.RegisterOutputType(DomainReportAddressPtrOutput{})
	pulumi.RegisterOutputType(DomainSieveOutput{})
	pulumi.RegisterOutputType(DomainSievePtrOutput{})
	pulumi.RegisterOutputType(WebDomainRedirectOutput{})
	pulumi.RegisterOutputType(WebDomainRedirectArrayOutput{})
	pulumi.RegisterOutputType(WebForwardOutput{})
	pulumi.RegisterOutputType(WebForwardPtrOutput{})
	pulumi.RegisterOutputType(WebHandlerOutput{})
	pulumi.RegisterOutputType(WebHandlerArrayOutput{})
	pulumi.RegisterOutputType(WebInternalOutput{})
	pulumi.RegisterOutputType(WebInternalPtrOutput{})
	pulumi.RegisterOutputType(WebRedirectOutput{})
	pulumi.RegisterOutputType(WebRedirectPtrOutput{})
	pulumi.RegisterOutputType(WebStaticOutput{})
	pulumi.RegisterOutputType(WebStaticPtrOutput{})
}
