// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AccountRoute struct {
	FromDomains     []string `pulumi:"fromDomains"`
	MinimumAttempts *int     `pulumi:"minimumAttempts"`
	ToDomains       []string `pulumi:"toDomains"`
	Transport       string   `pulumi:"transport"`
}

// AccountRouteInput is an input type that accepts AccountRouteArgs and AccountRouteOutput values.
// You can construct a concrete instance of `AccountRouteInput` via:
//
//	AccountRouteArgs{...}
type AccountRouteInput interface {
	pulumi.Input

	ToAccountRouteOutput() AccountRouteOutput
	ToAccountRouteOutputWithContext(context.Context) AccountRouteOutput
}

type AccountRouteArgs struct {
	FromDomains     pulumi.StringArrayInput `pulumi:"fromDomains"`
	MinimumAttempts pulumi.IntPtrInput      `pulumi:"minimumAttempts"`
	ToDomains       pulumi.StringArrayInput `pulumi:"toDomains"`
	Transport       pulumi.StringInput      `pulumi:"transport"`
}

func (AccountRouteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AccountRoute)(nil)).Elem()
}

func (i AccountRouteArgs) ToAccountRouteOutput() AccountRouteOutput {
	return i.ToAccountRouteOutputWithContext(context.Background())
}

func (i AccountRouteArgs) ToAccountRouteOutputWithContext(ctx context.Context) AccountRouteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountRouteOutput)
}

// AccountRouteArrayInput is an input type that accepts AccountRouteArray and AccountRouteArrayOutput values.
// You can construct a concrete instance of `AccountRouteArrayInput` via:
//
//	AccountRouteArray{ AccountRouteArgs{...} }
type AccountRouteArrayInput interface {
	pulumi.Input

	ToAccountRouteArrayOutput() AccountRouteArrayOutput
	ToAccountRouteArrayOutputWithContext(context.Context) AccountRouteArrayOutput
}

type AccountRouteArray []AccountRouteInput

func (AccountRouteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccountRoute)(nil)).Elem()
}

func (i AccountRouteArray) ToAccountRouteArrayOutput() AccountRouteArrayOutput {
	return i.ToAccountRouteArrayOutputWithContext(context.Background())
}

func (i AccountRouteArray) ToAccountRouteArrayOutputWithContext(ctx context.Context) AccountRouteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountRouteArrayOutput)
}

type AccountRouteOutput struct{ *pulumi.OutputState }

func (AccountRouteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AccountRoute)(nil)).Elem()
}

func (o AccountRouteOutput) ToAccountRouteOutput() AccountRouteOutput {
	return o
}

func (o AccountRouteOutput) ToAccountRouteOutputWithContext(ctx context.Context) AccountRouteOutput {
	return o
}

func (o AccountRouteOutput) FromDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AccountRoute) []string { return v.FromDomains }).(pulumi.StringArrayOutput)
}

func (o AccountRouteOutput) MinimumAttempts() pulumi.IntPtrOutput {
	return o.ApplyT(func(v AccountRoute) *int { return v.MinimumAttempts }).(pulumi.IntPtrOutput)
}

func (o AccountRouteOutput) ToDomains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AccountRoute) []string { return v.ToDomains }).(pulumi.StringArrayOutput)
}

func (o AccountRouteOutput) Transport() pulumi.StringOutput {
	return o.ApplyT(func(v AccountRoute) string { return v.Transport }).(pulumi.StringOutput)
}

type AccountRouteArrayOutput struct{ *pulumi.OutputState }

func (AccountRouteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AccountRoute)(nil)).Elem()
}

func (o AccountRouteArrayOutput) ToAccountRouteArrayOutput() AccountRouteArrayOutput {
	return o
}

func (o AccountRouteArrayOutput) ToAccountRouteArrayOutputWithContext(ctx context.Context) AccountRouteArrayOutput {
	return o
}

func (o AccountRouteArrayOutput) Index(i pulumi.IntInput) AccountRouteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AccountRoute {
		return vs[0].([]AccountRoute)[vs[1].(int)]
	}).(AccountRouteOutput)
}

type DkimDNSRecord struct {
	// DKIM selector (the label before "._domainkey").
	Selector string `pulumi:"selector"`
	// Full DKIM TXT record value, e.g. "v=DKIM1;h=sha256;p=...".
	Txt string `pulumi:"txt"`
}

type DkimDNSRecordOutput struct{ *pulumi.OutputState }

func (DkimDNSRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DkimDNSRecord)(nil)).Elem()
}

func (o DkimDNSRecordOutput) ToDkimDNSRecordOutput() DkimDNSRecordOutput {
	return o
}

func (o DkimDNSRecordOutput) ToDkimDNSRecordOutputWithContext(ctx context.Context) DkimDNSRecordOutput {
	return o
}

// DKIM selector (the label before "._domainkey").
func (o DkimDNSRecordOutput) Selector() pulumi.StringOutput {
	return o.ApplyT(func(v DkimDNSRecord) string { return v.Selector }).(pulumi.StringOutput)
}

// Full DKIM TXT record value, e.g. "v=DKIM1;h=sha256;p=...".
func (o DkimDNSRecordOutput) Txt() pulumi.StringOutput {
	return o.ApplyT(func(v DkimDNSRecord) string { return v.Txt }).(pulumi.StringOutput)
}

type DkimDNSRecordArrayOutput struct{ *pulumi.OutputState }

func (DkimDNSRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DkimDNSRecord)(nil)).Elem()
}

func (o DkimDNSRecordArrayOutput) ToDkimDNSRecordArrayOutput() DkimDNSRecordArrayOutput {
	return o
}

func (o DkimDNSRecordArrayOutput) ToDkimDNSRecordArrayOutputWithContext(ctx context.Context) DkimDNSRecordArrayOutput {
	return o
}

func (o DkimDNSRecordArrayOutput) Index(i pulumi.IntInput) DkimDNSRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DkimDNSRecord {
		return vs[0].([]DkimDNSRecord)[vs[1].(int)]
	}).(DkimDNSRecordOutput)
}

type DomainLocalpartConfig struct {
	// Whether localparts are case-sensitive.
	CaseSensitive *bool `pulumi:"caseSensitive"`
	// Separators used for sub-addressing, e.g. "+".
	CatchallSeparators []string `pulumi:"catchallSeparators"`
}

// DomainLocalpartConfigInput is an input type that accepts DomainLocalpartConfigArgs and DomainLocalpartConfigOutput values.
// You can construct a concrete instance of `DomainLocalpartConfigInput` via:
//
//	DomainLocalpartConfigArgs{...}
type DomainLocalpartConfigInput interface {
	pulumi.Input

	ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput
	ToDomainLocalpartConfigOutputWithContext(context.Context) DomainLocalpartConfigOutput
}

type DomainLocalpartConfigArgs struct {
	// Whether localparts are case-sensitive.
	CaseSensitive pulumi.BoolPtrInput `pulumi:"caseSensitive"`
	// Separators used for sub-addressing, e.g. "+".
	CatchallSeparators pulumi.StringArrayInput `pulumi:"catchallSeparators"`
}

func (DomainLocalpartConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainLocalpartConfig)(nil)).Elem()
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput {
	return i.ToDomainLocalpartConfigOutputWithContext(context.Background())
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigOutputWithContext(ctx context.Context) DomainLocalpartConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigOutput)
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return i.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (i DomainLocalpartConfigArgs) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigOutput).ToDomainLocalpartConfigPtrOutputWithContext(ctx)
}

// DomainLocalpartConfigPtrInput is an input type that accepts DomainLocalpartConfigArgs, DomainLocalpartConfigPtr and DomainLocalpartConfigPtrOutput values.
// You can construct a concrete instance of `DomainLocalpartConfigPtrInput` via:
//
//	        DomainLocalpartConfigArgs{...}
//
//	or:
//
//	        nil
type DomainLocalpartConfigPtrInput interface {
	pulumi.Input

	ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput
	ToDomainLocalpartConfigPtrOutputWithContext(context.Context) DomainLocalpartConfigPtrOutput
}

type domainLocalpartConfigPtrType DomainLocalpartConfigArgs

func DomainLocalpartConfigPtr(v *DomainLocalpartConfigArgs) DomainLocalpartConfigPtrInput {
	return (*domainLocalpartConfigPtrType)(v)
}

func (*domainLocalpartConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainLocalpartConfig)(nil)).Elem()
}

func (i *domainLocalpartConfigPtrType) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return i.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (i *domainLocalpartConfigPtrType) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainLocalpartConfigPtrOutput)
}

type DomainLocalpartConfigOutput struct{ *pulumi.OutputState }

func (DomainLocalpartConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainLocalpartConfig)(nil)).Elem()
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigOutput() DomainLocalpartConfigOutput {
	return o
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigOutputWithContext(ctx context.Context) DomainLocalpartConfigOutput {
	return o
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return o.ToDomainLocalpartConfigPtrOutputWithContext(context.Background())
}

func (o DomainLocalpartConfigOutput) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainLocalpartConfig) *DomainLocalpartConfig {
		return &v
	}).(DomainLocalpartConfigPtrOutput)
}

// Whether localparts are case-sensitive.
func (o DomainLocalpartConfigOutput) CaseSensitive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DomainLocalpartConfig) *bool { return v.CaseSensitive }).(pulumi.BoolPtrOutput)
}

// Separators used for sub-addressing, e.g. "+".
func (o DomainLocalpartConfigOutput) CatchallSeparators() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainLocalpartConfig) []string { return v.CatchallSeparators }).(pulumi.StringArrayOutput)
}

type DomainLocalpartConfigPtrOutput struct{ *pulumi.OutputState }

func (DomainLocalpartConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainLocalpartConfig)(nil)).Elem()
}

func (o DomainLocalpartConfigPtrOutput) ToDomainLocalpartConfigPtrOutput() DomainLocalpartConfigPtrOutput {
	return o
}

func (o DomainLocalpartConfigPtrOutput) ToDomainLocalpartConfigPtrOutputWithContext(ctx context.Context) DomainLocalpartConfigPtrOutput {
	return o
}

func (o DomainLocalpartConfigPtrOutput) Elem() DomainLocalpartConfigOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) DomainLocalpartConfig {
		if v != nil {
			return *v
		}
		var ret DomainLocalpartConfig
		return ret
	}).(DomainLocalpartConfigOutput)
}

// Whether localparts are case-sensitive.
func (o DomainLocalpartConfigPtrOutput) CaseSensitive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) *bool {
		if v == nil {
			return nil
		}
		return v.CaseSensitive
	}).(pulumi.BoolPtrOutput)
}

// Separators used for sub-addressing, e.g. "+".
func (o DomainLocalpartConfigPtrOutput) CatchallSeparators() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DomainLocalpartConfig) []string {
		if v == nil {
			return nil
		}
		return v.CatchallSeparators
	}).(pulumi.StringArrayOutput)
}

type DomainMtaSts struct {
	// Policy lifetime in seconds.
	MaxAgeSeconds int `pulumi:"maxAgeSeconds"`
	// MTA-STS mode: "enforce", "testing" or "none".
	Mode string `pulumi:"mode"`
	// Permitted MX host patterns.
	Mx []string `pulumi:"mx"`
	// Policy version identifier; change it to signal an updated policy to senders.
	PolicyId string `pulumi:"policyId"`
}

// DomainMtaStsInput is an input type that accepts DomainMtaStsArgs and DomainMtaStsOutput values.
// You can construct a concrete instance of `DomainMtaStsInput` via:
//
//	DomainMtaStsArgs{...}
type DomainMtaStsInput interface {
	pulumi.Input

	ToDomainMtaStsOutput() DomainMtaStsOutput
	ToDomainMtaStsOutputWithContext(context.Context) DomainMtaStsOutput
}

type DomainMtaStsArgs struct {
	// Policy lifetime in seconds.
	MaxAgeSeconds pulumi.IntInput `pulumi:"maxAgeSeconds"`
	// MTA-STS mode: "enforce", "testing" or "none".
	Mode pulumi.StringInput `pulumi:"mode"`
	// Permitted MX host patterns.
	Mx pulumi.StringArrayInput `pulumi:"mx"`
	// Policy version identifier; change it to signal an updated policy to senders.
	PolicyId pulumi.StringInput `pulumi:"policyId"`
}

func (DomainMtaStsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainMtaSts)(nil)).Elem()
}

func (i DomainMtaStsArgs) ToDomainMtaStsOutput() DomainMtaStsOutput {
	return i.ToDomainMtaStsOutputWithContext(context.Background())
}

func (i DomainMtaStsArgs) ToDomainMtaStsOutputWithContext(ctx context.Context) DomainMtaStsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsOutput)
}

func (i DomainMtaStsArgs) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return i.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (i DomainMtaStsArgs) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsOutput).ToDomainMtaStsPtrOutputWithContext(ctx)
}

// DomainMtaStsPtrInput is an input type that accepts DomainMtaStsArgs, DomainMtaStsPtr and DomainMtaStsPtrOutput values.
// You can construct a concrete instance of `DomainMtaStsPtrInput` via:
//
//	        DomainMtaStsArgs{...}
//
//	or:
//
//	        nil
type DomainMtaStsPtrInput interface {
	pulumi.Input

	ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput
	ToDomainMtaStsPtrOutputWithContext(context.Context) DomainMtaStsPtrOutput
}

type domainMtaStsPtrType DomainMtaStsArgs

func DomainMtaStsPtr(v *DomainMtaStsArgs) DomainMtaStsPtrInput {
	return (*domainMtaStsPtrType)(v)
}

func (*domainMtaStsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainMtaSts)(nil)).Elem()
}

func (i *domainMtaStsPtrType) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return i.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (i *domainMtaStsPtrType) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMtaStsPtrOutput)
}

type DomainMtaStsOutput struct{ *pulumi.OutputState }

func (DomainMtaStsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainMtaSts)(nil)).Elem()
}

func (o DomainMtaStsOutput) ToDomainMtaStsOutput() DomainMtaStsOutput {
	return o
}

func (o DomainMtaStsOutput) ToDomainMtaStsOutputWithContext(ctx context.Context) DomainMtaStsOutput {
	return o
}

func (o DomainMtaStsOutput) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return o.ToDomainMtaStsPtrOutputWithContext(context.Background())
}

func (o DomainMtaStsOutput) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainMtaSts) *DomainMtaSts {
		return &v
	}).(DomainMtaStsPtrOutput)
}

// Policy lifetime in seconds.
func (o DomainMtaStsOutput) MaxAgeSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v DomainMtaSts) int { return v.MaxAgeSeconds }).(pulumi.IntOutput)
}

// MTA-STS mode: "enforce", "testing" or "none".
func (o DomainMtaStsOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v DomainMtaSts) string { return v.Mode }).(pulumi.StringOutput)
}

// Permitted MX host patterns.
func (o DomainMtaStsOutput) Mx() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DomainMtaSts) []string { return v.Mx }).(pulumi.StringArrayOutput)
}

// Policy version identifier; change it to signal an updated policy to senders.
func (o DomainMtaStsOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v DomainMtaSts) string { return v.PolicyId }).(pulumi.StringOutput)
}

type DomainMtaStsPtrOutput struct{ *pulumi.OutputState }

func (DomainMtaStsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainMtaSts)(nil)).Elem()
}

func (o DomainMtaStsPtrOutput) ToDomainMtaStsPtrOutput() DomainMtaStsPtrOutput {
	return o
}

func (o DomainMtaStsPtrOutput) ToDomainMtaStsPtrOutputWithContext(ctx context.Context) DomainMtaStsPtrOutput {
	return o
}

func (o DomainMtaStsPtrOutput) Elem() DomainMtaStsOutput {
	return o.ApplyT(func(v *DomainMtaSts) DomainMtaSts {
		if v != nil {
			return *v
		}
		var ret DomainMtaSts
		return ret
	}).(DomainMtaStsOutput)
}

// Policy lifetime in seconds.
func (o DomainMtaStsPtrOutput) MaxAgeSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *int {
		if v == nil {
			return nil
		}
		return &v.MaxAgeSeconds
	}).(pulumi.IntPtrOutput)
}

// MTA-STS mode: "enforce", "testing" or "none".
func (o DomainMtaStsPtrOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *string {
		if v == nil {
			return nil
		}
		return &v.Mode
	}).(pulumi.StringPtrOutput)
}

// Permitted MX host patterns.
func (o DomainMtaStsPtrOutput) Mx() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DomainMtaSts) []string {
		if v == nil {
			return nil
		}
		return v.Mx
	}).(pulumi.StringArrayOutput)
}

// Policy version identifier; change it to signal an updated policy to senders.
func (o DomainMtaStsPtrOutput) PolicyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainMtaSts) *string {
		if v == nil {
			return nil
		}
		return &v.PolicyId
	}).(pulumi.StringPtrOutput)
}

type DomainReportAddress struct {
	// Mox account that receives the reports.
	Account string `pulumi:"account"`
	// Report destination domain. Empty means the domain itself.
	Domain *string `pulumi:"domain"`
	// Local part of the report destination address.
	Localpart string `pulumi:"localpart"`
	// Destination mailbox within the account.
	Mailbox *string `pulumi:"mailbox"`
}

// DomainReportAddressInput is an input type that accepts DomainReportAddressArgs and DomainReportAddressOutput values.
// You can construct a concrete instance of `DomainReportAddressInput` via:
//
//	DomainReportAddressArgs{...}
type DomainReportAddressInput interface {
	pulumi.Input

	ToDomainReportAddressOutput() DomainReportAddressOutput
	ToDomainReportAddressOutputWithContext(context.Context) DomainReportAddressOutput
}

type DomainReportAddressArgs struct {
	// Mox account that receives the reports.
	Account pulumi.StringInput `pulumi:"account"`
	// Report destination domain. Empty means the domain itself.
	Domain pulumi.StringPtrInput `pulumi:"domain"`
	// Local part of the report destination address.
	Localpart pulumi.StringInput `pulumi:"localpart"`
	// Destination mailbox within the account.
	Mailbox pulumi.StringPtrInput `pulumi:"mailbox"`
}

func (DomainReportAddressArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainReportAddress)(nil)).Elem()
}

func (i DomainReportAddressArgs) ToDomainReportAddressOutput() DomainReportAddressOutput {
	return i.ToDomainReportAddressOutputWithContext(context.Background())
}

func (i DomainReportAddressArgs) ToDomainReportAddressOutputWithContext(ctx context.Context) DomainReportAddressOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressOutput)
}

func (i DomainReportAddressArgs) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return i.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (i DomainReportAddressArgs) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressOutput).ToDomainReportAddressPtrOutputWithContext(ctx)
}

// DomainReportAddressPtrInput is an input type that accepts DomainReportAddressArgs, DomainReportAddressPtr and DomainReportAddressPtrOutput values.
// You can construct a concrete instance of `DomainReportAddressPtrInput` via:
//
//	        DomainReportAddressArgs{...}
//
//	or:
//
//	        nil
type DomainReportAddressPtrInput interface {
	pulumi.Input

	ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput
	ToDomainReportAddressPtrOutputWithContext(context.Context) DomainReportAddressPtrOutput
}

type domainReportAddressPtrType DomainReportAddressArgs

func DomainReportAddressPtr(v *DomainReportAddressArgs) DomainReportAddressPtrInput {
	return (*domainReportAddressPtrType)(v)
}

func (*domainReportAddressPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainReportAddress)(nil)).Elem()
}

func (i *domainReportAddressPtrType) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return i.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (i *domainReportAddressPtrType) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainReportAddressPtrOutput)
}

type DomainReportAddressOutput struct{ *pulumi.OutputState }

func (DomainReportAddressOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainReportAddress)(nil)).Elem()
}

func (o DomainReportAddressOutput) ToDomainReportAddressOutput() DomainReportAddressOutput {
	return o
}

func (o DomainReportAddressOutput) ToDomainReportAddressOutputWithContext(ctx context.Context) DomainReportAddressOutput {
	return o
}

func (o DomainReportAddressOutput) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return o.ToDomainReportAddressPtrOutputWithContext(context.Background())
}

func (o DomainReportAddressOutput) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainReportAddress) *DomainReportAddress {
		return &v
	}).(DomainReportAddressPtrOutput)
}

// Mox account that receives the reports.
func (o DomainReportAddressOutput) Account() pulumi.StringOutput {
	return o.ApplyT(func(v DomainReportAddress) string { return v.Account }).(pulumi.StringOutput)
}

// Report destination domain. Empty means the domain itself.
func (o DomainReportAddressOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainReportAddress) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

// Local part of the report destination address.
func (o DomainReportAddressOutput) Localpart() pulumi.StringOutput {
	return o.ApplyT(func(v DomainReportAddress) string { return v.Localpart }).(pulumi.StringOutput)
}

// Destination mailbox within the account.
func (o DomainReportAddressOutput) Mailbox() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainReportAddress) *string { return v.Mailbox }).(pulumi.StringPtrOutput)
}

type DomainReportAddressPtrOutput struct{ *pulumi.OutputState }

func (DomainReportAddressPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainReportAddress)(nil)).Elem()
}

func (o DomainReportAddressPtrOutput) ToDomainReportAddressPtrOutput() DomainReportAddressPtrOutput {
	return o
}

func (o DomainReportAddressPtrOutput) ToDomainReportAddressPtrOutputWithContext(ctx context.Context) DomainReportAddressPtrOutput {
	return o
}

func (o DomainReportAddressPtrOutput) Elem() DomainReportAddressOutput {
	return o.ApplyT(func(v *DomainReportAddress) DomainReportAddress {
		if v != nil {
			return *v
		}
		var ret DomainReportAddress
		return ret
	}).(DomainReportAddressOutput)
}

// Mox account that receives the reports.
func (o DomainReportAddressPtrOutput) Account() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return &v.Account
	}).(pulumi.StringPtrOutput)
}

// Report destination domain. Empty means the domain itself.
func (o DomainReportAddressPtrOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return v.Domain
	}).(pulumi.StringPtrOutput)
}

// Local part of the report destination address.
func (o DomainReportAddressPtrOutput) Localpart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return &v.Localpart
	}).(pulumi.StringPtrOutput)
}

// Destination mailbox within the account.
func (o DomainReportAddressPtrOutput) Mailbox() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainReportAddress) *string {
		if v == nil {
			return nil
		}
		return v.Mailbox
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountRouteInput)(nil)).Elem(), AccountRouteArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountRouteArrayInput)(nil)).Elem(), AccountRouteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainLocalpartConfigInput)(nil)).Elem(), DomainLocalpartConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainLocalpartConfigPtrInput)(nil)).Elem(), DomainLocalpartConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMtaStsInput)(nil)).Elem(), DomainMtaStsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMtaStsPtrInput)(nil)).Elem(), DomainMtaStsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainReportAddressInput)(nil)).Elem(), DomainReportAddressArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainReportAddressPtrInput)(nil)).Elem(), DomainReportAddressArgs{})
	pulumi.RegisterOutputType(AccountRouteOutput{})
	pulumi.RegisterOutputType(AccountRouteArrayOutput{})
	pulumi.RegisterOutputType(DkimDNSRecordOutput{})
	pulumi.RegisterOutputType(DkimDNSRecordArrayOutput{})
	pulumi.RegisterOutputType(DomainLocalpartConfigOutput{})
	pulumi.RegisterOutputType(DomainLocalpartConfigPtrOutput{})
	pulumi.RegisterOutputType(DomainMtaStsOutput{})
	pulumi.RegisterOutputType(DomainMtaStsPtrOutput{})
	pulumi.RegisterOutputType(DomainReportAddressOutput{})
	pulumi.RegisterOutputType(DomainReportAddressPtrOutput{})
}
