// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"errors"
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Sieve script stored on a mox account, optionally the account's active script (used for redirect-based forwarding).
type Sieve struct {
	pulumi.CustomResourceState

	// Existing mox account that owns the script.
	Account pulumi.StringOutput `pulumi:"account"`
	// When true, make this the account's active script. When false or unset, the script is stored but not activated (and deactivated if it was previously active).
	Active pulumi.BoolPtrOutput `pulumi:"active"`
	// Sieve script source. Validated by mox when stored.
	Content pulumi.StringOutput `pulumi:"content"`
	// Script name within the account.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewSieve registers a new resource with the given unique name, arguments, and options.
func NewSieve(ctx *pulumi.Context,
	name string, args *SieveArgs, opts ...pulumi.ResourceOption) (*Sieve, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Account == nil {
		return nil, errors.New("invalid value for required argument 'Account'")
	}
	if args.Content == nil {
		return nil, errors.New("invalid value for required argument 'Content'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"account",
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Sieve
	err := ctx.RegisterResource("mox:index:Sieve", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSieve gets an existing Sieve resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSieve(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SieveState, opts ...pulumi.ResourceOption) (*Sieve, error) {
	var resource Sieve
	err := ctx.ReadResource("mox:index:Sieve", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Sieve resources.
type sieveState struct {
}

type SieveState struct {
}

func (SieveState) ElementType() reflect.Type {
	return reflect.TypeOf((*sieveState)(nil)).Elem()
}

type sieveArgs struct {
	// Existing mox account that owns the script.
	Account string `pulumi:"account"`
	// When true, make this the account's active script. When false or unset, the script is stored but not activated (and deactivated if it was previously active).
	Active *bool `pulumi:"active"`
	// Sieve script source. Validated by mox when stored.
	Content string `pulumi:"content"`
	// Script name within the account.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a Sieve resource.
type SieveArgs struct {
	// Existing mox account that owns the script.
	Account pulumi.StringInput
	// When true, make this the account's active script. When false or unset, the script is stored but not activated (and deactivated if it was previously active).
	Active pulumi.BoolPtrInput
	// Sieve script source. Validated by mox when stored.
	Content pulumi.StringInput
	// Script name within the account.
	Name pulumi.StringInput
}

func (SieveArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sieveArgs)(nil)).Elem()
}

type SieveInput interface {
	pulumi.Input

	ToSieveOutput() SieveOutput
	ToSieveOutputWithContext(ctx context.Context) SieveOutput
}

func (*Sieve) ElementType() reflect.Type {
	return reflect.TypeOf((**Sieve)(nil)).Elem()
}

func (i *Sieve) ToSieveOutput() SieveOutput {
	return i.ToSieveOutputWithContext(context.Background())
}

func (i *Sieve) ToSieveOutputWithContext(ctx context.Context) SieveOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SieveOutput)
}

// SieveArrayInput is an input type that accepts SieveArray and SieveArrayOutput values.
// You can construct a concrete instance of `SieveArrayInput` via:
//
//	SieveArray{ SieveArgs{...} }
type SieveArrayInput interface {
	pulumi.Input

	ToSieveArrayOutput() SieveArrayOutput
	ToSieveArrayOutputWithContext(context.Context) SieveArrayOutput
}

type SieveArray []SieveInput

func (SieveArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Sieve)(nil)).Elem()
}

func (i SieveArray) ToSieveArrayOutput() SieveArrayOutput {
	return i.ToSieveArrayOutputWithContext(context.Background())
}

func (i SieveArray) ToSieveArrayOutputWithContext(ctx context.Context) SieveArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SieveArrayOutput)
}

// SieveMapInput is an input type that accepts SieveMap and SieveMapOutput values.
// You can construct a concrete instance of `SieveMapInput` via:
//
//	SieveMap{ "key": SieveArgs{...} }
type SieveMapInput interface {
	pulumi.Input

	ToSieveMapOutput() SieveMapOutput
	ToSieveMapOutputWithContext(context.Context) SieveMapOutput
}

type SieveMap map[string]SieveInput

func (SieveMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Sieve)(nil)).Elem()
}

func (i SieveMap) ToSieveMapOutput() SieveMapOutput {
	return i.ToSieveMapOutputWithContext(context.Background())
}

func (i SieveMap) ToSieveMapOutputWithContext(ctx context.Context) SieveMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SieveMapOutput)
}

type SieveOutput struct{ *pulumi.OutputState }

func (SieveOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Sieve)(nil)).Elem()
}

func (o SieveOutput) ToSieveOutput() SieveOutput {
	return o
}

func (o SieveOutput) ToSieveOutputWithContext(ctx context.Context) SieveOutput {
	return o
}

// Existing mox account that owns the script.
func (o SieveOutput) Account() pulumi.StringOutput {
	return o.ApplyT(func(v *Sieve) pulumi.StringOutput { return v.Account }).(pulumi.StringOutput)
}

// When true, make this the account's active script. When false or unset, the script is stored but not activated (and deactivated if it was previously active).
func (o SieveOutput) Active() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Sieve) pulumi.BoolPtrOutput { return v.Active }).(pulumi.BoolPtrOutput)
}

// Sieve script source. Validated by mox when stored.
func (o SieveOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v *Sieve) pulumi.StringOutput { return v.Content }).(pulumi.StringOutput)
}

// Script name within the account.
func (o SieveOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Sieve) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type SieveArrayOutput struct{ *pulumi.OutputState }

func (SieveArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Sieve)(nil)).Elem()
}

func (o SieveArrayOutput) ToSieveArrayOutput() SieveArrayOutput {
	return o
}

func (o SieveArrayOutput) ToSieveArrayOutputWithContext(ctx context.Context) SieveArrayOutput {
	return o
}

func (o SieveArrayOutput) Index(i pulumi.IntInput) SieveOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Sieve {
		return vs[0].([]*Sieve)[vs[1].(int)]
	}).(SieveOutput)
}

type SieveMapOutput struct{ *pulumi.OutputState }

func (SieveMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Sieve)(nil)).Elem()
}

func (o SieveMapOutput) ToSieveMapOutput() SieveMapOutput {
	return o
}

func (o SieveMapOutput) ToSieveMapOutputWithContext(ctx context.Context) SieveMapOutput {
	return o
}

func (o SieveMapOutput) MapIndex(k pulumi.StringInput) SieveOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Sieve {
		return vs[0].(map[string]*Sieve)[vs[1].(string)]
	}).(SieveOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SieveInput)(nil)).Elem(), &Sieve{})
	pulumi.RegisterInputType(reflect.TypeOf((*SieveArrayInput)(nil)).Elem(), SieveArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SieveMapInput)(nil)).Elem(), SieveMap{})
	pulumi.RegisterOutputType(SieveOutput{})
	pulumi.RegisterOutputType(SieveArrayOutput{})
	pulumi.RegisterOutputType(SieveMapOutput{})
}
