// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mox

import (
	"context"
	"reflect"

	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Mox dynamic webserver redirects and handlers.
type WebserverConfig struct {
	pulumi.CustomResourceState

	// Ordered web handlers for static files, redirects, reverse proxies, or internal services.
	Handlers WebHandlerArrayOutput `pulumi:"handlers"`
	// Domain-to-domain HTTPS redirects.
	Redirects WebDomainRedirectArrayOutput `pulumi:"redirects"`
}

// NewWebserverConfig registers a new resource with the given unique name, arguments, and options.
func NewWebserverConfig(ctx *pulumi.Context,
	name string, args *WebserverConfigArgs, opts ...pulumi.ResourceOption) (*WebserverConfig, error) {
	if args == nil {
		args = &WebserverConfigArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WebserverConfig
	err := ctx.RegisterResource("mox:index:WebserverConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWebserverConfig gets an existing WebserverConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWebserverConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WebserverConfigState, opts ...pulumi.ResourceOption) (*WebserverConfig, error) {
	var resource WebserverConfig
	err := ctx.ReadResource("mox:index:WebserverConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WebserverConfig resources.
type webserverConfigState struct {
}

type WebserverConfigState struct {
}

func (WebserverConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*webserverConfigState)(nil)).Elem()
}

type webserverConfigArgs struct {
	// Ordered web handlers for static files, redirects, reverse proxies, or internal services.
	Handlers []WebHandler `pulumi:"handlers"`
	// Domain-to-domain HTTPS redirects.
	Redirects []WebDomainRedirect `pulumi:"redirects"`
}

// The set of arguments for constructing a WebserverConfig resource.
type WebserverConfigArgs struct {
	// Ordered web handlers for static files, redirects, reverse proxies, or internal services.
	Handlers WebHandlerArrayInput
	// Domain-to-domain HTTPS redirects.
	Redirects WebDomainRedirectArrayInput
}

func (WebserverConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*webserverConfigArgs)(nil)).Elem()
}

type WebserverConfigInput interface {
	pulumi.Input

	ToWebserverConfigOutput() WebserverConfigOutput
	ToWebserverConfigOutputWithContext(ctx context.Context) WebserverConfigOutput
}

func (*WebserverConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**WebserverConfig)(nil)).Elem()
}

func (i *WebserverConfig) ToWebserverConfigOutput() WebserverConfigOutput {
	return i.ToWebserverConfigOutputWithContext(context.Background())
}

func (i *WebserverConfig) ToWebserverConfigOutputWithContext(ctx context.Context) WebserverConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebserverConfigOutput)
}

// WebserverConfigArrayInput is an input type that accepts WebserverConfigArray and WebserverConfigArrayOutput values.
// You can construct a concrete instance of `WebserverConfigArrayInput` via:
//
//	WebserverConfigArray{ WebserverConfigArgs{...} }
type WebserverConfigArrayInput interface {
	pulumi.Input

	ToWebserverConfigArrayOutput() WebserverConfigArrayOutput
	ToWebserverConfigArrayOutputWithContext(context.Context) WebserverConfigArrayOutput
}

type WebserverConfigArray []WebserverConfigInput

func (WebserverConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WebserverConfig)(nil)).Elem()
}

func (i WebserverConfigArray) ToWebserverConfigArrayOutput() WebserverConfigArrayOutput {
	return i.ToWebserverConfigArrayOutputWithContext(context.Background())
}

func (i WebserverConfigArray) ToWebserverConfigArrayOutputWithContext(ctx context.Context) WebserverConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebserverConfigArrayOutput)
}

// WebserverConfigMapInput is an input type that accepts WebserverConfigMap and WebserverConfigMapOutput values.
// You can construct a concrete instance of `WebserverConfigMapInput` via:
//
//	WebserverConfigMap{ "key": WebserverConfigArgs{...} }
type WebserverConfigMapInput interface {
	pulumi.Input

	ToWebserverConfigMapOutput() WebserverConfigMapOutput
	ToWebserverConfigMapOutputWithContext(context.Context) WebserverConfigMapOutput
}

type WebserverConfigMap map[string]WebserverConfigInput

func (WebserverConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WebserverConfig)(nil)).Elem()
}

func (i WebserverConfigMap) ToWebserverConfigMapOutput() WebserverConfigMapOutput {
	return i.ToWebserverConfigMapOutputWithContext(context.Background())
}

func (i WebserverConfigMap) ToWebserverConfigMapOutputWithContext(ctx context.Context) WebserverConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebserverConfigMapOutput)
}

type WebserverConfigOutput struct{ *pulumi.OutputState }

func (WebserverConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebserverConfig)(nil)).Elem()
}

func (o WebserverConfigOutput) ToWebserverConfigOutput() WebserverConfigOutput {
	return o
}

func (o WebserverConfigOutput) ToWebserverConfigOutputWithContext(ctx context.Context) WebserverConfigOutput {
	return o
}

// Ordered web handlers for static files, redirects, reverse proxies, or internal services.
func (o WebserverConfigOutput) Handlers() WebHandlerArrayOutput {
	return o.ApplyT(func(v *WebserverConfig) WebHandlerArrayOutput { return v.Handlers }).(WebHandlerArrayOutput)
}

// Domain-to-domain HTTPS redirects.
func (o WebserverConfigOutput) Redirects() WebDomainRedirectArrayOutput {
	return o.ApplyT(func(v *WebserverConfig) WebDomainRedirectArrayOutput { return v.Redirects }).(WebDomainRedirectArrayOutput)
}

type WebserverConfigArrayOutput struct{ *pulumi.OutputState }

func (WebserverConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WebserverConfig)(nil)).Elem()
}

func (o WebserverConfigArrayOutput) ToWebserverConfigArrayOutput() WebserverConfigArrayOutput {
	return o
}

func (o WebserverConfigArrayOutput) ToWebserverConfigArrayOutputWithContext(ctx context.Context) WebserverConfigArrayOutput {
	return o
}

func (o WebserverConfigArrayOutput) Index(i pulumi.IntInput) WebserverConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WebserverConfig {
		return vs[0].([]*WebserverConfig)[vs[1].(int)]
	}).(WebserverConfigOutput)
}

type WebserverConfigMapOutput struct{ *pulumi.OutputState }

func (WebserverConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WebserverConfig)(nil)).Elem()
}

func (o WebserverConfigMapOutput) ToWebserverConfigMapOutput() WebserverConfigMapOutput {
	return o
}

func (o WebserverConfigMapOutput) ToWebserverConfigMapOutputWithContext(ctx context.Context) WebserverConfigMapOutput {
	return o
}

func (o WebserverConfigMapOutput) MapIndex(k pulumi.StringInput) WebserverConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WebserverConfig {
		return vs[0].(map[string]*WebserverConfig)[vs[1].(string)]
	}).(WebserverConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebserverConfigInput)(nil)).Elem(), &WebserverConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebserverConfigArrayInput)(nil)).Elem(), WebserverConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebserverConfigMapInput)(nil)).Elem(), WebserverConfigMap{})
	pulumi.RegisterOutputType(WebserverConfigOutput{})
	pulumi.RegisterOutputType(WebserverConfigArrayOutput{})
	pulumi.RegisterOutputType(WebserverConfigMapOutput{})
}
