// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/hilli/pulumi-mox/sdk/go/mox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Password for the mox admin LoginPrep/Login flow.
func GetAdminPassword(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mox:adminPassword")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MOX_ADMIN_PASSWORD"); d != nil {
		value = d.(string)
	}
	return value
}

// Base URL of the mox admin interface, e.g. https://mox-admin.example.com.
func GetAdminUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mox:adminUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "MOX_ADMIN_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Disable TLS certificate verification (dev/self-signed only).
func GetInsecureSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "mox:insecureSkipVerify")
}
