// Code generated by gen_moxapi.py from mox webadmin/api.json; DO NOT EDIT.

// Package moxapi contains faithful, read-only Go types mirroring the mox
// webadmin sherpa API return values. Each field carries a json tag (the
// sherpa wire name) and a pulumi tag (the generated schema property name).
package moxapi

type Account struct {
	OutgoingWebhook              *OutgoingWebhook       `json:"OutgoingWebhook" pulumi:"outgoingWebhook,optional"`
	IncomingWebhook              *IncomingWebhook       `json:"IncomingWebhook" pulumi:"incomingWebhook,optional"`
	FromIDLoginAddresses         []string               `json:"FromIDLoginAddresses" pulumi:"fromIDLoginAddresses,optional"`
	KeepRetiredMessagePeriod     int64                  `json:"KeepRetiredMessagePeriod" pulumi:"keepRetiredMessagePeriod"`
	KeepRetiredWebhookPeriod     int64                  `json:"KeepRetiredWebhookPeriod" pulumi:"keepRetiredWebhookPeriod"`
	LoginDisabled                string                 `json:"LoginDisabled" pulumi:"loginDisabled"`
	Domain                       string                 `json:"Domain" pulumi:"domain"`
	Description                  string                 `json:"Description" pulumi:"description"`
	FullName                     string                 `json:"FullName" pulumi:"fullName"`
	Destinations                 map[string]Destination `json:"Destinations" pulumi:"destinations,optional"`
	SubjectPass                  SubjectPass            `json:"SubjectPass" pulumi:"subjectPass"`
	QuotaMessageSize             int64                  `json:"QuotaMessageSize" pulumi:"quotaMessageSize"`
	RejectsMailbox               string                 `json:"RejectsMailbox" pulumi:"rejectsMailbox"`
	KeepRejects                  bool                   `json:"KeepRejects" pulumi:"keepRejects"`
	AutomaticJunkFlags           AutomaticJunkFlags     `json:"AutomaticJunkFlags" pulumi:"automaticJunkFlags"`
	JunkFilter                   *JunkFilter            `json:"JunkFilter" pulumi:"junkFilter,optional"`
	MaxOutgoingMessagesPerDay    int32                  `json:"MaxOutgoingMessagesPerDay" pulumi:"maxOutgoingMessagesPerDay"`
	MaxFirstTimeRecipientsPerDay int32                  `json:"MaxFirstTimeRecipientsPerDay" pulumi:"maxFirstTimeRecipientsPerDay"`
	NoFirstTimeSenderDelay       bool                   `json:"NoFirstTimeSenderDelay" pulumi:"noFirstTimeSenderDelay"`
	NoCustomPassword             bool                   `json:"NoCustomPassword" pulumi:"noCustomPassword"`
	IMAPCapabilitiesDisabled     []string               `json:"IMAPCapabilitiesDisabled" pulumi:"imapCapabilitiesDisabled,optional"`
	Routes                       []Route                `json:"Routes" pulumi:"routes,optional"`
	Sieve                        *Sieve                 `json:"Sieve" pulumi:"sieve,optional"`
	DNSDomain                    Domain                 `json:"DNSDomain" pulumi:"dnsDomain"`
	Aliases                      []AddressAlias         `json:"Aliases" pulumi:"aliases,optional"`
}

type Address struct {
	Localpart string `json:"Localpart" pulumi:"localpart"`
	Domain    Domain `json:"Domain" pulumi:"domain"`
}

type AddressAlias struct {
	SubscriptionAddress string   `json:"SubscriptionAddress" pulumi:"subscriptionAddress"`
	Alias               Alias    `json:"Alias" pulumi:"alias"`
	MemberAddresses     []string `json:"MemberAddresses" pulumi:"memberAddresses,optional"`
}

type Alias struct {
	Addresses       []string       `json:"Addresses" pulumi:"addresses,optional"`
	PostPublic      bool           `json:"PostPublic" pulumi:"postPublic"`
	ListMembers     bool           `json:"ListMembers" pulumi:"listMembers"`
	AllowMsgFrom    bool           `json:"AllowMsgFrom" pulumi:"allowMsgFrom"`
	LocalpartStr    string         `json:"LocalpartStr" pulumi:"localpartStr"`
	Domain          Domain         `json:"Domain" pulumi:"domain"`
	ParsedAddresses []AliasAddress `json:"ParsedAddresses" pulumi:"parsedAddresses,optional"`
}

type AliasAddress struct {
	Address     Address     `json:"Address" pulumi:"address"`
	AccountName string      `json:"AccountName" pulumi:"accountName"`
	Destination Destination `json:"Destination" pulumi:"destination"`
}

type AutoconfCheckResult struct {
	ClientSettingsDomainIPs []string `json:"ClientSettingsDomainIPs" pulumi:"clientSettingsDomainIPs,optional"`
	IPs                     []string `json:"IPs" pulumi:"ips,optional"`
	Errors                  []string `json:"Errors" pulumi:"errors,optional"`
	Warnings                []string `json:"Warnings" pulumi:"warnings,optional"`
	Instructions            []string `json:"Instructions" pulumi:"instructions,optional"`
}

type AutodiscoverCheckResult struct {
	Records      []AutodiscoverSRV `json:"Records" pulumi:"records,optional"`
	Errors       []string          `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string          `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string          `json:"Instructions" pulumi:"instructions,optional"`
}

type AutodiscoverSRV struct {
	Target   string   `json:"Target" pulumi:"target"`
	Port     int      `json:"Port" pulumi:"port"`
	Priority int      `json:"Priority" pulumi:"priority"`
	Weight   int      `json:"Weight" pulumi:"weight"`
	IPs      []string `json:"IPs" pulumi:"ips,optional"`
}

type AutomaticJunkFlags struct {
	Enabled              bool   `json:"Enabled" pulumi:"enabled"`
	JunkMailboxRegexp    string `json:"JunkMailboxRegexp" pulumi:"junkMailboxRegexp"`
	NeutralMailboxRegexp string `json:"NeutralMailboxRegexp" pulumi:"neutralMailboxRegexp"`
	NotJunkMailboxRegexp string `json:"NotJunkMailboxRegexp" pulumi:"notJunkMailboxRegexp"`
}

type Canonicalization struct {
	HeaderRelaxed bool `json:"HeaderRelaxed" pulumi:"headerRelaxed"`
	BodyRelaxed   bool `json:"BodyRelaxed" pulumi:"bodyRelaxed"`
}

type CheckResult struct {
	Domain       string                  `json:"Domain" pulumi:"domain"`
	DNSSEC       DNSSECResult            `json:"DNSSEC" pulumi:"dnssec"`
	IPRev        IPRevCheckResult        `json:"IPRev" pulumi:"ipRev"`
	MX           MXCheckResult           `json:"MX" pulumi:"mx"`
	TLS          TLSCheckResult          `json:"TLS" pulumi:"tls"`
	DANE         DANECheckResult         `json:"DANE" pulumi:"dane"`
	SPF          SPFCheckResult          `json:"SPF" pulumi:"spf"`
	DKIM         DKIMCheckResult         `json:"DKIM" pulumi:"dkim"`
	DMARC        DMARCCheckResult        `json:"DMARC" pulumi:"dmarc"`
	HostTLSRPT   TLSRPTCheckResult       `json:"HostTLSRPT" pulumi:"hostTLSRPT"`
	DomainTLSRPT TLSRPTCheckResult       `json:"DomainTLSRPT" pulumi:"domainTLSRPT"`
	MTASTS       MTASTSCheckResult       `json:"MTASTS" pulumi:"mtasts"`
	SRVConf      SRVConfCheckResult      `json:"SRVConf" pulumi:"srvConf"`
	Autoconf     AutoconfCheckResult     `json:"Autoconf" pulumi:"autoconf"`
	Autodiscover AutodiscoverCheckResult `json:"Autodiscover" pulumi:"autodiscover"`
}

type ClientConfigs struct {
	Entries []ClientConfigsEntry `json:"Entries" pulumi:"entries,optional"`
}

type ClientConfigsEntry struct {
	Protocol string `json:"Protocol" pulumi:"protocol"`
	Host     Domain `json:"Host" pulumi:"host"`
	Port     int32  `json:"Port" pulumi:"port"`
	Listener string `json:"Listener" pulumi:"listener"`
	Note     string `json:"Note" pulumi:"note"`
}

type ConfigDomain struct {
	Disabled                             bool             `json:"Disabled" pulumi:"disabled"`
	Description                          string           `json:"Description" pulumi:"description"`
	ClientSettingsDomain                 string           `json:"ClientSettingsDomain" pulumi:"clientSettingsDomain"`
	LocalpartCatchallSeparator           string           `json:"LocalpartCatchallSeparator" pulumi:"localpartCatchallSeparator"`
	LocalpartCatchallSeparators          []string         `json:"LocalpartCatchallSeparators" pulumi:"localpartCatchallSeparators,optional"`
	LocalpartCaseSensitive               bool             `json:"LocalpartCaseSensitive" pulumi:"localpartCaseSensitive"`
	DKIM                                 DKIM             `json:"DKIM" pulumi:"dkim"`
	DMARC                                *DMARC           `json:"DMARC" pulumi:"dmarc,optional"`
	MTASTS                               *MTASTS          `json:"MTASTS" pulumi:"mtasts,optional"`
	TLSRPT                               *TLSRPT          `json:"TLSRPT" pulumi:"tlsrpt,optional"`
	Routes                               []Route          `json:"Routes" pulumi:"routes,optional"`
	Aliases                              map[string]Alias `json:"Aliases" pulumi:"aliases,optional"`
	Sieve                                *Sieve           `json:"Sieve" pulumi:"sieve,optional"`
	Domain                               Domain           `json:"Domain" pulumi:"domain"`
	LocalpartCatchallSeparatorsEffective []string         `json:"LocalpartCatchallSeparatorsEffective" pulumi:"localpartCatchallSeparatorsEffective,optional"`
}

type DANECheckResult struct {
	Errors       []string `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string `json:"Instructions" pulumi:"instructions,optional"`
}

type DKIM struct {
	Selectors map[string]Selector `json:"Selectors" pulumi:"selectors,optional"`
	Sign      []string            `json:"Sign" pulumi:"sign,optional"`
}

type DKIMCheckResult struct {
	Records      []DKIMRecord `json:"Records" pulumi:"records,optional"`
	Errors       []string     `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string     `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string     `json:"Instructions" pulumi:"instructions,optional"`
}

type DKIMRecord struct {
	Selector string  `json:"Selector" pulumi:"selector"`
	TXT      string  `json:"TXT" pulumi:"txt"`
	Record   *Record `json:"Record" pulumi:"record,optional"`
}

type DMARC struct {
	Localpart       string `json:"Localpart" pulumi:"localpart"`
	Domain          string `json:"Domain" pulumi:"domain"`
	Account         string `json:"Account" pulumi:"account"`
	Mailbox         string `json:"Mailbox" pulumi:"mailbox"`
	ParsedLocalpart string `json:"ParsedLocalpart" pulumi:"parsedLocalpart"`
	DNSDomain       Domain `json:"DNSDomain" pulumi:"dnsDomain"`
}

type DMARCCheckResult struct {
	Domain       string       `json:"Domain" pulumi:"domain"`
	TXT          string       `json:"TXT" pulumi:"txt"`
	Record       *DMARCRecord `json:"Record" pulumi:"record,optional"`
	Errors       []string     `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string     `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string     `json:"Instructions" pulumi:"instructions,optional"`
}

type DMARCRecord struct {
	Version                    string   `json:"Version" pulumi:"version"`
	Policy                     string   `json:"Policy" pulumi:"policy"`
	SubdomainPolicy            string   `json:"SubdomainPolicy" pulumi:"subdomainPolicy"`
	AggregateReportAddresses   []URI    `json:"AggregateReportAddresses" pulumi:"aggregateReportAddresses,optional"`
	FailureReportAddresses     []URI    `json:"FailureReportAddresses" pulumi:"failureReportAddresses,optional"`
	ADKIM                      string   `json:"ADKIM" pulumi:"adkim"`
	ASPF                       string   `json:"ASPF" pulumi:"aspf"`
	AggregateReportingInterval int32    `json:"AggregateReportingInterval" pulumi:"aggregateReportingInterval"`
	FailureReportingOptions    []string `json:"FailureReportingOptions" pulumi:"failureReportingOptions,optional"`
	ReportingFormat            []string `json:"ReportingFormat" pulumi:"reportingFormat,optional"`
	Percentage                 int32    `json:"Percentage" pulumi:"percentage"`
}

type DNSSECResult struct {
	Errors       []string `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string `json:"Instructions" pulumi:"instructions,optional"`
}

type Destination struct {
	Mailbox                      string    `json:"Mailbox" pulumi:"mailbox"`
	Rulesets                     []Ruleset `json:"Rulesets" pulumi:"rulesets,optional"`
	SMTPError                    string    `json:"SMTPError" pulumi:"smtpError"`
	MessageAuthRequiredSMTPError string    `json:"MessageAuthRequiredSMTPError" pulumi:"messageAuthRequiredSMTPError"`
	FullName                     string    `json:"FullName" pulumi:"fullName"`
}

type Directive struct {
	Qualifier  string `json:"Qualifier" pulumi:"qualifier"`
	Mechanism  string `json:"Mechanism" pulumi:"mechanism"`
	DomainSpec string `json:"DomainSpec" pulumi:"domainSpec"`
	IPstr      string `json:"IPstr" pulumi:"ipstr"`
	IP4CIDRLen *int32 `json:"IP4CIDRLen" pulumi:"ip4CIDRLen,optional"`
	IP6CIDRLen *int32 `json:"IP6CIDRLen" pulumi:"ip6CIDRLen,optional"`
}

type Domain struct {
	ASCII   string `json:"ASCII" pulumi:"ascii"`
	Unicode string `json:"Unicode" pulumi:"unicode"`
}

type Dynamic struct {
	Domains            map[string]ConfigDomain `json:"Domains" pulumi:"domains,optional"`
	Accounts           map[string]Account      `json:"Accounts" pulumi:"accounts,optional"`
	WebDomainRedirects map[string]string       `json:"WebDomainRedirects" pulumi:"webDomainRedirects,optional"`
	WebHandlers        []WebHandler            `json:"WebHandlers" pulumi:"webHandlers,optional"`
	Routes             []Route                 `json:"Routes" pulumi:"routes,optional"`
	MonitorDNSBLs      []string                `json:"MonitorDNSBLs" pulumi:"monitorDNSBLs,optional"`
	MonitorDNSBLZones  []Domain                `json:"MonitorDNSBLZones" pulumi:"monitorDNSBLZones,optional"`
}

type Extension struct {
	Key   string `json:"Key" pulumi:"key"`
	Value string `json:"Value" pulumi:"value"`
}

type IPRevCheckResult struct {
	Hostname     Domain              `json:"Hostname" pulumi:"hostname"`
	IPNames      map[string][]string `json:"IPNames" pulumi:"ipNames,optional"`
	Errors       []string            `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string            `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string            `json:"Instructions" pulumi:"instructions,optional"`
}

type IncomingWebhook struct {
	URL           string `json:"URL" pulumi:"url"`
	Authorization string `json:"Authorization" pulumi:"authorization"`
}

type JunkFilter struct {
	Threshold   float64 `json:"Threshold" pulumi:"threshold"`
	Onegrams    bool    `json:"Onegrams" pulumi:"onegrams"`
	Twograms    bool    `json:"Twograms" pulumi:"twograms"`
	Threegrams  bool    `json:"Threegrams" pulumi:"threegrams"`
	MaxPower    float64 `json:"MaxPower" pulumi:"maxPower"`
	TopWords    int32   `json:"TopWords" pulumi:"topWords"`
	IgnoreWords float64 `json:"IgnoreWords" pulumi:"ignoreWords"`
	RareWords   int32   `json:"RareWords" pulumi:"rareWords"`
}

type LoginAttempt struct {
	Key                  []int  `json:"Key" pulumi:"key,optional"`
	Last                 string `json:"Last" pulumi:"last"`
	First                string `json:"First" pulumi:"first"`
	Count                int64  `json:"Count" pulumi:"count"`
	AccountName          string `json:"AccountName" pulumi:"accountName"`
	LoginAddress         string `json:"LoginAddress" pulumi:"loginAddress"`
	RemoteIP             string `json:"RemoteIP" pulumi:"remoteIP"`
	LocalIP              string `json:"LocalIP" pulumi:"localIP"`
	TLS                  string `json:"TLS" pulumi:"tls"`
	TLSPubKeyFingerprint string `json:"TLSPubKeyFingerprint" pulumi:"tlsPubKeyFingerprint"`
	Protocol             string `json:"Protocol" pulumi:"protocol"`
	UserAgent            string `json:"UserAgent" pulumi:"userAgent"`
	AuthMech             string `json:"AuthMech" pulumi:"authMech"`
	Result               string `json:"Result" pulumi:"result"`
}

type MTASTS struct {
	PolicyID string   `json:"PolicyID" pulumi:"policyID"`
	Mode     string   `json:"Mode" pulumi:"mode"`
	MaxAge   int64    `json:"MaxAge" pulumi:"maxAge"`
	MX       []string `json:"MX" pulumi:"mx,optional"`
}

type MTASTSCheckResult struct {
	TXT          string        `json:"TXT" pulumi:"txt"`
	Record       *MTASTSRecord `json:"Record" pulumi:"record,optional"`
	PolicyText   string        `json:"PolicyText" pulumi:"policyText"`
	Policy       *Policy       `json:"Policy" pulumi:"policy,optional"`
	Errors       []string      `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string      `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string      `json:"Instructions" pulumi:"instructions,optional"`
}

type MTASTSRecord struct {
	Version    string `json:"Version" pulumi:"version"`
	ID         string `json:"ID" pulumi:"id"`
	Extensions []Pair `json:"Extensions" pulumi:"extensions,optional"`
}

type MX struct {
	Host string   `json:"Host" pulumi:"host"`
	Pref int32    `json:"Pref" pulumi:"pref"`
	IPs  []string `json:"IPs" pulumi:"ips,optional"`
}

type MXCheckResult struct {
	Records      []MX     `json:"Records" pulumi:"records,optional"`
	Errors       []string `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string `json:"Instructions" pulumi:"instructions,optional"`
}

type Modifier struct {
	Key   string `json:"Key" pulumi:"key"`
	Value string `json:"Value" pulumi:"value"`
}

type OutgoingWebhook struct {
	URL           string   `json:"URL" pulumi:"url"`
	Authorization string   `json:"Authorization" pulumi:"authorization"`
	Events        []string `json:"Events" pulumi:"events,optional"`
}

type Pair struct {
	Key   string `json:"Key" pulumi:"key"`
	Value string `json:"Value" pulumi:"value"`
}

type Policy struct {
	Version       string  `json:"Version" pulumi:"version"`
	Mode          string  `json:"Mode" pulumi:"mode"`
	MX            []STSMX `json:"MX" pulumi:"mx,optional"`
	MaxAgeSeconds int32   `json:"MaxAgeSeconds" pulumi:"maxAgeSeconds"`
	Extensions    []Pair  `json:"Extensions" pulumi:"extensions,optional"`
}

type Record struct {
	Version  string   `json:"Version" pulumi:"version"`
	Hashes   []string `json:"Hashes" pulumi:"hashes,optional"`
	Key      string   `json:"Key" pulumi:"key"`
	Notes    string   `json:"Notes" pulumi:"notes"`
	Pubkey   []int    `json:"Pubkey" pulumi:"pubkey,optional"`
	Services []string `json:"Services" pulumi:"services,optional"`
	Flags    []string `json:"Flags" pulumi:"flags,optional"`
}

type Route struct {
	FromDomain      []string `json:"FromDomain" pulumi:"fromDomain,optional"`
	ToDomain        []string `json:"ToDomain" pulumi:"toDomain,optional"`
	MinimumAttempts int32    `json:"MinimumAttempts" pulumi:"minimumAttempts"`
	Transport       string   `json:"Transport" pulumi:"transport"`
	FromDomainASCII []string `json:"FromDomainASCII" pulumi:"fromDomainASCII,optional"`
	ToDomainASCII   []string `json:"ToDomainASCII" pulumi:"toDomainASCII,optional"`
}

type Ruleset struct {
	SMTPMailFromRegexp     string            `json:"SMTPMailFromRegexp" pulumi:"smtpMailFromRegexp"`
	MsgFromRegexp          string            `json:"MsgFromRegexp" pulumi:"msgFromRegexp"`
	VerifiedDomain         string            `json:"VerifiedDomain" pulumi:"verifiedDomain"`
	HeadersRegexp          map[string]string `json:"HeadersRegexp" pulumi:"headersRegexp,optional"`
	IsForward              bool              `json:"IsForward" pulumi:"isForward"`
	ListAllowDomain        string            `json:"ListAllowDomain" pulumi:"listAllowDomain"`
	AcceptRejectsToMailbox string            `json:"AcceptRejectsToMailbox" pulumi:"acceptRejectsToMailbox"`
	Mailbox                string            `json:"Mailbox" pulumi:"mailbox"`
	Comment                string            `json:"Comment" pulumi:"comment"`
	VerifiedDNSDomain      Domain            `json:"VerifiedDNSDomain" pulumi:"verifiedDNSDomain"`
	ListAllowDNSDomain     Domain            `json:"ListAllowDNSDomain" pulumi:"listAllowDNSDomain"`
}

type SPFCheckResult struct {
	DomainTXT    string     `json:"DomainTXT" pulumi:"domainTXT"`
	DomainRecord *SPFRecord `json:"DomainRecord" pulumi:"domainRecord,optional"`
	HostTXT      string     `json:"HostTXT" pulumi:"hostTXT"`
	HostRecord   *SPFRecord `json:"HostRecord" pulumi:"hostRecord,optional"`
	Errors       []string   `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string   `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string   `json:"Instructions" pulumi:"instructions,optional"`
}

type SPFRecord struct {
	Version     string      `json:"Version" pulumi:"version"`
	Directives  []Directive `json:"Directives" pulumi:"directives,optional"`
	Redirect    string      `json:"Redirect" pulumi:"redirect"`
	Explanation string      `json:"Explanation" pulumi:"explanation"`
	Other       []Modifier  `json:"Other" pulumi:"other,optional"`
}

type SRV struct {
	Target   string `json:"Target" pulumi:"target"`
	Port     int    `json:"Port" pulumi:"port"`
	Priority int    `json:"Priority" pulumi:"priority"`
	Weight   int    `json:"Weight" pulumi:"weight"`
}

type SRVConfCheckResult struct {
	SRVs         map[string][]SRV `json:"SRVs" pulumi:"srvs,optional"`
	Errors       []string         `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string         `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string         `json:"Instructions" pulumi:"instructions,optional"`
}

type STSMX struct {
	Wildcard bool   `json:"Wildcard" pulumi:"wildcard"`
	Domain   Domain `json:"Domain" pulumi:"domain"`
}

type Selector struct {
	Hash             string           `json:"Hash" pulumi:"hash"`
	HashEffective    string           `json:"HashEffective" pulumi:"hashEffective"`
	Canonicalization Canonicalization `json:"Canonicalization" pulumi:"canonicalization"`
	Headers          []string         `json:"Headers" pulumi:"headers,optional"`
	HeadersEffective []string         `json:"HeadersEffective" pulumi:"headersEffective,optional"`
	DontSealHeaders  bool             `json:"DontSealHeaders" pulumi:"dontSealHeaders"`
	Expiration       string           `json:"Expiration" pulumi:"expiration"`
	PrivateKeyFile   string           `json:"PrivateKeyFile" pulumi:"privateKeyFile"`
	Algorithm        string           `json:"Algorithm" pulumi:"algorithm"`
}

type Sieve struct {
	Enabled             *bool  `json:"Enabled" pulumi:"enabled,optional"`
	MaxScriptSize       int64  `json:"MaxScriptSize" pulumi:"maxScriptSize"`
	MaxScripts          int32  `json:"MaxScripts" pulumi:"maxScripts"`
	MaxTotalScriptSize  int64  `json:"MaxTotalScriptSize" pulumi:"maxTotalScriptSize"`
	ExecutionTimeout    int64  `json:"ExecutionTimeout" pulumi:"executionTimeout"`
	MaxRedirects        int32  `json:"MaxRedirects" pulumi:"maxRedirects"`
	AutoCreateMailboxes *bool  `json:"AutoCreateMailboxes" pulumi:"autoCreateMailboxes,optional"`
	RunOnDelivery       *bool  `json:"RunOnDelivery" pulumi:"runOnDelivery,optional"`
	RunOnIMAPEvents     *bool  `json:"RunOnIMAPEvents" pulumi:"runOnIMAPEvents,optional"`
	FailureMode         string `json:"FailureMode" pulumi:"failureMode"`
}

type SubjectPass struct {
	Period int64 `json:"Period" pulumi:"period"`
}

type TLSCheckResult struct {
	Errors       []string `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string `json:"Instructions" pulumi:"instructions,optional"`
}

type TLSPublicKey struct {
	Fingerprint   string `json:"Fingerprint" pulumi:"fingerprint"`
	Created       string `json:"Created" pulumi:"created"`
	Type          string `json:"Type" pulumi:"type"`
	Name          string `json:"Name" pulumi:"name"`
	NoIMAPPreauth bool   `json:"NoIMAPPreauth" pulumi:"noIMAPPreauth"`
	CertDER       []int  `json:"CertDER" pulumi:"certDER,optional"`
	Account       string `json:"Account" pulumi:"account"`
	LoginAddress  string `json:"LoginAddress" pulumi:"loginAddress"`
}

type TLSRPT struct {
	Localpart       string `json:"Localpart" pulumi:"localpart"`
	Domain          string `json:"Domain" pulumi:"domain"`
	Account         string `json:"Account" pulumi:"account"`
	Mailbox         string `json:"Mailbox" pulumi:"mailbox"`
	ParsedLocalpart string `json:"ParsedLocalpart" pulumi:"parsedLocalpart"`
	DNSDomain       Domain `json:"DNSDomain" pulumi:"dnsDomain"`
}

type TLSRPTCheckResult struct {
	TXT          string        `json:"TXT" pulumi:"txt"`
	Record       *TLSRPTRecord `json:"Record" pulumi:"record,optional"`
	Errors       []string      `json:"Errors" pulumi:"errors,optional"`
	Warnings     []string      `json:"Warnings" pulumi:"warnings,optional"`
	Instructions []string      `json:"Instructions" pulumi:"instructions,optional"`
}

type TLSRPTRecord struct {
	Version    string      `json:"Version" pulumi:"version"`
	RUAs       [][]string  `json:"RUAs" pulumi:"ruas,optional"`
	Extensions []Extension `json:"Extensions" pulumi:"extensions,optional"`
}

type URI struct {
	Address string `json:"Address" pulumi:"address"`
	MaxSize int    `json:"MaxSize" pulumi:"maxSize"`
	Unit    string `json:"Unit" pulumi:"unit"`
}

type WebForward struct {
	StripPath       bool              `json:"StripPath" pulumi:"stripPath"`
	URL             string            `json:"URL" pulumi:"url"`
	ResponseHeaders map[string]string `json:"ResponseHeaders" pulumi:"responseHeaders,optional"`
}

type WebHandler struct {
	LogName               string       `json:"LogName" pulumi:"logName"`
	Domain                string       `json:"Domain" pulumi:"domain"`
	PathRegexp            string       `json:"PathRegexp" pulumi:"pathRegexp"`
	DontRedirectPlainHTTP bool         `json:"DontRedirectPlainHTTP" pulumi:"dontRedirectPlainHTTP"`
	Compress              bool         `json:"Compress" pulumi:"compress"`
	WebStatic             *WebStatic   `json:"WebStatic" pulumi:"webStatic,optional"`
	WebRedirect           *WebRedirect `json:"WebRedirect" pulumi:"webRedirect,optional"`
	WebForward            *WebForward  `json:"WebForward" pulumi:"webForward,optional"`
	WebInternal           *WebInternal `json:"WebInternal" pulumi:"webInternal,optional"`
	Name                  string       `json:"Name" pulumi:"name"`
	DNSDomain             Domain       `json:"DNSDomain" pulumi:"dnsDomain"`
}

type WebInternal struct {
	BasePath string `json:"BasePath" pulumi:"basePath"`
	Service  string `json:"Service" pulumi:"service"`
}

type WebRedirect struct {
	BaseURL        string `json:"BaseURL" pulumi:"baseURL"`
	OrigPathRegexp string `json:"OrigPathRegexp" pulumi:"origPathRegexp"`
	ReplacePath    string `json:"ReplacePath" pulumi:"replacePath"`
	StatusCode     int32  `json:"StatusCode" pulumi:"statusCode"`
}

type WebStatic struct {
	StripPrefix      string            `json:"StripPrefix" pulumi:"stripPrefix"`
	Root             string            `json:"Root" pulumi:"root"`
	ListFiles        bool              `json:"ListFiles" pulumi:"listFiles"`
	ContinueNotFound bool              `json:"ContinueNotFound" pulumi:"continueNotFound"`
	ResponseHeaders  map[string]string `json:"ResponseHeaders" pulumi:"responseHeaders,optional"`
}
